### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CameronASC20** [sei-ec-remote/team-project-issues#10]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
Having trouble display data

**Expected behavior**
_A clear and concise description of what you expected to happen._
data from api should be displayed

**What is the actual behavior?**
_A clear and concise description of what actually happened._
nothing

**Post any code you think might be relevant (one fenced block per file)**
```js
const IndexFaves = (props) => {
    const [faves, setFaves] = useState(null)
    useEffect(() => {
        getAllFav()
            .then(res => {
                console.log(res.data.faves)
                setFaves(res.data.faves)
            })
            .catch(console.error)
    }, [])
```

**What is your best guess as to the source of the problem?**
No idea

**What things have you already tried to solve the problem?**
Asking team members

**Additional context**

**Paste a link to your repository here**
https://github.com/CameronASC20/Bird-client

**Comment by cory-yonomi** [comment]
Can you add the code where you call the data to display it?

**Comment by CameronASC20** [comment]
```
// index function
export const getAllFav = () => {
    return axios(`${apiUrl}/favorites`)
}
```

**Comment by CameronASC20** [comment]
I am having an issue connecting to my local host. I am getting a weird error.

**Comment by CameronASC20** [comment]
![Screenshot from 2022-04-05 15-51-05](https://user-images.githubusercontent.com/68292255/161837909-e1f39c01-a8d1-4e91-af95-e64484a5027a.png)

**Comment by cory-yonomi** [comment]
Fixed connection string
