### ISSUE TITLE
Socket.io debug

### ISSUE THREAD

**Issue by Abdisheik3** [sei-ec-remote/team-project-issues#101]
**Describe the bug**
_A clear and concise description of what the bug is._
I am using socket.io with okta and it working fine on my testing repo but when I try to implement it into the project repo it stops working.

**What is the problem you are trying to solve?**
I am trying to make it functional on the project repo.

**Expected behavior**
_A clear and concise description of what you expected to happen._
when I type something in the text box it should log what was said and what time.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
when I type something and hit enter nothing comes up.

**Post any code you think might be relevant (one fenced block per file)**
```js
I don't have a specific code but I do have to package.json
```

**What is your best guess as to the source of the problem?**

My guess is its trying to run on a different server because it uses PORT=8080

**What things have you already tried to solve the problem?**
I've tried breaking the code, making a new repo and testing things there.

**Additional context**
Also I can't log in to the app

**Paste a link to your repository here**
https://github.com/Abdisheik3/player-client
https://github.com/Abdisheik3/player-api

**Comment by timmshinbone** [comment]
Share the code(a link to a GH repo is fine) for your test repo and the link to whatever tutorial/docs you used to put it together so I can see how they have you using it. 

Also, I'm interested to see if your project has an `env` file which I'm fairly sure `socket.io` will need

**Comment by Abdisheik3** [comment]
it does have and env file

**Comment by Abdisheik3** [comment]
https://github.com/Abdisheik3/test-api
https://github.com/Abdisheik3/test-client
these are the repo that it's working on.

**Comment by timmshinbone** [comment]
Ok, and where's the tutorial you pulled this from? Got a link to it?

**Comment by Abdisheik3** [comment]
https://developer.okta.com/blog/2021/07/14/socket-io-react-tutorial
it works fine when I use it in my test repo but Im thinking since it uses client and server that the port are interfering with each other.

**Comment by timmshinbone** [comment]
Hey @Abdisheik3 are you still working on this? If so, share some update, if not, close the issue with your solution

**Comment by Abdisheik3** [comment]
still working on this

**Comment by Abdisheik3** [comment]
can't connect socket.io to our server

**Comment by kestler01** [comment]
hey, where is your app at and is this still an active issue ?
