### ISSUE TITLE
We are failing to make our seed script run

### ISSUE THREAD

**Issue by OnePartHarmony** [sei-ec-remote/team-project-issues#102]
**Describe the bug**
_A clear and concise description of what the bug is._

We have created a seed script based off of our last project, but it does nothing.  We know it probably has to do with the difference in the connection setup in this project, but none of us know enough about what is going on here vs last project.

**What is the problem you are trying to solve?**

Seeding the database

**Expected behavior**
_A clear and concise description of what you expected to happen._

I expected a pile of documents to appear in my database.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

 » npm run seed

> git-input@1.0.0 seed
> node app/models/seed.js

**Post any code you think might be relevant (one fenced block per file)**
```
db.on('open', () => {
  Company.deleteMany()
    .then(() => {
      Company.create(startCompanies)
        .then(data => {
            console.log(data)
            db.close()
        })
        .catch(err => {
          console.error(err)
          db.close()
        })
    })
    .catch(err => {
      console.error(err)
      db.close()
    })
})

```

**Paste a link to your repository here**

https://github.com/OnePartHarmony/WDSTF-Project3-API

Meg says,
 "I just want to add onto this issue-- for some reason I am unable to sign up or log in and we cannot figure out why. I have pulled all of the most up-to-date code from GH that the rest of the team has and theirs is working."

**Comment by megwelch** [comment]
I just want to add onto this issue-- for some reason I am unable to sign up or log in and we cannot figure out why. I have pulled all of the most up-to-date code from GH that the rest of the team has and theirs is working.

**Comment by kestler01** [comment]
@OnePartHarmony it looks like we have to add a database connect to our seed script like we do in server.js ( since it's not a route ) - see lines 32 -34 
@megwelch are you getting an error that would point us in the right direction ?

**Comment by megwelch** [comment]
@kestler01 
this is my terminal after i try to sign up:
```===== Incoming Request =====

Tue Nov 01 2022 10:52:30 GMT-0400 (Eastern Daylight Time)
POST /sign-up
body {"credentials":{"username":"k@k.com","password":"k","password_confirmation":"k"}}

============================


 10:52:30 GMT-0400 (Eastern Daylight Time):
MongoServerError: E11000 duplicate key error collection: express-auth-template-development.users index: email_1 dup key: { email: null }
    at /Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/operations/insert.js:53:33
    at /Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/cmap/connection_pool.js:308:25
    at /Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/sdam/server.js:213:17
    at handleOperationResult (/Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/sdam/server.js:329:20)
    at Connection.onMessage (/Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/cmap/connection.js:219:9)
    at MessageStream.<anonymous> (/Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/Users/megwelch/sei/projects/project-3/WDSTF-Project3-API/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12) {
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: null },
  [Symbol(errorLabels)]: Set(0) {}

**Comment by kestler01** [comment]
```
MongoServerError: E11000 duplicate key error collection: express-auth-template-development.users index: email_1 dup key: { email: null }
```
_*dup key: { email: null }*_
there is no email key in your credentials pojo from your request, so it's interpreting it as null - turns out null is already an email value in the DB
```
body {"credentials":{"username":"k@k.com","password":"k","password_confirmation":"k"}}
```
without me looking at your model: I'm guessing you all have the email set to unique. Make sure that if a field is unique, it is also required ( it should also be non-nullable by default if required so shouldn't have to worry about that) 

if the issue persists after changing your request and or adjusting the model lmk
