### ISSUE TITLE
Checkbox bug

### ISSUE THREAD

**Issue by emilybernard1** [sei-ec-remote/team-project-issues#103]
**Describe the bug**
_A clear and concise description of what the bug is._
When creating a pet profile, the user current has to keep the checked box checked, otherwise they get an error. However, if the user then edits that pet, they can leave the box blank and everything works fine. 

**What is the problem you are trying to solve?**
I want the user to be able to uncheck the box when first creating their pet's profile

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expect the show page for the pet to show up whether or not the checkbox is checked.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
I get a 422 error if I leave the check box unchecked

**Post any code you think might be relevant (one fenced block per file)**
```
 const { pet, handleChange, heading, handleSubmit } = props

<Form.Check 
                    label="Are You Able to Meet-up?"
                    name="available"
                    defaultChecked={ pet.available }
                    onChange={ handleChange }
                />
                <Button type="submit">Submit</Button>

```

**What is your best guess as to the source of the problem?**
I think it's either a pathing or routing problem. 

**What things have you already tried to solve the problem?**
I've compared our code to the react-auth-boilerplate that we did with Beth and Timm last week to see how the "adoptable" check box functioned and what the code was like. To my eyes now, our checkbox should work just like that one.

**Additional context**

**Paste a link to your repository here**
https://github.com/ebare012882/petMatch

**Comment by ejparnell** [comment]
@ebare012882 I think what is happening is that you might not be sending back the `available` as a key in your json object. When we do the `handleChange` it only runs and adds keys to our state object when we click it. So if we don't have it run then the `available` key will not be in that object and we will get a 422 error. Console.log the data you are sending back to the API before it's sent. Is it missing a key?

**Comment by ejparnell** [comment]
Also with 422 errors there will be more details on what errored in the server side console. What did it fail out on? Which part was it unable to process?

**Comment by emilybernard1** [comment]
I went to office hours and John helped me fix the problem.

**Comment by emilybernard1** [comment]
It almost works just right and at this point, I think it would be easier for me to show you what it does, if that's ok.

**Comment by scarletpuma** [comment]
Can you let us know some more details about what's happening now?

**Comment by emilybernard1** [comment]
Yeah! So if I create a new pet profile, and say that the pet is available for play dates by checking the box, then when I go to edit that pet to say it's not available, the checkbox comes up not checked. So to get it to say that that pet is NOT available anymore, you have to click the box, then uncheck it and then on the show page, it shows that the pet isn't available. But that's not user friendly. I'd like it to consistently make the check box persist one way or the other.

**Comment by emilybernard1** [comment]
I read this tutorial to make the checkbox into a reusable component and I thought I had it correct, but now I'm getting the error message that "Checkbox is not defined" even though it is. I'll copy and paste the code below: 
```
import React from "react";


const Checkbox = ({label, value, onChange}) => {
    const [checked, setChecked] = React.useState(false);

    const handleChange = () => {
        setChecked(!checked);
    }

    return (
        <div>
            <Checkbox
                label="Are You Able to Meet-up?"
                name="available"
                value={checked}
                onChange={handleChange}
            />
            <p>Is "availability" checked? {checked.toString()}</p>
        </div>
    )
}


export default CheckBox

```
