### ISSUE TITLE
Modal to show on card

### ISSUE THREAD

**Issue by nguyenpham207** [sei-ec-remote/team-project-issues#107]
**Describe the bug**
_A clear and concise description of what the bug is._

Can't get my modal's value to show up on a card.

**What is the problem you are trying to solve?**

Since I added the card everything just stopped working.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Checked my backend but not too sure if I did it correctly

**What is the actual behavior?**
_A clear and concise description of what actually happened._

I messed up my code something in react so my app is not fully working.
**Post any code you think might be relevant (one fenced block per file)**
```js
import React, { useState } from 'react'
import { Card, Button } from 'react-bootstrap'

const ShowMeet = (props) => {
    const { meet, pet, user } = props

    return (
        <>
            <Card>
                <Card.Header>{ pet.person }</Card.Header>
                <Card.Body>
                    <small>{ pet.when }</small><br/>
                    <small>
                        { pet.where}
                    </small>
                </Card.Body>
            </Card>
        </>
    )
}

export default ShowMeet
```

**What is your best guess as to the source of the problem?**

backend is not fully working for me

**What things have you already tried to solve the problem?**

following examples from the lecture.

**Additional context**

**Paste a link to your repository here**
https://github.com/skbarbee/petMatch
https://github.com/skbarbee/PetMatchBackEnd

**Comment by scarletpuma** [comment]
Have you spoken to your backend lead about this issue? They may have a better idea of what is going wrong!

**Comment by nguyenpham207** [comment]
I spoke to the backend lead and we don't think it's a backend problem.

**Comment by scarletpuma** [comment]
Can you push up your code so we can see the most up to date?

**Comment by nguyenpham207** [comment]
just pushed the code. right now i'm just not hitting the route.

**Comment by kestler01** [comment]
there is no backend connection here ( and from the current code there shouldn't be, this isn't MVC ) 
where are you using this component ?

**Comment by nguyenpham207** [comment]
Petshow.js not too sure why its not showing up

**Comment by kestler01** [comment]
i don't see you actually importing and using the component in petshow.js - would you point it out for me ?

**Comment by kestler01** [comment]
ah : you linked me sarahs repo, not your fork so i can't actually see any of your work Sean

**Comment by nguyenpham207** [comment]
https://github.com/nguyenpham207/petMatch/tree/test2

**Comment by kestler01** [comment]
ok, a few things here
first: FIX INDENTATION
second:
```js
let meetCards
    if (pet) {
        if (pet.meets.length > 0) { //<------ are we sure that this is valid - lets look at the api return of the petshow call 
            meetCards = pet.meets.map(meet => (
                <ShowMeet
                    key={meet._id}
                    meet={meet}
                    pet={pet}
                />
            ))    
    } 
} 
```

**Comment by kestler01** [comment]
also, we never use the key passed to the meet component - react wont like that and is probably telling you so with an error somehwere

**Comment by kestler01** [comment]
( definitely need to use the key )
