### ISSUE TITLE
Username not displaying

### ISSUE THREAD

**Issue by megwelch** [sei-ec-remote/team-project-issues#108]
**Describe the bug**
_A clear and concise description of what the bug is._
We are trying to display the review username. We are able to see it in the state in our dev tools, but when we try and display it in JSX it is breaking.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Username to display in review

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Nothign is showing up on page and we are getting this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'username')
    at ReviewShow (ReviewShow.js:45:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
```

**Post any code you think might be relevant (one fenced block per file)**
back-end:
```
router.get('/reviews/show/:id', (req, res, next) => {
	Review.findById(req.params.id)
        .populate("owner", "username")
		.then(handle404)
		.then((review) => res.status(200).json({ review: review}))
		.catch(next)
})
```
front-end:
```
<div className="rating-item">User: { review.owner.username }</div>
```

**What is your best guess as to the source of the problem?**
Honestly not sure (see below)

**What things have you already tried to solve the problem?**
console.loging everywhere (the username shows up in the console.log so we're very confused why it's not working

**Paste a link to your repository here**
https://github.com/OnePartHarmony/WDSTF-Project3-Client

**Comment by scarletpuma** [comment]
When you're getting back the username in the logs, are you calling it as "review.owner.username" in the console.log or something else?

**Comment by megwelch** [comment]
@scarletpuma 
console.log('USERNAME', review.owner.username)

**Comment by ejparnell** [comment]
@megwelch What I think is happening is that on component first mount we have not made a get request to get the review yet so our review state is just `review: {}`. There is no `owner` key at the start and since there is no `owner` key there is no `username` key hence the error. What we can do is called [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). Try `review.owner?.username` and see if that works.

**Comment by megwelch** [comment]
@ejparnell review.owner?.username worked, thank you!
