### ISSUE TITLE
Semantic UI SearchBar isnt pulling any data from Api

### ISSUE THREAD

**Issue by sheikdon** [sei-ec-remote/team-project-issues#109]
**Describe the bug**
_A clear and concise description of what the bug is._
we are having issues with our semantic ui search bar and we cant seem to find why it won't display even though it's using our reducer function. The bug is definitely the placements of my props on the code.
```
×
Error: 
Reducer
src/components/SearchBar/Search.js:31
  28 |       return { ...state, value: props.selection }
  29 | 
  30 |     default:
> 31 |       throw new Error()
  32 |   }
  33 | }
  34 | 
View compiled
▶ 3 stack frames were collapsed.
SearchBar
src/components/SearchBar/Search.js:41
  38 | const msgAlert = props.msgAlert
  39 | 
  40 | 
> 41 |   const [currentUser, dispatch] = React.useReducer(Reducer, initialState)
  42 |   const { loading, results, value } = currentUser
  43 | 
  44 |   useEffect(() => {

```

**What is the problem you are trying to solve?**
we are having issues with our semantic ui search bar and we cant display the api we want from the database we own. All I have going is the search bar itself working but theres no data if can grab. I feel like I'm putting in my props in the wrong places.

**Expected behavior**
_A clear and concise description of what you expected to happen._
What should happen is that we need the data from out database api to get fetched with our dispatch so the search can filter out whatever comes up.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
We have the search feature working and everything but it cant grab any data and bring an error function for the reducer and search part.

**Post any code you think might be relevant (one fenced block per file)**
```
×
Error: 
Reducer
src/components/SearchBar/Search.js:31
  28 |       return { ...state, value: props.selection }
  29 | 
  30 |     default:
> 31 |       throw new Error()
  32 |   }
  33 | }
  34 | 
View compiled
▶ 3 stack frames were collapsed.
SearchBar
src/components/SearchBar/Search.js:41
  38 | const msgAlert = props.msgAlert
  39 | 
  40 | 
> 41 |   const [currentUser, dispatch] = React.useReducer(Reducer, initialState)
  42 |   const { loading, results, value } = currentUser
  43 | 
  44 |   useEffect(() => {

```

**What is your best guess as to the source of the problem?**
it saying the reduce is wrong and the threw error. so i adjusted the reduce functions to it right spots. but its giving the same error after i type

**What things have you already tried to solve the problem?**
so i adjusted the reduce functions to it right spots. but its giving the same error after i type. I read the semantic ui doc props but cant seem to find the issue.

**Additional context**

**Paste a link to your repository here**
https://github.com/mrbaummath/honey-badgers-API
https://github.com/mrbaummath/honey-badgers-client

**Comment by scarletpuma** [comment]
I think you're making it a little more complicated than it needs to be! [Check out this example of it being used](https://codesandbox.io/s/3rxzrq0rxp), I would try to do something a little more like that and move away from using the reduce functions.

**Comment by sheikdon** [comment]
okay i see that it makes the result list a written out seed. I would just put my data from my api instead?

**Comment by scarletpuma** [comment]
Exactly!

**Comment by sheikdon** [comment]
i used my project filter to get it to work but thanks for the help!
