### ISSUE TITLE
showing comments below user profile

### ISSUE THREAD

**Issue by jlm8965** [sei-ec-remote/team-project-issues#112]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**

showing comments below user profile

**Expected behavior**
_A clear and concise description of what you expected to happen._

showing comments below user profile

**What is the actual behavior?**
_A clear and concise description of what actually happened._

nothing showing. 

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by ejparnell** [comment]
@jlm8965 I'm going to close this issue due to it missing a lot of the information that we would need in order to help you. Please reopen the issue but fully filled out. 😄
