### ISSUE TITLE
Ownership issues when creating and indexing

### ISSUE THREAD

**Issue by harrisimon** [sei-ec-remote/team-project-issues#114]
**Describe the bug**
_A clear and concise description of what the bug is._
After creating a new user and going to create a new database document the page and database are returning 401
The document creates just fine in the terminal but going to view it on the front end returns 401.
A user already created in postman is able to view those documents.

**What is the problem you are trying to solve?**
Trying to get documents to show up.

**Expected behavior**
_A clear and concise description of what you expected to happen._
A user should be able to sign up and view the index of all documents

**What is the actual behavior?**
_A clear and concise description of what actually happened._
It's returning a 401.

**Post any code you think might be relevant (one fenced block per file)**
```js

```
We haven't touched sign up / auth so it's confusing why it's happening.

**What is your best guess as to the source of the problem?**
Something in our users? I'm digging but am not sure

**What things have you already tried to solve the problem?**
We've tried to debug as a team but haven't gotten too far

**Additional context**

**Paste a link to your repository here**
https://github.com/infinitelyann/Trivia-Client

**Comment by timmshinbone** [comment]
I have a sneaking suspicion I know what's going on here, I'm on my way

**Comment by harrisimon** [comment]
Adjusted our index route which had requireToken to not require to view the game.
