### ISSUE TITLE
showing pet rating not showing

### ISSUE THREAD

**Issue by jlm8965** [sei-ec-remote/team-project-issues#115]
**Describe the bug**
_A clear and concise description of what the bug is._
 ShowRating not doing the do of showing the rating. 

**What is the problem you are trying to solve?**

show a card of the pet's rating below the profile. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

show a card of the pet's rating below the profile. 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

not showing at all. 

**Post any code you think might be relevant (one fenced block per file)**
```js

```

I commented out and fiddled with it for a while, but have either broken it, or card remains unshown. 

**What is your best guess as to the source of the problem?**
ShowRating and the RatingForm communicating. 

**What things have you already tried to solve the problem?**

fiddling and breaking the app. 

**Additional context**

**Paste a link to your repository here**
https://github.com/skbarbee/petMatch
https://github.com/skbarbee/PetMatchBackEnd

**Comment by kestler01** [comment]
it looks like the rating data isn't being stored in the state of the parent component from your rating component- you're not passing your data back up the component tree. 

add the pet rating to the parent components state and pass the set function down as props to allow us to pass back that rating data so we can display it

**Comment by kestler01** [comment]
any progress on this issue ?

**Comment by jlm8965** [comment]
I'm in PetShow (pet dating app where rating appears below pet profile) connecting things.

**Comment by kestler01** [comment]
nice, shouldn't be a huge refactor with the current architecture. lmk if you have any questions or need more guidance

**Comment by jlm8965** [comment]
hi. I broke PetShow.

**Comment by jlm8965** [comment]
John worked on it for an hour tonight and got the pet profiles to once again show w/ the rating data, but the rating info doesn't show. He was stumped. Can you stop by tomorrow and assist?

**Comment by kestler01** [comment]
hey Julie, lmk if you have any more questions about this issue or close it if it's squashed 😁
