### ISSUE TITLE
Passing State down for mapped components? Best practice issue

### ISSUE THREAD

**Issue by harrisimon** [sei-ec-remote/team-project-issues#119]
**Describe the bug**
_A clear and concise description of what the bug is._
Currently I have page with components being rendered as a map function. Inside of each of those components is an edit button to bring up a form. I'm having a hard time getting the data to populate on the form (it's coming through undefined). I have a feeling it has to do with a component being mapped but am not sure where to start / how to refactor the code.

**What is the problem you are trying to solve?**
Trying to figure out the best way to map info but also have data passed down to an edit form / modal

**Expected behavior**
_A clear and concise description of what you expected to happen._
Trying to get each form to populate with existing data so the 'question' can be edited.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Data is coming through undefined

**Post any code you think might be relevant (one fenced block per file)**
This block has 'ShowQuestion' component
```js
                    <Card.Body>
                        
                        {/* {allQuestions} */}
                        <ShowQuestion 
                            user={user}
                            game={game}
                            show={questionModalShow}
                            msgAlert={msgAlert}
                            triggerRefresh={() => setUpdated(prev=> !prev)}
                            handleClose = {() => setQuestionModalShow(false)}
                        />
                    </Card.Body>
```
'ShowQuestion' component has 'EditQuestionModal'
```js
 let allQuestions
    return (
        allQuestions = game.questions.map((question, index) => (
        <>
            <div key={question._id}>
                <h1 key={index}>Question {index+1}</h1>
                <h3 key={index + "question"}>
                    {question.question}
                </h3>
                {question.correctAnswer}
                {question.incorrectAnswers}
                {question.category}
                {question.difficulty}
                {question.type}
            <EditQuestionModal 
                user={user}
                show={editModalShow}
                handleClose={()=> setEditModalShow(false)}
                triggerRefresh={triggerRefresh}
                msgAlert={msgAlert}
                game={game}
                question={question}
            />
            </div>
        
            <Button
                className="m-2" 
                variant="warning"
                onClick={() => setEditModalShow(true)}  
            >
                Edit this Question
            </Button>
        </>
    )
        ))
```
Which has 
```js
const EditQuestionModal = (props) => {
    const {user,  handleClose, msgAlert, triggerRefresh, game , show} = props

    const [question, setQuestion] = useState(props.question)
    console.log("huh",question)
```
and the return
```js

        <Modal show={ show } onHide = { handleClose } user={user}>
                <Modal.Title className='m2'>Add a question to your quiz</Modal.Title>
            <Modal.Header/>
            
            <QuestionForm
                handleChange={handleChange}
                handleSubmit={handleSubmit}
                user={user}
                question={question}
            
            />
        </Modal>
```

**What is your best guess as to the source of the problem?**
Something with map but I'm not sure how to get around it

**What things have you already tried to solve the problem?**
A bit of googling and looking at examples. Asked some teammates to also take a look at it

**Additional context**

**Paste a link to your repository here**
https://github.com/harrisimon/Trivia-Client/tree/harrison

**Comment by harrisimon** [comment]
In progress
--------------
Adding on a GET request with passed down info and filtering for subdoc

**Comment by harrisimon** [comment]
@ejparnell I think I've encountered an issue with this solution. Because it is doing the GET request inside of the map, it's doing it as many times as there are elements.

**Comment by ejparnell** [comment]
@harrisimon I'm going to send you over [this](https://www.devcript.com/how-to-select-only-one-element-of-a-map-in-react/) article. What I'm thinking is if you remove the EditModal from the map function and you set up a handler like in the article that can give you back the index of what you clicked on you can select your answer.  So something like:

```js
// from the article
const [element, setElement] = useState()
const [isUpdateShown, setIsUpdateShown] = useState(false)

const handleClick = (id) => {
  setElement(id)
  setIsUpdateShown(true)
}

// inside the return
<EditModal 
   // all other props you need
   show={isUpdateShown}
   question={game[setElement]}
/>

```

Would have to make it work in your context but I'm thinking this might be the key

**Comment by harrisimon** [comment]
Ok! I'll take a look. Thank you!

**Comment by harrisimon** [comment]
@ejparnell So I'm successfully finding the element and passing it down from modal to form--my form however is sometimes reading it as undefined and sometimes reading it properly. It also is not setting the field but that might be because my form is (overly?) complicated

**Comment by harrisimon** [comment]
After discussing with Andrew we'll be doing a refactor to bring the modals outside of the map function.
