### ISSUE TITLE
Edit route and Delete route keeps showing error of "Cannot read properties of undefined (reading 'token')"

### ISSUE THREAD

**Issue by Chrislee1996** [sei-ec-remote/team-project-issues#12]
**Describe the bug**
_A clear and concise description of what the bug is._
Whenever a user is trying to delete or edit their own product, it renders an error page of "Cannot read properties of undefined (reading 'token')"

**What is the problem you are trying to solve?**
Having so a user can edit or delete their own product 

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected the user to be able to edit or delete their product whichever button is pressed.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
The page just renders an error message of "Cannot read properties of undefined (reading 'token')"

**Post any code you think might be relevant (one fenced block per file)**
```js
// PATCH -> Update function
export const updateProduct = (user, updatedProduct) => {
    return axios({
        url: `${apiUrl}/products/${updatedProduct.id}`,
        method: 'PATCH',
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { product: updatedProduct }
    })
}
```

```
// DELETE -> Remove function
export const removeProduct = (user, productId) => {
    console.log('user in delting product', user)
    return axios({
        url: `${apiUrl}/products/${productId}`,
        method: 'DELETE',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}
```

**What is your best guess as to the source of the problem?**
It is not reading the user of whoever is pressing the edit or delete button because of the console.log for when I press the delete button as it says username is "undefined". But the weird part is that my POST route is working and is reading the username whenever i post something. Here is my POST route code for reference. 

```
// POST -> Create function
export const createProduct = (user, newProduct) => {
    console.log('user in creating a product', user)
    return axios({
        url: `${apiUrl}/products`,
        method: 'POST',
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { product: newProduct }
    })
}
```

**What things have you already tried to solve the problem?**
At first, I thought we had too many API calls in our product but the product route is working so it can't be that. Then I noticed the user name is not being defined via the delete route for some reason even though it's being passed.

**Additional context**

Forgot to mention but this works perfectly fine via back-end in post-man

**Paste a link to your repository here**

**Comment by cory-yonomi** [comment]
Found the missing prop in App.js
