### ISSUE TITLE
Display User timestamp for User Profile

### ISSUE THREAD

**Issue by sheikdon** [sei-ec-remote/team-project-issues#121]
**Describe the bug**
_A clear and concise description of what the bug is._
The data requires a value in which will display the created date from the token signon.

**What is the problem you are trying to solve?**
the value portion for the form inside the return button.

**Expected behavior**
_A clear and concise description of what you expected to happen._
i expect that the time stamp will show so we can place it in the userpage as last seen.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
it send me straight to the user profile which no errors or bugs.

**Post any code you think might be relevant (one fenced block per file)**
```js
<Form.Input 
                      fluid
                      icon='lock'
                      iconPosition='left'
                      
                      name='createdDate'
                      value={createdDate}
                      type='timestamp'
                      class="form-control"
   const [createdDate, setCreatedDate] = useState('')
                  />
```

**What is your best guess as to the source of the problem?**
the timestamp from the backend isnt displaying properly to the frontend client page.

**What things have you already tried to solve the problem?**
I tried this react hook which uses local storage from axios but it didnt work at all. 

**Additional context**

**Paste a link to your repository here**
https://github.com/mrbaummath/honey-badgers-client

**Comment by kestler01** [comment]
interesting ! i think we may actually want to look at the type here. I found these docs that may help 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date *

**Comment by sheikdon** [comment]
i looked and the only way it will list the time as profile created, is if we include it on the signup form. I think that might be the solution!

**Comment by sheikdon** [comment]
okay i got it to work thanks!
