### ISSUE TITLE
Search bar will not map through the array and display the results

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/team-project-issues#123]
**Describe the bug**
_A clear and concise description of what the bug is._
The search bar is able to filter through the list of restaurants and shows the results in the console but the  function to map through the array and display the results is not working

**What is the problem you are trying to solve?**
I want the results of the search to show up on the page  

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected  the results to map through the array and display on the page

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Nothing... I type in the search bar and hit enter then I see the results of the filter in the console as an array of objects but on the webpage nothing is displaying

**Post any code you think might be relevant (one fenced block per file)**
```js
import React, { useState, useEffect} from "react"

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faXmark, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons'
import axios from "axios"
import {Input, Space, Button} from 'antd'

const {Search} = Input

const SearchBar = () => {
    const [data, setData] = useState([])
    const [filteredData, setFilteredData] = useState([])
    const [error, setError] = useState("")
    const [input, setInput] = useState("")
    const [newFilter, setNewFilter] = useState([])

    console.log('I hit here')
    useEffect(() => {
        axios.get('http://localhost:8000/restaurants')
        .then((response) => {
            console.log(response.data)
            setData(response.data)
            setFilteredData(response.data)
        })
        .catch((err) => {
            console.log(err)
            setError(err)
        })
    }, [])

    const onSearch = (searchInput) => {
        const newFilter = data.restaurants.filter((value) => {
            return  value.name.toLowerCase().includes(searchInput.toLowerCase())
            // (
            //     newFilter.map(newFilter => {
            //         <li key={newFilter.id}>
            //         {newFilter.name}
            //     </li>
            //     })
            // )
        })
        console.log('new filter', newFilter)
    }

    const handleFilter = (e) => {
        console.log('event',e)
        const searchInput = e.target.value
        setInput(searchInput)       
        const newFilter = data.filter((value) => {
            console.log('I tried to hit here')
            return  value.name.toLowerCase().includes(searchInput.toLowerCase())
        })
        if (searchInput === "") {
            setFilteredData([])
        } else {
            setFilteredData(newFilter)
        }
    }
    
    console.log('a little bit farther down')
    


return(
    <div className="search">
        <div className="searchInputs">
        <Search
            placeholder="Search for a Restaurant" 
            // value={input}
            onSearch={onSearch}       
            // enterButton ={handleFilter}
        />
        </div>
        <div className="containter-md">
            <ul>{newFilter.map((newFilter) => {
                return (
                    <div>
                    <li key={newFilter}>
                        {newFilter.name}
                    </li>
                    </div>
                )
                })}
            </ul>
        </div>

```

**What is your best guess as to the source of the problem?**
I am sure its something silly and I have just gone code blind from staring at it for too long.  I think it might be that the return needs to be in a card  like the reviews and not in a div

**What things have you already tried to solve the problem?**
I have googled a ton and  my format for the mapping function is the same as the ones I googled. I have tried mapping over the objects in the array. I went to TA hours last night,  I have read sooo much documentation. 

**Additional context**
I think I'm just code blind at this point and am missing something silly like an extra div 

**Paste a link to your repository here**[
](https://github.com/melsil11/Client-theGoodAvocado)

**Comment by timmshinbone** [comment]
we discussed sending the `setAllRestaurants` function from the main index page down to the search bar component so it will update those restas and re-render the index with only the filtered results

**Comment by kestler01** [comment]
how are we doing with this issue ?

**Comment by melsil11** [comment]
We are close,  Angel and Sam are taking a look with some fresh eyes and think they might have it figured out.  We will keep you updated and close the issue if we figure it out.

**Comment by melsil11** [comment]
we got it to work by changing it to render to a new page
