### ISSUE TITLE
how to resolve conflicting pull request

### ISSUE THREAD

**Issue by AlexMcBex** [sei-ec-remote/team-project-issues#129]
**Describe the bug**
_A clear and concise description of what the bug is._
We are not sure how to resolve a conflicting pull request without messing the git flow up...

**What is the problem you are trying to solve?**
We have a pull request with a file that has been modified at the same time as another pull request. We are looking for the best way to resolve the conflict .

**Expected behavior**
_A clear and concise description of what you expected to happen._
resolve the conflict, try to commit only certain files and ignore others

**What is the actual behavior?**
_A clear and concise description of what actually happened._

the pull request seems to can not ignore some files and pull others...

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/AlexMcBex/Project3-client/pull/4#pullrequestreview-1296475069

**Comment by timmshinbone** [comment]
will join your room to help
