### ISSUE TITLE
Cloudinary questions, how to use it? Also getting an error on our API call which is limiting results to one.

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/team-project-issues#130]
**Describe the bug**
_A clear and concise description of what the bug is._
Cloudinary, just wondering how to use this. we do plan on bringing in alot of images from an API

api bug. getting back a couple results but then we get an error. the error is "cannot set headers after already sent to client" and i remember dealing with these but not sure how to fix it. already using one .then and and two awaits. not sure how to get the code to go one by one

**What is the problem you are trying to solve?**
give json on multiple objects

**Expected behavior**
_A clear and concise description of what you expected to happen._
the code to loop over an array of url's and hit each one with an api call to GET data, json data 

**What is the actual behavior?**
_A clear and concise description of what actually happened._
it gets one, renders one object, then stops with an error , cannot set headers

**Post any code you think might be relevant (one fenced block per file)**
```js
// INDEX
// GET /examples
router.get('/artworks', async (req, res, next) => {
	Artwork.find({})
		.then(async artworks => {
            
            const artworkInfo = await axios(`${process.env.MET_URL}`)

            const artworkIdNum = artworkInfo.data.objectIDs.slice(43152,43159)

            
            for (let i = 0; i < artworkIdNum.length; i++) {
                const artworkURL = process.env.MET_URL + `/${artworkIdNum[i]}`
                console.log(artworkURL)
                const paintingInfo =  await axios(`${artworkURL}`)
                    console.log('title' , paintingInfo)
                res.json({ 
                    title: paintingInfo.data.title, 
                    date : paintingInfo.data.objectDate, 
                    artist: paintingInfo.data.artistDisplayName, 
                    dimensions : paintingInfo.data.dimensions, 
                    medium : paintingInfo.data.medium, 
                    img : paintingInfo.data.primaryImageSmall, 
                    department : paintingInfo.data.department 
                })
            }
		})
		.catch(next)
})

```

**What is your best guess as to the source of the problem?**
dont think i'm using async and await correctly with how this API is setup, which is like a 2 step api instead of one. step one gives back an object number, step 2 gives back the actual object associated.

**What things have you already tried to solve the problem?**
tried map instead of for loop. googled it, found a repository for the met api but no help . tried another .then but that had an error.

**Additional context**

**Paste a link to your repository here**
https://github.com/caitreid/projectThreeBackend

**Comment by timmshinbone** [comment]
I'd recommend making the call to your third party API from your front end client, if you're not saving data to the backend and you're just displaying that data to your users, no need to make the call from the back end. After you've got the data displaying on the client you can determine how to save parts of that data as the 'Artworks' that your users create

**Comment by asands94** [comment]
Also, make sure not to call the `res.json` inside the for loop!

**Comment by tthephas** [comment]
ok we can do it on the front end only and seed the back. but we still will run into the same problem we are now, which is not being able to get many results without hitting an error. we still need help there. also understanding cloudinary as well. ashley we have the json outside of the for loop in our latest code and it is still not working.

**Comment by asands94** [comment]
Are you getting the same error now that you are calling the API on the front end?

**Comment by timmshinbone** [comment]
Share the updated API request

**Comment by tthephas** [comment]
```js

  Artwork.find()
        .then(async artwork => {
            const artworkImages = await axios(`${process.env.MET_IMAGE_URL}`)
            console.log('this is the data.objectIDs array: ',artworkImages.data.objectIDs)
            const slicedArr = artworkImages.data.objectIDs.slice(1, 9)
            console.log('this is slicedArr: \n', slicedArr)
            
			slicedArr.map(async objectID => {
                console.log('this is objectID in slicedArr', objectID)
                let artworkObjId = null
				try {
					const artworkObjId = await axios(`${process.env.MET_OBJECTID_URL}/${objectID}`)
					
				} catch (err) {
					console.error(err)

				} finally {
					// artworkObject = {
					// 	"title": artworkObjId.data.title,
					// 	"artist": artworkObjId.data.artistDisplayName,
					// 	"department": artworkObjId.data.department,
					// 	"medium": artworkObjId.data.medium,
					// 	"img": artworkObjId.data.primaryImage
					// }
					console.log('the artwork! \n', artworkObjId)
				}
                //console.log('the artwork! \n', artwork)
            })
			
		})
		// respond with status 200 and JSON of the examples
		.then((artwork) => res.status(200).json({ artwork: artwork }))
		// if an error occurs, pass it to the handler
		.catch(next)
})

```

**Comment by timmshinbone** [comment]
We re-thought the course of action for completing this task.
