### ISSUE TITLE
App3 - Duplicate followers

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/team-project-issues#134]
**Describe the bug**
_A clear and concise description of what the bug is._
Pushing a new userId into the follower's array allows for duplication of the same id into the followers array

**What is the problem you are trying to solve?**
We want to have unique userid's in the array, so users are unable to follow the same account twice. 

**Expected behavior**
_A clear and concise description of what you expected to happen._
We can push new users into a followers array but only once per user.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
The same user id can add into a user array multiple times

**Post any code you think might be relevant (one fenced block per file)**
```js
 FollowCart.findOne({ owner: userid })
        .then((fcart) => {
            if (fcart) {
                console.log(`======= FIRST CONSOLE=====`)
                console.log(`this is followCart`, fcart)
        
                fcart.followers.push(anUserId)
                // console.log(fcart.followers.push(anUserId))
                return fcart.save()

                
                // res.json(fcart)
            } else {
                FollowCart.create({
                    owner: userid,
                    followers: [],
                    followings: []
                }).then((fcart) => {
                    console.log(`======= SECOND CONSOLE=====`);
                    console.log(`this is followCart`, fcart)
                    fcart.followers.push(anUserId)
                    return fcart.save()
                    // res.json(fcart);
                });
            }
        })
```

**What is your best guess as to the source of the problem?**

not sure

**What things have you already tried to solve the problem?**

we don't know where to start,

**Additional context**

none

**Paste a link to your repository here**
https://github.com/bruceabrigo/App3-API/tree/followCart

**Comment by timmshinbone** [comment]
When you pull in the user, first run a check to see if the id is already in the array, if it is, send some message that they're already following, if not, then allow the push. Alternatively, you could leave this for now, and only conditionally render the "follow" button based on that same data. If the logged in user's id is already in the array, then an inactive button that says 'following' should appear, but if the id is NOT in the followers array, the normal 'follow' button should show up.

**Comment by bruceabrigo** [comment]
We'll leave this for now, we think adding followers to an array is a big win.
