### ISSUE TITLE
Error when trying to display subdocuments

### ISSUE THREAD

**Issue by EricCSheppard** [sei-ec-remote/team-project-issues#136]
**Describe the bug**
_A clear and concise description of what the bug is._

Getting an error when trying to display the comments subdoc

**What is the problem you are trying to solve?**

trying to get our comments to display on our show page for an individual document

**Expected behavior**
_A clear and concise description of what you expected to happen._

Expecting to map over the array of comments on our document, and have them display below

**What is the actual behavior?**
_A clear and concise description of what actually happened._

An error is returned in the console.

**Post any code you think might be relevant (one fenced block per file)**

The comment map:
```js
    let commentCards
    if (goal) {
        if (goal.comments.length > 0) {
            commentCards = goal.comments.map(comment => (
                
                <ShowComment
                    key={comment.id}
                    comments={comment}
                    user={user}
                    goal={goal}
                    msgAlert={msgAlert}
                    triggerRefresh={() => setUpdated(prev => !prev)}
                />
                
            ))
        }
    }

```

The ShowComment component:
```js
import { Card, Button } from 'react-bootstrap'
import { useState } from 'react'

const ShowComment = (props) => {
    const { comment, user, goal, msgAlert, triggerRefresh } = props

    return (
        <>
            <Card>
                <Card.Header></Card.Header>
                <Card.Body>
                    {comment.note}
                </Card.Body>
                <Card.Footer>
                </Card.Footer>
            </Card>
        </>
    )
}

export default ShowComment
```

**What is your best guess as to the source of the problem?**

The error says there is something wrong with the casing of the react component

**What things have you already tried to solve the problem?**

I tried console logging the "commentCard" and this was returned:

![Screen Shot 2023-02-15 at 12 00 19 PM](https://user-images.githubusercontent.com/109560435/219099605-79a4c62f-cec7-45a5-8490-558bdfbe4636.png)

**Additional context**

![Error](https://user-images.githubusercontent.com/109560435/219099350-3de602d5-d866-4f66-a87b-c5f49d17d546.png)

**Paste a link to your repository here**

https://github.com/EricCSheppard/Project3-client/tree/eric

**Comment by timmshinbone** [comment]
The prop for comment on the ShowComment component is `comments` but you're referring to it inside the component as `comment`, change the prop name to the singular `comment`

**Comment by EricCSheppard** [comment]
Oops, that was a typo leftover from when I was changing things around, the error still exists when it's comment.

**Comment by EricCSheppard** [comment]
heading for lunch now so might be slow to reply if you get back.

**Comment by timmshinbone** [comment]
Weird, I'll take a look after lunch

**Comment by EricCSheppard** [comment]
Solved!

**Comment by timmshinbone** [comment]
Renamed component + Github weirdness was causing this issue. Making a new component with the same exact parts fixed the prob
