### ISSUE TITLE
Unable to retrieve axios data

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/team-project-issues#137]
**Describe the bug**
_A clear and concise description of what the bug is._

state is returning as undefined after setState in useEffect

**What is the problem you are trying to solve?**

I need to return content data from the get axios call

**Expected behavior**
_A clear and concise description of what you expected to happen._

I expected the object to be returned to my console, and map to a card.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

The console shows null and its set state, however, is returns an undefined to the console.

**Post any code you think might be relevant (one fenced block per file)**
```js
    useEffect(() => {
        getAllContent()
            .then(res => setContent(res.data.content))
            .catch(err => {
                msgAlert({
                    heading: 'Error with content',
                    message: 'Trouble receiving content data',
                    variant: 'danger'
                })
                setError(true)
            })
    }, [])
```

**What is your best guess as to the source of the problem?**
my `useEffect` hook may be the source, or a bad axios call.

**What things have you already tried to solve the problem?**

I tried changing content to contents, however the screen goes blank.

**Additional context**

**Paste a link to your repository here**
https://github.com/bruceabrigo/App3-Client

**Comment by timmshinbone** [comment]
Do you have a means of handling what happens if there is no 'content' data? Remember that the component loads FIRST then calls useEffect, so initially there is no data, if you're not handling that, then your component will be broken at the outset

**Comment by bruceabrigo** [comment]
This is what I have to handle for no content: 
```js
    if (error) {
        return <p>Error!</p>
    }

    if(!content) {
        return <p>Unable to load content</p>
    } else if(content.length === 0) {
        return <p>Create post or follow new users!</p>
    }
```

**Comment by bruceabrigo** [comment]
On my index page, the container that would hold the content returns the `if(!content)`

**Comment by bruceabrigo** [comment]
I'm now able to return the content data to the console. My bug no is only in the map. It looks like I  just need to refactor my map function in order to get the content I need. I'll keep the issue queue updated.

**Comment by timmshinbone** [comment]
Let me see the map and I'll guide ya!

**Comment by bruceabrigo** [comment]
5 seconds too late! I got it working

**Comment by bruceabrigo** [comment]
Was just a typo: contnet instead of content
