### ISSUE TITLE
Issues with comments and favorites routes

### ISSUE THREAD

**Issue by KenGibb** [sei-ec-remote/team-project-issues#142]
**Describe the bug**
_A clear and concise description of what the bug is._
We keep getting an error that says "TypeError: Cannot set properties of undefined" while trying to set the properties of our owner. We took a few steps but couldn't resolve it.

**What is the problem you are trying to solve?**
We can't get our favorite module or comment module to render.

**Expected behavior**
_A clear and concise description of what you expected to happen._
We expect our comments to show on the show page of our games and on our "show favorites" page.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
We keep getting an error inn the terminal every time we try to run our code and our show comments page renders with a white screen.

**Post any code you think might be relevant (one fenced block per file)**
## Comments
```js
router.post('/comments/:gameId', requireToken, (req, res, next) => {
    const gameId = req.params.gameId
    const userId = req.user._id
    const { note } = req.body
    console.log('this is the userId', userId)
    console.log('this is req.boy', req.body)
    Game.findById(gameId)
        .then(handle404)
        .then(game => { 
            const newComment = {
            author: userId,
            note: note
            }
            console.log('this is newComment', newComment)
            game.comments.push(newComment)
            return game.save()
        })
        .then(game => {
            res.redirect(`/comments/${game.id}`)
        })
        .catch(next)
})
```
## Favorites
``` js
router.get(`/favorites`, (req, res, next) => {
    Game.find({})
        .populate({
            path: 'favorites',
            populate: {
                path: 'owner',
                select: 'username'
            }
        })
        .then(games => {
            const favorites = games.reduce(
                (acc, game) => {
                    game.favorites.forEach(favorite => {
                        acc.push(favorite)
                    })
                    return acc
                },
                []
            )
            console.log(favorites)
            return res.status(200).json(favorites)
        })
        .catch(next)
})

// POST
router.post('/favorites/:gameId', requireToken, (req, res, next) => {
    const userId = req.user._id
    const gameId = req.params.gameId
    Game.findById(gameId)
        .then(handle404)
        .then(game => {
            const newFavorite = {
                game: game,
                owner: userId,
            }
            console.log(newFavorite)
            game.favorites.push(newFavorite)
            console.log(game)
            return game.save()
        })
        .then(() => res.sendStatus(204))
        .catch(next)
})
```

**What is your best guess as to the source of the problem?**
I don't know what may be the source other than in the backend we have a problem with the author and owner being undefined somewhere.

**What things have you already tried to solve the problem?**
We tried to change our owners and arthors but still was unsuccessful.

**Additional context**
We keep getting a 404 not found after trying our code in  PostMan.

**Paste a link to your repository here**
![Error](https://user-images.githubusercontent.com/85146023/219260590-d2755b73-8b18-4cce-8ef0-09d5761716f8.png)
https://github.com/ShadowXG/team-project-1-backend
https://github.com/ShadowXG/team-project-1-frontend

**Comment by asands94** [comment]
For your code in comments, refer to the pets api toy post route. It looks like you are adding extra things in your code such as the `newComment` object. You already have a variable called `note` that it looks like you were trying to use to access the comment information.

**Comment by KenGibb** [comment]
We referenced our backend to the toy routes and it's still not working as intended; we are getting an error but it's different.


![Error 2](https://user-images.githubusercontent.com/85146023/219404715-ad55b3dd-e733-4111-b046-93e7cfce1b04.png)
![Error 3](https://user-images.githubusercontent.com/85146023/219405350-81ea2a2e-d8f4-4e02-85ea-f4ad3d73f183.png)
![Error 4](https://user-images.githubusercontent.com/85146023/219405390-b3d40500-7bab-48bd-be7c-64a5c24a20a4.png)

**Comment by asands94** [comment]
If you use `requireToken` you should also `requireOwnership` also your route says `petId` and not `gameId` so the params isn't working

**Comment by KenGibb** [comment]
We are getting an error that's still saying "Error: Game validation failed: comments.0.author: Path `author` is required."  

![Screen Shot 2023-02-16 at 10 36 19 AM](https://user-images.githubusercontent.com/85146023/219429519-2648e532-10bf-4966-bf95-aceec3d771c1.png)

**Comment by asands94** [comment]
You need to add in `req.body.game.owner = req.user.id`

**Comment by KenGibb** [comment]
It's still not working for us after we added req.body.game.owner = req.user.id.

![Screen Shot 2023-02-16 at 12 12 33 PM](https://user-images.githubusercontent.com/85146023/219452101-c16a4da8-100d-4271-adbf-9f9cd66a8fdd.png)
