### ISSUE TITLE
Getting seeded Backend API data to render on the frontend

### ISSUE THREAD

**Issue by caitreid** [sei-ec-remote/team-project-issues#144]
**Describe the bug**
_A clear and concise description of what the bug is._

Everyone on my team is able to see seeded data when calling it on the frontend, but I'm unable to do so. 

I have seeded the data a few times, and I've looked in mongosh. The data is definitely there. And the error I'm getting is that the list of items in the collection is zero, which makes me think that it can successfully hit the db, but its perhaps getting the wrong info back?

**What is the problem you are trying to solve?**

Identify why my set up is out of sync with my team's

**Expected behavior**
_A clear and concise description of what you expected to happen._

I expect to see the data on the frontend

**What is the actual behavior?**
_A clear and concise description of what actually happened._

hitting this part of the code ... but it shouldn't be 'true'
```js
 else if (departments.length === 0) {
    // otherwise if there ARE no pets, display that message
    return <p>No departments yet, go add some!</p>
  }

```

**Post any code you think might be relevant (one fenced block per file)**
```js
import React, { useState, useEffect } from 'react';
// import axios from 'axios';
import { getAllDepartments } from '../../api/departments'
import Card from 'react-bootstrap/Card'

const IndexDepartment = (props) => {
  // State to store the departments data
  const [departments, setDepartments] = useState(null);
  console.log('this is departments', departments)
  console.log('this is props', props)


  //Use effect to fetch the departments data from the API
  useEffect(() => {
    getAllDepartments() 
      .then(res => setDepartments(res.data.departments))
      .catch(err => console.log(err))
  }, []); // Second argument of an empty array means this useEffect will only run once on component mount
  console.log('this is department', departments)

  if (!departments) {
    // if no pets loaded yet, display 'loading'
    return <p>Loading...</p>
  } else if (departments.length === 0) {
    // otherwise if there ARE no pets, display that message
    return <p>No departments yet, go add some!</p>
  }
  // cards aren't rendering
  const departmentCards = departments.map(department => (
    <Card key={department.id} style={{ backgroundImage: `url(${department.img})`, width: "250px" }}>
      <Card.Header>
        {department.name}
      </Card.Header>
    </Card>
  ))


  return (
    <div>
      <div>
        <h1>View Artworks</h1>
        <p>Search by Department</p>
      </div>
      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "1rem",
        height: "100vh",
        overflow: "scroll"
      }}>
        {departmentCards}
      </div>
    </div>
  )
};


export default IndexDepartment;

```

**What is your best guess as to the source of the problem?**
Maybe there's something wrong with my operating system?... I'm at a loss as to why my three teammates can see it fine, but I can't

**What things have you already tried to solve the problem?**

- Restarted my computer to make sure there were no other processes running on other ports
- pulled main on frontend and backend
- Restarted both development servers 
- Opened mongosh to double check that data is present in db
- re-seeded db

**Additional context**

It's not working for either the seeded departments or exhibitions
(ProjectThreeBackend > src/models/departmentSeed.js)
(ProjectThreeBackend > src/models/seed.js)

**Paste a link to your repository here**
https://github.com/caitreid/projectThreeFrontend
https://github.com/caitreid/projectThreeBackend

**Comment by asands94** [comment]
When you do a console log for departments do you ever get any data back?
