### ISSUE TITLE
need help setting up cloudinary API

### ISSUE THREAD

**Issue by huy-tran49** [sei-ec-remote/team-project-issues#149]
**Describe the bug**
_A clear and concise description of what the bug is._

need help setting up cloudinary API

**What is the problem you are trying to solve?**

cloudinary does not work, i'm not able to call any build in function from cloudinary

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

when I call the cloudinary function (window.cloudinary) and console log it it return "undefine"

**Post any code you think might be relevant (one fenced block per file)**
```js
const UploadWidget = () => {
    const cloudinaryRef = useRef()
    const widgetRef = useRef()
    useEffect(()=> {
        cloudinaryRef.current = window.cloudinary
        console.log(window)
        console.log(cloudinary)
        widgetRef.current = cloudinaryRef.current.createUploadWidget({
            cloudName: 'dcsbdscrq',
            uploadPreset: 'k83dfv5v'
        }, function(error, result) {
            console.log(result)
        })
    }, [])
    return (
        <button onClick={()=> {widgetRef.current.open()}}>
            Upload
        </button>
    )
}
```

**What is your best guess as to the source of the problem?**

window.cloudinary is undefine because cloudinary is not set up correctly

**What things have you already tried to solve the problem?**

installed the cloudinary npm package and importing the cloudinary package

**Additional context**

**Paste a link to your repository here**
https://github.com/huy-tran49/FrontEndProject3

**Comment by timmshinbone** [comment]
Where did you get the `window.cloudinary`, I'm pretty sure that reference should be to the cloudinary package you've installed.

**Comment by huy-tran49** [comment]
I was able to make the API call in Postman but now I'm having trouble passing the data into the request body on the frontend in my code.

This is the request from Postman

![image](https://user-images.githubusercontent.com/23158353/219722679-db83fae5-aae2-4ac5-a20b-0b9ffdddb6f7.png)

What I currently have for my code
```js
const data = new FormData();
data.append('file', 'public/logo192.png');
data.append('upload_preset', 'k83dfv5v');
data.append('api_key', '239673437135639');
console.log(data.getHeaders)
export const UploadImage = {
    method: 'post',
    maxBodyLength: Infinity,
    url: 'https://api.cloudinary.com/v1_1/dcsbdscrq/image/upload',
    headers: { 
        ...data.getHeaders()
    },
    data : data
};

axios(UploadImage)
    .then(function (response) {
        console.log(JSON.stringify(response.data));
    })
    .catch(function (error) {
        console.log(error);
    });


```

**Comment by timmshinbone** [comment]
Ok, what does the form look like, and what are the error messages you're receiving?

**Comment by huy-tran49** [comment]
Its giving me an error saying that getHeaders() is not a function. I did some googling and I found that form-data method getHeaders() can only be use on Node js. Is there a way to include the header in my axios call in React?

**Comment by huy-tran49** [comment]
I think to clarify, I want to make an API call like the one I did in the postman request that would include the form-data in the body.

**Comment by timmshinbone** [comment]
Check out the axios functions we built into the boilerplate for the user's auth functionality for an example of how to send headers in these requests. You can apply any headers you want to the request that way, by having them as key:value pairs in the headers object. For sending form data as part of the request, that functionality should already be handled by the form and is easy to investigate by using console logs inside the api function as well as the back end routes.
