### ISSUE TITLE
code not updating

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/team-project-issues#15]
**Describe the bug**
_A clear and concise description of what the bug is._

So I was able to resolve my issue, but I don't think the way I resolved it would be ideal. So after the merge I usually do a pull to get the updated code. When I did a pull just earlier the terminal would tell me that my code was up to date, however the changes weren't getting pulled from the most recent merge I did.

**What is the problem you are trying to solve?**

Problem was resolved, but I would like to learn how to properly resolve it if it happens again.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Usually right after a merge I will `pull origin main` and then the code will get updated to the current code, but earlier it kept giving me the outdated code.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

I kept getting the old code pre merge.

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

I have no idea, and would like to know what I did to cause my code not to update

**What things have you already tried to solve the problem?**

I tried redoing the pull, double checking the pull request on github, double checking with group mates if the pull went through on their end, etc.

**Additional context**

n/a

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-client

**Comment by cory-yonomi** [comment]
Sometimes GitHub can take a minute or two to fully update and provide the intended code when you're pulling. Also want to make sure you're pulling the right branches or are on the right branch that you want to update

**Comment by ivycle94** [comment]
That's really weird because I think i was trying to pull maybe 5-7 mins after the merge, and I did the pull the same way I've been doing for the past couple days. Do you think it could have been a bug? I never had this issue until earlier.

**Comment by tkolsrud** [comment]
Just to clarify, you're pushing to your fork, and then pulling from that same fork? or you're pushing to your fork and then pulling from the main repo

**Comment by ivycle94** [comment]
So because I'm GM, on a separate branch I will push to that same branch. once I merge i just go back to my main branch and then pull to update my code.

**Comment by DoireannJane** [comment]
Are you still having this issue? I can pop in in a second

**Comment by ivycle94** [comment]
No i resolved it yesterday by just copy and pasting the code, I was just mainly curious as to why it happened and how I should fix it properly next time it happens! Thanks Doire :)!

**Comment by ivycle94** [comment]
I will just close this issues and will open it back up if I encounter it again.
