### ISSUE TITLE
Unable to receive SHOW

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/team-project-issues#152]
**Describe the bug**
_A clear and concise description of what the bug is._

Receiving issue where null state is being read set state

**What is the problem you are trying to solve?**

I need to show the content of one content id

**Expected behavior**
_A clear and concise description of what you expected to happen._

When rediricted to show page, I need to see a card of the content in content id

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Show page loaded and crashed, console output cannot read null state

**Post any code you think might be relevant (one fenced block per file)**
```js
    useEffect(() => {
        showContent(id)
            .then(res => setContent(res.data.content))
            .catch(err => {
                msgAlert({
                    heading: 'Error editing post',
                    message: messages.editPostFailure,
                    variant: 'danger'
                })
            })
    }, [edited])

    if (!content) {
        <LoadingScreen />
    }

        <>
            <Container className="mt-5">
                <Card>
                    <Card.Header>Content</Card.Header>
                        <Card.Body>
                            <h2>{content.material}</h2>
                        </Card.Body>
                </Card>
            </Container>
        </>
```

**What is your best guess as to the source of the problem?**

perhaps the if (!content) is not receiving any content even at null?

**What things have you already tried to solve the problem?**

tried reading just content and not content id - received error stating objects are not a valid react child

**Additional context**

**Paste a link to your repository here**
https://github.com/bruceabrigo/App3-Client/tree/Bruce-Client-D3

**Comment by timmshinbone** [comment]
try adding `return` before the `<LoadingScreen/>` in your if statement

**Comment by bruceabrigo** [comment]
That worked! Ashley had me try this as well:
```react
content?.material
```
I'll stick with the return in my conditional.
