### ISSUE TITLE
Unable to updated 

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/team-project-issues#153]
**Describe the bug**
_A clear and concise description of what the bug is._

Content not updating on api

**What is the problem you are trying to solve?**

Updated content should updated content material

**Expected behavior**
_A clear and concise description of what you expected to happen._

After inputting new material to edit content form, edit material should patch it's previous value

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Received a success message, however no updated actually occured

**Post any code you think might be relevant (one fenced block per file)**
In Show
```js
useEffect(() => {
        showContent(id)
        .then(res => setContent(res.data.content))
        .catch(err => {
            msgAlert({
                heading: 'Error editing post',
                message: messages.editPostFailure,
                variant: 'danger'
            })
        })
    }, [edited])

```
In Modal
```js
    const onSubmit = (e) => {
        e.preventDefault()

        editPost(user, content)
            .then(() => handleClose())
            .then(() => {
                msgAlert({
                    heading: 'Post saved!',
                    message: messages.editPostSuccess,
                    variant: 'success'
                })
            })
            .then(() => triggerRefresh())
            .catch(() => {
                msgAlert({
                    heading: 'Error with edit',
                    message: messages.editPostFailure,
                    variant: 'danger'
                })
            })
    }
```

**What is your best guess as to the source of the problem?**

At first I assumed an incorrect axios call, however after changes the url an error occured. PATCH url works in postman. My best bet is an error in the useEffect

**What things have you already tried to solve the problem?**

Changed the axios url 

**Additional context**

**Paste a link to your repository here**
https://github.com/bruceabrigo/App3-Client/tree/Bruce-Client-D3

**Comment by asands94** [comment]
When you refresh the page is the content updated?

**Comment by bruceabrigo** [comment]
Nothing updates even after the refresh
