### ISSUE TITLE
trouble setting up an index-mine route

### ISSUE THREAD

**Issue by mqpiffle** [sei-ec-remote/team-project-issues#154]
**Describe the bug**
_A clear and concise description of what the bug is._
getting a not able to read properties of id error, something is not right with how i set up the  route on the back end

**What is the problem you are trying to solve?**
i want an index page for a specific curator of the galleries they've created

**Expected behavior**
_A clear and concise description of what you expected to happen._
set up a route that will return only the curator's galleries

**What is the actual behavior?**
_A clear and concise description of what actually happened._
error in postman (500)

**Post any code you think might be relevant (one fenced block per file)**
```js
// INDEX -- MINE
// GET /galleries-mine/:id

router.get('/galleries-mine/:userId', requireToken, (req, res, next) => {
    if (req.user.isCurator) {
        Gallery.find()
            .populate('owner')
            .then(galleries => {
                galleries.map(gallery => {
                    if (gallery.owner.id === req.user.id) {
                        return gallery.toObject()
                    }
                })
            })
            // respond with status 200 and JSON for galleries
            .then(galleries => res.status(200).json({ galleries: galleries }))
            // if an error occurs, pass it to the handler
            .catch(next)
    } else {
        throw new notAllowed()
    }
})
```

**What is your best guess as to the source of the problem?**
not using the params/user.id correctly

**What things have you already tried to solve the problem?**
i initially tired ```requireOwnership()``` both inside and outside of the ```.map()``` function

**Additional context**

**Paste a link to your repository here**
https://github.com/mqpiffle/Project-3-backend

**Comment by mqpiffle** [comment]
Here is a screenshot of postman and terminal for reference
![image](https://user-images.githubusercontent.com/69863751/219780460-eff32afa-2570-4a79-9c64-dfa5f76bd168.png)

**Comment by asands94** [comment]
To be clear, you only want the logged in users information to show? If so then you would need to add the id inside of the `Gallery.find({owner: req.user.id})` <-- something like this

**Comment by asands94** [comment]
You also would not need to have an ID as a param in that get route. This is a similar concept to last unit when we created the `/mine` route

**Comment by mqpiffle** [comment]
yes! thank you!  now i'm not erroring, but it's not returning the gallery i have set up with the logged in user
![image](https://user-images.githubusercontent.com/69863751/219783813-818a7773-e001-4df9-aed0-e04444ba2ef3.png)

**Comment by mqpiffle** [comment]
```js
router.get('/galleries-mine', requireToken, (req, res, next) => {
    if (req.user.isCurator) {
        Gallery.find({ owner: req.user.id })
            .populate('owner')
            .then(galleries => {
                galleries.map(gallery => {
                    return gallery.toObject()
                })
            })
            // respond with status 200 and JSON for galleries
            .then(galleries => res.status(200).json({ galleries: galleries }))
            // if an error occurs, pass it to the handler
            .catch(next)
    } else {
        throw new notAllowed()
    }
})
```

**Comment by timmshinbone** [comment]
Can you share here how you were attempting to use requireOwnership?

**Comment by mqpiffle** [comment]
```js
// INDEX -- MINE
// GET /galleries-mine/:id

router.get('/galleries-mine', requireToken, (req, res, next) => {
    if (req.user.isCurator) {
        Gallery.find({ owner: req.user.id })
            .populate('owner')
            .then(galleries => {
                galleries.map(gallery => {
                    requireOwnership(req, gallery)
                    return gallery.toObject()
                })
            })
            // respond with status 200 and JSON for galleries
            .then(galleries => res.status(200).json({ galleries: galleries }))
            // if an error occurs, pass it to the handler
            .catch(next)
    } else {
        throw new notAllowed()
    }
})
```

**Comment by mqpiffle** [comment]
or
```js
// INDEX -- MINE
// GET /galleries-mine/:id

router.get('/galleries-mine', requireToken, (req, res, next) => {
    if (req.user.isCurator) {
        Gallery.find({ owner: req.user.id })
            .populate('owner')
            .then(galleries => {
                requireOwnership(req, galleries)
                galleries.map(gallery => {
                    return gallery.toObject()
                })
            })
            // respond with status 200 and JSON for galleries
            .then(galleries => res.status(200).json({ galleries: galleries }))
            // if an error occurs, pass it to the handler
            .catch(next)
    } else {
        throw new notAllowed()
    }
})
```

**Comment by mqpiffle** [comment]
neither of which works

**Comment by asands94** [comment]
For the get route, you dont need requireOwnership actually nor do you need the if statement if all you want is for someone to go to the `galleries-mine` route and only see their personal info. If that's not what you want then maybe we can try a different approach

**Comment by mqpiffle** [comment]
do you mean ```if (req.user.isCurator)``` ? I want that, just to protect the route

**Comment by mqpiffle** [comment]
yeah, it's not working without the ```if (req.user.isCurator)``` statement either

**Comment by timmshinbone** [comment]
Does finding the gallery by owner id not work? I thought that they'd need to be the curator anyway to see that? Or do I have a misunderstanding with how these documents are created?

**Comment by mqpiffle** [comment]
it seems like it ought to work...like i said, i tried it without the ```if``` statement too.

```js
// INDEX -- MINE
// GET /galleries-mine/:id

router.get('/galleries-mine', requireToken, (req, res, next) => {
    // if (req.user.isCurator) {
    Gallery.find({ owner: req.user.id })
        .populate('owner')
        .then(galleries => {
            galleries.map(gallery => gallery.toObject())
        })
        // respond with status 200 and JSON for galleries
        .then(galleries => res.status(200).json({ galleries: galleries }))
        // if an error occurs, pass it to the handler
        .catch(next)
    //     } else {
    //         throw new notAllowed()
    //     }
})

```

**Comment by mqpiffle** [comment]
wow, i'm dumb -- thank you guys for the help!!!! (spot the bug lol)

```js
router.get('/galleries-mine', requireToken, (req, res, next) => {
    // if (req.user.isCurator) {
    Gallery.find({ owner: req.user.id })
        .populate('owner')
        .then(galleries => {
            console.log(galleries)
            return galleries.map(gallery => gallery.toObject())
        })
        // respond with status 200 and JSON for galleries
        .then(galleries => res.status(200).json({ galleries: galleries }))
        // if an error occurs, pass it to the handler
        .catch(next)
    //     } else {
    //         throw new notAllowed()
    //     }
})
```

**Comment by asands94** [comment]
Perfect! That's what I was thinking

**Comment by timmshinbone** [comment]
lol, not dumb! Sometimes it just takes a little talking it out to get where you need to be!

**Comment by mqpiffle** [comment]
THANK YOU!!! <3

**Comment by mqpiffle** [comment]
put the return statement back :facepalm:
