### ISSUE TITLE
ClassProject(DeleteView)

### ISSUE THREAD

**Issue by dn412** [sei-ec-remote/team-project-issues#156]
**Describe the bug**
_A clear and concise description of what the bug is._
No bug.

**What is the problem you are trying to solve?**
What to include in the success_url so that when a user deletes a project, the user is returned to the user's personal profile.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Once a User deletes a project, the user is returned to their personal profile

**What is the actual behavior?**
_A clear and concise description of what actually happened._
I'm not sure how to proceed

**Post any code you think might be relevant (one fenced block per file)**
```js
class ProjectDelete(DeleteView):
    model = Project
    success_url = f"/user/{request.user.id}"
```

**What is your best guess as to the source of the problem?**
Trying to figure that out as a collective

**What things have you already tried to solve the problem?**
success_url = reverse_lazy

**Additional context**

**Paste a link to your repository here**
https://github.com/NoahCSmith93/General-Archive

**Comment by dn412** [comment]
Would this work?

```js
class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy("user_profile")
    def get_success_url(self):
        user_id = self.request.user.id
        success_url = reverse("user_profile", kwargs={"user_id": user_id})
        return success_url
```

**Comment by timmshinbone** [comment]
Did you try it out? If so, what was the behavior? Did you get an error?

**Comment by dn412** [comment]
> Did you try it out? If so, what was the behavior? Did you get an error?

It worked
