### ISSUE TITLE
_pycache_

### ISSUE THREAD

**Issue by brendinsgit** [sei-ec-remote/team-project-issues#157]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
I had to download psycopg and I have a pycache file in my folder. They don't have the same file in their folders but when I pushed my code it included it in the pull request. When I pushed the code it tried to overwrite all of the main code with what was in my folder as well. I suggested adding my pycache to gitignore but they wanted to know if they needed it in their folders as well.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Read the top reply to this stackoverflow: https://stackoverflow.com/questions/16869024/what-is-pycache

If the lack of pycache isn't codebreaking, then it's not a problem and they don't need it, if the presence of the folder is causing problems, then we'll have to manage that. Any changes in the behavior of the app?

**Comment by brendinsgit** [comment]
I think it's fine. We aren't able to move forward at the moment with any code because of push/pull issues though.

**Comment by timmshinbone** [comment]
Ok, can you describe the issue or share a screenshot of the terminal?

**Comment by brendinsgit** [comment]
Ashley just came into the room and I believe everything is resolved now. Thanks for the help!
