### ISSUE TITLE
Create button not clicking

### ISSUE THREAD

**Issue by Kateattardo** [sei-ec-remote/team-project-issues#158]
**Describe the bug**
_A clear and concise description of what the bug is._
One of our forms button to create a new task is not clicking and not generating any errors.

**What is the problem you are trying to solve?**
Trying to get the button to click 

**Expected behavior**
_A clear and concise description of what you expected to happen._
Expect the submit button to engage when new task is created but it doesn't.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
It does nothing and displays in the terminal as if it worked:
 [18/Sep/2023 15:21:57] "GET /tasks/create/ HTTP/1.1" 200 3638

**Post any code you think might be relevant (one fenced block per file)**
```py
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add Task</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add Task" class="btn">
</form>
{% endblock %}

```

**What is your best guess as to the source of the problem?**
We think it's the form action which is blank at the moment

**What things have you already tried to solve the problem?**
we put the url in the action form but the project action form is blank and works correctly

**Additional context**

**Paste a link to your repository here**
https://github.com/Kateattardo/task_master.git

**Comment by asands94** [comment]
If the form is meant to create then you want to see POST not GET in the terminal. So make sure that your view is setup correctly in the views.py. Can you share that code?

**Comment by Kateattardo** [comment]
Sure thing:

#TASK VIEWS
class TaskList(ListView):
    model = Task
    template_name = 'tasks/index.html'
# class TaskDetail(DetailView):
#     model = Task
#     template_name = 'tasks/detail.html'

def tasks_detail(request, task_id):
  task = Task.objects.get(id=task_id)
  comments = Comment.objects.filter()
  return render(request, 'tasks/detail.html', {
    'comments': comments, 
    'task': tasks,
  })

class TaskCreate(CreateView):
    model = Task
    # fields = ['title', 'description', 'owner', 'due_date', ' project', 'status', 'priority']
    fields = '__all__'
    success_url = '/tasks/'




class TaskUpdate(UpdateView):
    model = Task
    # fields = ['title', 'description', 'owner', 'due_date', ' project', 'status', 'priority']
    fields = '__all__'
    success_url = '/tasks/'
class TaskDelete(DeleteView):
    model = Task
    # instead of fields or using the absolure_url, we just use a success_url
    success_url = '/tasks/'
