### ISSUE TITLE
Template rendering interfering withupdate and delete link.

### ISSUE THREAD

**Issue by jpineda48** [sei-ec-remote/team-project-issues#159]
**Describe the bug**
_A clear and concise description of what the bug is._

When I try to render the gift detail page i get a "NoReverseMatch at /gifts/1/"

when I remove the update and delete links at the bottom the page works. I believe my urls are all in order and written correctly. 

**What is the problem you are trying to solve?**

correct url rendering

**Expected behavior**
_A clear and concise description of what you expected to happen._

Details should render with delete and update options at the bottom

**What is the actual behavior?**
_A clear and concise description of what actually happened._

receiving a "NoReverseMatch at /gifts/1/" error

**Post any code you think might be relevant (one fenced block per file)**
DETAILS PAGE 
```js
{% block content %}

    <h1>Gift Detail</h1>

        <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        {{gift.ideas}}
                    </span>
                </div>
                <div class="card-action">
                    <a class="btn" href="{% url 'gifts_update' gift.id %}">Edit</a>
                    <a class="btn red" href="{% url 'gifts_delete' gift.id %}">Delete</a>
                </div>
          
        </div>
    

{% endblock %

```
URLS PAGE
```js
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('birthdays/', views.birthdays_index, name='index'),
    path('birthdays/<int:birthday_id>/', views.birthdays_detail, name='detail'),
    path('birthdays/create/', views.BirthdayCreate.as_view(), name='birthdays_create'),
    path('birthdays/<int:pk>/update/', views.BirthdayUpdate.as_view(), name='birthdays_update'),
    path('birthdays/<int:pk>/delete/', views.BirthdayDelete.as_view(), name='birthdays_delete'),
    #need several urls for ideas to work
    path('gifts/', views.GiftIdeaList.as_view(), name='gifts_index'),
    path('gifts/<int:pk>/', views.GiftIdeaDetail.as_view(), name='gifts_detail'),
    path('gifts/create/', views.GiftIdeaCreate.as_view(), name='gifts_create'),
    path('gifts/<int:pk>/update/', views.GiftIdeaUpdate.as_view(), name='gifts_update'),
    path('gifts/<int:pk>/delete', views.GiftIdeaDelete.as_view(), name='gifts_delete')
    
]

```
VIEWS PAGE
```js

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.views.generic import ListView, DetailView



from.models import Birthday, GiftIdea


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

def birthdays_index(request):
  birthdays= Birthday.objects.all()
  # We pass data to a template very much like we did in Express!
  return render(request, 'birthdays/index.html', {
    'birthdays': birthdays
  })

def birthdays_detail(request, birthday_id):
  birthday = Birthday.objects.get(id=birthday_id)
  return render(request, 'birthdays/detail.html', { 'birthday': birthday })

class BirthdayCreate(CreateView):
  model = Birthday
  fields = ['first_name', 'last_name','date', 'relationship', 'address', 'phone_number', 'email', 'delivery_method' ]

class BirthdayUpdate(UpdateView):
  model = Birthday
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = '__all__'

class BirthdayDelete(DeleteView):
  model = Birthday
  success_url = '/birthdays'

#views for gifts

class GiftIdeaList(ListView):
   model=GiftIdea 
   template_name = 'gifts/index.html'

class GiftIdeaDetail(DeleteView):
   model=GiftIdea
   template_name = 'gifts/detail.html'

class GiftIdeaCreate(CreateView):
   model= GiftIdea
   fields = '__all__'

class GiftIdeaUpdate(UpdateView):
   model=GiftIdea
   fields= '__all__'

class GiftIdeaDelete(DeleteView):
   model = GiftIdea
   success_url = '/gifts'
               

# Create your views here.


```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

checking a double checking urls, rearranging urls.

**Additional context**

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Can you share a screenshot of the traceback shown in the browser?

**Comment by jpineda48** [comment]
<img width="1287" alt="Screen Shot 2023-09-18 at 1 57 00 PM" src="https://github.com/sei-ec-remote/team-project-issues/assets/135978440/ae872203-e57d-4afa-986c-ff06aa55445d">

**Comment by asands94** [comment]
Is your GiftIdeaDetail meant to be a delteview?

**Comment by jpineda48** [comment]
<img width="1253" alt="Screen Shot 2023-09-18 at 2 21 33 PM" src="https://github.com/sei-ec-remote/team-project-issues/assets/135978440/6303a126-0191-447d-94ef-e21adaf78343">

**Comment by jpineda48** [comment]
> Is your GiftIdeaDetail meant to be a delteview?

yes! i fixed it hoping it was the issue but still receiving the same error.

**Comment by timmshinbone** [comment]
One quick way to source the bug here is to replace the problematic `<a>` tag with a `<p>` that displays the value you're trying to use, in this case, it would be the `gift.id`. Try that and let me know what turns up.

**Comment by jpineda48** [comment]
<img width="1287" alt="Screen Shot 2023-09-18 at 2 37 30 PM" src="https://github.com/sei-ec-remote/team-project-issues/assets/135978440/f5fb62b9-ca1d-46cc-a181-f9c41170ce4e">

**Comment by jpineda48** [comment]
looks like that is the issue

**Comment by jpineda48** [comment]
i checked the data base and they exist and have an id number

**Comment by jpineda48** [comment]
trying to do some cross referencing to figure it out and wondering where "toy" is coming form on this detail page. 
<img width="622" alt="Screen Shot 2023-09-18 at 2 43 56 PM" src="https://github.com/sei-ec-remote/team-project-issues/assets/135978440/1947b7fe-85b1-407b-af47-be7811f4c699">

probaby been staring at it for too long but i cant seem to find where it is being referenced from to be able to render the toy.color

**Comment by timmshinbone** [comment]
You used the wrong tags, instead of `{% gift.id %}` you need to use `{{ gift.id }}` to inject the value, making sure it's accessible in the template
