### ISSUE TITLE
Trying to change the format of my Date.

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/team-project-issues#16]
**Describe the bug**
_A clear and concise description of what the bug is._

When I try to implement `moment.js` into my view to change the format of my date it stops rendering the whole show view. The error that appears is `Warning: Invalid DOM property class. Did you mean className?`, the error also tells me that the error is coming from the first line in my `index.js`, but I never touched anything in that file.

**What is the problem you are trying to solve?**

I am trying to convert the date into a more user friendly format to display on my show page

**Expected behavior**
_A clear and concise description of what you expected to happen._

I was expecting the date format to change into something similar to "January 1, 2000"

**What is the actual behavior?**
_A clear and concise description of what actually happened._

The show page that use to render isn't rendering anymore and there are errors popping up talking about my `DOM`.

**Post any code you think might be relevant (one fenced block per file)**
```js
const ShowVisited = (props) => {
    const [visited, setVisited] = useState(null)
    const [modalOpen, setModalOpen] = useState(false)
    const [updated, setUpdated] = useState(false)
    const { user, msgAlert } = props
    const { id } = useParams()
    const navigate = useNavigate()
    // IVY -> trying to chnage time format here
    // let visitFromDate = moment(visited.visitFromDate, "DD-MM-YYYY")
    // console.log("this is the formatted date", visitFromDate)
    // console.log('id in showVisited', id)

    // empty dependency array in useEffect to act like component did mount
    useEffect(() => {
        getOneVisit(id)
            .then(res =>

                setVisited(res.data.visit)
            )
            .then(() => {
                msgAlert({
                    heading: 'The spooky visited has been retrieved!',
                    message: showVisitedSuccess,
                    variant: 'success',
                })
            })
            .catch(() => {
                msgAlert({
                    heading: 'Failed to find the spooky visit',
                    message: showVisitedFailure,
                    variant: 'danger',
                })
            })
    }, [updated])

    const removeTheVisited = () => {
        console.log("removeTheVisited id", visited.id)
        console.log("removeTheVisited _id", visited._id)

        removeVisited(user, visited._id)
            .then(() => {
                msgAlert({
                    heading: 'The spooky visited has been removed!',
                    message: 'The spooky visited has been deleted',
                    variant: 'success',
                })
            })
            .then(() => { navigate(`/myvisits`) })
            .catch(() => {
                msgAlert({
                    heading: 'Spooky Visited deletion failed.',
                    message: 'Failed to delete the spooky visited',
                    variant: 'danger',
                })
            })
    }

   

    if (!visited) {
        return (
            <Container fluid className="justify-content-center">
                <Spinner animation="border" role="status" variant="warning" >
                    <span className="visually-hidden">Loading....</span>
                </Spinner>
            </Container>
        )
    }

    return (
        <>
            <Container className="fluid">
                <Card>
                    <Card.Header>Visit</Card.Header>
                    <Card.Body>
                        <Card.Text>
                            <small>Description: {visited.description}</small><br />
                            <small>rating: {visited.visitRating}</small><br />
                            <small>Date from: {visited.visitFromDate}</small><br />
                            {/* THINGS THAT DIDN'T WORK: ...................................... */}
                            {/* <Moment format="YYY MMMM dddd">{visited.visitFromDate}</Moment> */}
                            {/* <small>Date from: {moment(visited.visitFromDate).toDate()}</small><br /> */}
                            <small>Date to: {visited.visitToDate}</small><br />
                        </Card.Text>
                    </Card.Body>
                    <Card.Footer>
                        <Button onClick={() => setModalOpen(true)} className="m-2" variant="warning">
                            Edit Visited
                        </Button>
                        <Button onClick={() => removeTheVisited()} className="m-2" variant="danger">
                            Delete Visited
                        </Button>
                    </Card.Footer>
                </Card>
            </Container>

```

**What is your best guess as to the source of the problem?**

The logic and syntax is incorrect.

**What things have you already tried to solve the problem?**

- I tried to use `moment.js` int he return, as well as before my `useEffect()`.

- I also tried looking at the docs

- youtube

**Additional context**

I have all the information in front of me, but I just don't know how to correctly use it and where to use it.

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-client

**Comment by DoireannJane** [comment]
In the things that didn't work section, had you changed that moment format around?

**Comment by ivycle94** [comment]
I did mess around with the syntax and rearrange things last night, but I couldn't get it to work. Is that what you meant?

**Comment by DoireannJane** [comment]
And just to check, you imported moment.js right?

**Comment by ivycle94** [comment]
yeah :)

**Comment by DoireannJane** [comment]
I'm looking at some stackoverflows like this --->  https://stackoverflow.com/questions/57782017/how-to-use-momentjs-with-react ----- just to make sure your syntax is right. Not entirely sure why it's flagging your index file. I might pop in in a second.

**Comment by ivycle94** [comment]
Okie dokie! I'll take a look at the link and update you afterwards! thank you.

**Comment by ivycle94** [comment]
So I tried changing my moment import from `import moment from 'moment';` to `import Moment from 'react-moment';` to follow the stackoverflow link, but now it says `Module not found` . So for react I would need to install `react-moment` and not `moment`?

**Comment by DoireannJane** [comment]
Imported react-moment instead and uninstalled momentjs and found 'class' that was throwing the other error and changed it to 'className'
