### ISSUE TITLE
Cannot get add birthday form to save to database

### ISSUE THREAD

**Issue by DaceyForward** [sei-ec-remote/team-project-issues#160]
**Describe the bug**
_A clear and concise description of what the bug is._
I am able to add birthdays via the admin portal, but when I try to add through our rendered form, the submit button goes nowhere and does not save to the database.

**What is the problem you are trying to solve?**
Saving the entered information on the UI to the database and displaying on the birthday details page.

**Expected behavior**
_A clear and concise description of what you expected to happen._
When clicking "submit," the new birthday information should render on a birthday details page with a new id.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Nothing happens on click, no error shows, and no data is saved or rendered.

In terminal, it says, "[18/Sep/2023 14:15:55] "GET /birthdays/create/ HTTP/1.1" 200 4782"

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
I feel like I'm missing something that should connect everything together, but I can't figure out where.

**What things have you already tried to solve the problem?**
Referenced notes and previous labs, checked urls to make sure matching, tried UI and checked database, etc.

**Additional context**

**Paste a link to your repository here**
https://github.com/DaceyForward/Pod1-Project-3.git

**Comment by timmshinbone** [comment]
When you create birthdays using the form on the page, do they show up in the index view or in the admin portal? If they're saving to the db, then the problem is the redirect, otherwise, it'll be a problem with create functionality

**Comment by asands94** [comment]
The issue was the fields idea field not being filled out!
