### ISSUE TITLE
date picker functionality

### ISSUE THREAD

**Issue by Kateattardo** [sei-ec-remote/team-project-issues#161]
**Describe the bug**
_A clear and concise description of what the bug is._
The Materialize date picker functionality isn't working.

**What is the problem you are trying to solve?**
The Materialize date picker functionality isn't working.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expect the date picker functionality to work  when selecting  the due date for a project

**What is the actual behavior?**
_A clear and concise description of what actually happened._
No errors generated but the date picker does not pop up

**Post any code you think might be relevant (one fenced block per file)**
```js
```  document.addEventListener('DOMContentLoaded' , function() {
    var elms = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, {
      format: 'yyyy-mm-dd',
      defaultDate: newDate(),
      setDefaultDate: true,
      autoClose:true
    });

```
```
from django import forms
from django.forms.widgets import DateTimeInput
from django import ModelForm
from main_app.models import, Project, Task, 

class ProjectForm(forms.ModelForm):
  due_date = forms.DateTimeField(widget=CustomDateTimeInput())

  class Meta:
    model = Project
    fields = [...]

class TaskForm(forms.ModelForm):
  due_date = forms.DateTimeField(widget=CustomDateTimeInput())

  class Meta:
    model = Task
    fields = [...]
```
<input type="text" class="datepicker" value="{{task.due_date|date: Y-m-d}}">

**What is your best guess as to the source of the problem?**
Somthing I'm missing in the forms 

**What things have you already tried to solve the problem?**
```
  // const dateEl = document.getElementById('task_due_date');
  // // M is Materialize's global variable
  // M.Datepicker.init(dateEl, {
  //     format: 'yyyy-mm-dd',
  //     defaultDate: new Date(),
  //     setDefaultDate: true,
  //     autoClose: true
  // });

  // const selectEl = document.getElementById('project_due_date');
  // M.FormSelect.init(selectEl)


I've tried task_due_date, project_due_date, id_date



**Additional context**
Add any other context about the problem here.



**Paste a link to your repository here**

**Comment by asands94** [comment]
Did you add the javascript cdn link to the base.html?

**Comment by asands94** [comment]
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
```

**Comment by Kateattardo** [comment]
Yes I did

**Comment by asands94** [comment]
You maye need to try something like this based on the name of your model fields

```html
 <script>
        const dateEl = document.getElementById('id_due_date');
        // M is Materialize's global variable
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
    </script>
```

**Comment by asands94** [comment]
You can also use your dev tools to tell you what the ID is by hovering over that field.
<img width="1260" alt="Screenshot 2023-09-19 at 10 24 59 AM" src="https://github.com/sei-ec-remote/team-project-issues/assets/84302689/4c46ba8b-fca9-46b1-859d-f4a4c764a0ff">

**Comment by Kateattardo** [comment]
Still nothing I’ve tried A LOT of (‘…_date’)
