### ISSUE TITLE
Adding Dropdown List

### ISSUE THREAD

**Issue by brendinsgit** [sei-ec-remote/team-project-issues#164]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
An exercise can be added to the 'all exercises' list but when I tried to add a dropdown for the category it didn't work.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
Not sure but I've tried many things

**What things have you already tried to solve the problem?**
Articles online and didn't try the last stackoverflow solution because it might've caused issues with other stuff

**Additional context**

**Paste a link to your repository here**
![issue_pic01](https://github.com/sei-ec-remote/team-project-issues/assets/139824521/e30ad994-1bee-4469-b7cb-ab88469d3721)
![Issue_pic02](https://github.com/sei-ec-remote/team-project-issues/assets/139824521/e9bcadb8-7b51-4003-bd50-f0c005cfd575)
![Issue_pic03](https://github.com/sei-ec-remote/team-project-issues/assets/139824521/87dea3ab-62e9-44ab-84ac-5a2bcd5e0374)

**Comment by asands94** [comment]
What does the form currently look like?

**Comment by asands94** [comment]
In the browser

**Comment by brendinsgit** [comment]
It's not clickable at the moment

![Issue_pic04](https://github.com/sei-ec-remote/team-project-issues/assets/139824521/502012a4-eae5-4bf5-982d-7b102fce6527)
