### ISSUE TITLE
Admin Portal CSS and Scripts 404

### ISSUE THREAD

**Issue by cooperwhitley** [sei-ec-remote/team-project-issues#165]
**Describe the bug**
_A clear and concise description of what the bug is._

When accessing the admin portal the log reads that fetching the admin stylesheets and scripts is returning a 404 error. This results in the admin portal not rendering/functioning correctly.

**What is the problem you are trying to solve?**

I would like to figure out what is causing django to not see/use the default stylesheets and how to address it.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The admin portal should fetch the proper scripts and stylesheets, as it has in the past.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

The admin portal renders as plain html as the scripts and stylesheets are not found.

**Post any code you think might be relevant (one fenced block per file)**

the terminal output:
```
[19/Sep/2023 20:18:38] "GET /admin/ HTTP/1.1" 200 8439
[19/Sep/2023 20:18:38] "GET /static/admin/css/base.css HTTP/1.1" 404 1813
[19/Sep/2023 20:18:38] "GET /static/admin/css/responsive.css HTTP/1.1" 404 1831
[19/Sep/2023 20:18:38] "GET /static/admin/css/dashboard.css HTTP/1.1" 404 1828
[19/Sep/2023 20:18:38] "GET /static/admin/css/dark_mode.css HTTP/1.1" 404 1828
[19/Sep/2023 20:18:38] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 404 1834
[19/Sep/2023 20:18:38] "GET /static/admin/js/theme.js HTTP/1.1" 404 1810
[19/Sep/2023 20:18:38] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 404 1828

```

**What is your best guess as to the source of the problem?**

We are using the tailwind CSS library, alongside the css compressor app, I feel one of these are perhaps responsible.

**What things have you already tried to solve the problem?**

I have tried disabling the css compressor app, however that does not seem to have fixed it.

**Additional context**

**Paste a link to your repository here**
https://github.com/cooperwhitley/teacheasy

**Comment by asands94** [comment]
Do you see all your styling when not accessing the Admin portal?

**Comment by cooperwhitley** [comment]
We do, yes

**Comment by cooperwhitley** [comment]
It looks like the install of TailwindCSS was causing the issue, made an exact replica of the repository with only that removed and it is working, for the sake of time we are probably just going to work without Tailwind.

**Comment by asands94** [comment]
Tailwind would be great for next unit if you all individually still wanted to give that a try.

**Comment by cooperwhitley** [comment]
For sure, it's definitely a super cool library.
