### ISSUE TITLE
CreateView is rendering confirm_delete page. 

### ISSUE THREAD

**Issue by jpineda48** [sei-ec-remote/team-project-issues#168]
**Describe the bug**
_A clear and concise description of what the bug is._

My giftidea_form is going to the delete page instead of creating and listing a new idea. 

**What is the problem you are trying to solve?**

a url issue, i believe.

**Expected behavior**
_A clear and concise description of what you expected to happen._

When you submit a new idea it should be posted in the details page where are ideas are to be rendered..

**What is the actual behavior?**
_A clear and concise description of what actually happened._

the delete page for ideas is rendered

**Post any code you think might be relevant (one fenced block per file)**
GIFT IDEA FORM
```js
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
  {% endblock %}

```
URL
```js
 path('gifts/create/', views.GiftCreate.as_view(), name='gifts_create'),

```

VIEW
```js
class GiftCreate(LoginRequiredMixin, CreateView):
   model= GiftIdea
   fields = '__all__'

   def form_valid(self, form):
    form.instance.user = self.request.user 
    return super().form_valid(form)
```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

Ive crodd referenced multiple times

**Additional context**

**Paste a link to your repository here**

https://github.com/jpineda48/Pod1-Project-3

**Comment by asands94** [comment]
What is the file path where the form is?

**Comment by jpineda48** [comment]
main_app/templates/main_app/giftidea-form.html

**Comment by asands94** [comment]
Make sure it's: main_app/templates/main_app/giftidea_form.html

**Comment by jpineda48** [comment]
looks like it is
.

**Comment by jpineda48** [comment]
i went through the chain a few times

**Comment by asands94** [comment]
Lets go to room 10 to double check everything
