### ISSUE TITLE
Reopened requireOwnership function not working with one of our update routes

### ISSUE THREAD

**Issue by mitchgemma** [sei-ec-remote/team-project-issues#17]
**Describe the bug**
_A clear and concise description of what the bug is._
requireOwnership function not working with one of our update routes

**What is the problem you are trying to solve?**
Trying to get the function working 

**Expected behavior**
_A clear and concise description of what you expected to happen._
Profile updates after a user submits

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Getting an error saying cannot get properties of _id

**Post any code you think might be relevant (one fenced block per file)**
```js
router.patch(
  '/user/:userId/:profileId',
  requireToken,
  removeBlanks,
  (req, res, next) => {
    const userId = req.params.userId
    const profileId = req.params.profileId + ''

    User.findById(userId)
      .then(handle404)
      .then((user) => {
        // keeping all of these to troubleshoot with Timm
        // also route seems to be working without the profileId param
        console.log('user.profile.id', user.profile.id)
        console.log('the user.profile ya know', user.profile)
        console.log('req.body.profile', req.body.profile)

        // const theProfile = user.profile.id(profileId)
        // console.log('the profile', theProfile)
        user.profile = req.body.profile
        console.log('req', req)
        console.log('user', user)
        // requireOwnership causing issues for route - put on back burner and ask Timm
        // requireOwnership(req, user)

        return user.save()
      })
      .then(() => res.sendStatus(204))
      .catch(next)
  }
)
```

**What is your best guess as to the source of the problem?**

Issue with the actual function itself in custom_errors

**What things have you already tried to solve the problem?**
Worked with Goro in office hours, console.log, remove the function

**Additional context**

Route is working when we take out the function

**Paste a link to your repository here**
https://github.com/katherine-kania/team-mack-api

**Comment by tkolsrud** [comment]
where's that require ownership function coming from?

**Comment by mitchgemma** [comment]
Timm recommended we change our subdocument to a model. I did that last night and am still getting the same issues 'properties of _id cannot be found' regarding the requireOwnership function in custom_errors

**Comment by timmshinbone** [comment]
Show the controller here for `Profile` where you're using requireOwnership, and in a separate codeblock show the react side where you're trying it, then in another code block, show the api function you're using in that react component

**Comment by mitchgemma** [comment]
Here is the controller where I am using requireOwnership

`router.patch(
  '/user/:profileId',
  requireToken,
  removeBlanks,
  (req, res, next) => {
    const profileId = req.params.profileId

    Profile.findById(profileId)
      .populate('owner')
      .then(handle404)
      .then((profile) => {
        console.log('the profile', profile)

        console.log('req', req)
        console.log('user', profile)

        requireOwnership(req, profile)
        return profile.updateOne(req.body.profile)
      })
      .then(() => res.sendStatus(204))
      .catch(next)
  }
)`

I have just been using postman to test the update route so I do not have code in react that uses this route. Here's a screenshot of what I have been testing in postman.

![Screen Shot 2022-04-07 at 11 42 49 AM](https://user-images.githubusercontent.com/98479455/162239876-169bc2c6-cf76-409b-b268-83c0d94d158c.png)

**Comment by timmshinbone** [comment]
ok, what do the console logs say?

**Comment by mitchgemma** [comment]
![Screen Shot 2022-04-07 at 1 44 45 PM](https://user-images.githubusercontent.com/98479455/162264707-72c095e3-6b61-49f5-ab39-4d2908195758.png)
