### ISSUE TITLE
associate many to many relationship with a dropdown list

### ISSUE THREAD

**Issue by jadewang425** [sei-ec-remote/team-project-issues#170]
**Describe the bug**
_A clear and concise description of what the bug is._
I created a form with a drop down list to associate exercises with a workout, but I'm not quite sure how to 

**What is the problem you are trying to solve?**
associate exercise(s) to workout

**Expected behavior**
_A clear and concise description of what you expected to happen._
select the exercise(s) from the drop down list, and add to the workout

**What is the actual behavior?**
_A clear and concise description of what actually happened._
getting an error page and exercise(s) not added

**Post any code you think might be relevant (one fenced block per file)**
```js
    <div class="col s6">
        <form action="{% url 'add_exercise' workout.id exercise.id %}" method="POST">
            {% csrf_token %}
            <select name="" id="id_exercises"></select>
            {% for exercise in exercises %}
                {{ exercise }}
            {% endfor %}
            <input type="submit" class="btn" value="Add Exercise">
        </form>
    </div>
```

**What is your best guess as to the source of the problem?**
in the function in views or in the html file

**What things have you already tried to solve the problem?**
different functions or looping over the exercises available

**Additional context**

**Paste a link to your repository here**
https://github.com/jadewang425/gym_grid

**Comment by asands94** [comment]
What is the error?

**Comment by jadewang425** [comment]
I'm not sure what I did but I can't see any options from the dropdown list anymore...
![image](https://github.com/sei-ec-remote/team-project-issues/assets/140425997/ee91c7b0-5677-4ce6-bffa-48f44961f87d)

**Comment by jadewang425** [comment]
I got it back! here's the message
![image](https://github.com/sei-ec-remote/team-project-issues/assets/140425997/1f4e388c-9fa0-4a68-8bb3-907bc3ccd996)

**Comment by asands94** [comment]
Can you also share the view.py thats responsible for adding an exercise. Did you add the exercise_id in the form.is_valid() section?

**Comment by jadewang425** [comment]
I'm not sure if using the form is the best way to go, but when I tried with the associate function similar to associating toy to a cat, it doesn't let me iterate the exercises for the dropdown list
![image](https://github.com/sei-ec-remote/team-project-issues/assets/140425997/07ec577d-acd6-40cb-8fd0-6acd4b453b69)

**Comment by asands94** [comment]
If you print `exercise_id` are you getting a number back?

**Comment by jadewang425** [comment]
No, I'm not getting the number back and it doesn't print in the terminal as well.
![image](https://github.com/sei-ec-remote/team-project-issues/assets/140425997/739aa37d-55cc-4bae-b080-938ce0a0bd95)

**Comment by asands94** [comment]
Ok, then you may want to try adding in a bunch of exercises then associating them like we did with cats and toys using the assoc_toys method
