### ISSUE TITLE
Add_Form

### ISSUE THREAD

**Issue by RyanCLuis** [sei-ec-remote/team-project-issues#174]
**Describe the bug**
_A clear and concise description of what the bug is._
when we try and add a new pet from out pet_form.html, the button doesnt work/and when we look at the admin portal, it doesnt add a new pet.

**What is the problem you are trying to solve?**
we are trying to solve how to get our form to post a new pet, also the form doesnt allow us to click a box for the boolean.

**Expected behavior**
_A clear and concise description of what you expected to happen._
It's suppose to add a new pet to our database.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
the button doesnt want to redirect to the index page and doesnt actually post to our database.

**Post any code you think might be relevant (one fenced block per file)**
```
from django.db import models
from django.urls import reverse

# Import the User
from django.contrib.auth.models import User

# Create your models here.
class Pet(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    # size = models.CharField(max_length=100)
    age = models.IntegerField()
    # gender = models.CharField(max_length=100)
    shots_received = models.TextField(max_length=500)
    description = models.TextField(max_length=500)
    fixed = models.BooleanField()

    # Add the foreign key linking to a user
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pet_id': self.id})
```
```
{% extends 'base.html' %}

{% block content %}
  <h1>Create a Pet</h1>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Pet</button>
  </form>
{% endblock %}
```
```
{% extends 'base.html' %}
{% block content %}

  <h1>Pet List</h1>

{% for pet in pets %}
  <div class="card">
    <a href="/pets/{{pet.id}}">
      <div class="card-content"></div>
        <span class="card-title">{{ pet.name }}</span>
          <p>Species: {{ pet.species }}</p>
          {% if pet.age > 0 %}
            <p>Age: {{ pet.age }}</p>
          {% else %}
            <p>Age: Baby</p>
          {% endif %}
          <p>Shots Received: {{ pet.shots_received }}</p>
          <p>Descriptions: {{ pet.description }}</p>
          <p>Fixed?: {{ pet.fixed }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

```

**What is your best guess as to the source of the problem?**
we think it has to do something with the boolean and the user field because it wont let us type or do anything for them.

**What things have you already tried to solve the problem?**
we committed out the fixed? field and the user field in the model and the database does update but we need those fields included.

**Additional context**

**Paste a link to your repository here**
https://github.com/RyanCLuis/Fur-Ever-Friends

**Comment by nayaba** [comment]
> the button doesnt work

Which button?

**Comment by nayaba** [comment]
I ask because I've cloned down your repo and I'm not even seeing a form populate

**Comment by RyanCLuis** [comment]
@nayaba it is currently on Juan's branch, we havent pushed it up since it isnt working

**Comment by RyanCLuis** [comment]
did you want us to push it up so you can see it or join us so we can show you?

**Comment by nayaba** [comment]
Can I see your create view?

**Comment by RyanCLuis** [comment]
```
class PetCreate(CreateView):
    model = Pet
    fields = '__all__'
    #template_name = 'pets/pet_form.html'
    #success_url = reverse_lazy('main_app:dogs_index') # Redirect to the dogs page after successful form submission
    ```

**Comment by nayaba** [comment]
So I _think_ ya'll need to add a function in your view like this one:

```python
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
```
which can assign the logged in user as the owner when creating the pet

**Comment by RyanCLuis** [comment]
we did some things but we still cant get the fixed field, which is a boolean to display, the user field went away but the fixed field is blank and we cant check mark it or uncheck mark it
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/c18a7a98-f3de-43d9-872c-f5f71179afa7)

**Comment by RyanCLuis** [comment]
and this is in our models for the fixed field
```
fixed = models.BooleanField(default=False)
```

**Comment by RyanCLuis** [comment]
okay we have everything working.... we can add a pet, we can see the pet in the index, only thing is we can changed the fixed field, it is still blank on the pet_form.html, but when we look at the index it just says false.
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/2ecc6a07-0d4e-439c-9f49-e59a0b25bfb1)

**Comment by nayaba** [comment]
The problem is with materialize UI... am investigating a workaround

**Comment by RyanCLuis** [comment]
Fixed the issue in Office hours
