### ISSUE TITLE
Help with model setup 

### ISSUE THREAD

**Issue by da1dude** [sei-ec-remote/team-project-issues#176]
**Describe the bug**
_A clear and concise description of what the bug is._

We are looking to impliment the idea that Timm provided for having our checkin model be tied to our medications model but are confused on how to implement that. Could we talk with you about this so we better understand what needs to be done. 

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

https://github.com/da1dude/petdesk

**Comment by nayaba** [comment]
Before we meet, can you update your ERD with an example that reflects how you _think_ it should be executed (or your best guess) as well as a short description of how it works.
