### ISSUE TITLE
Adding a photo

### ISSUE THREAD

**Issue by RyanCLuis** [sei-ec-remote/team-project-issues#177]
**Describe the bug**
_A clear and concise description of what the bug is._
when i try and add a photo to the page, and error pops up saying "column main_app_photo.pet_id does not exist" 
but also gives me a hint of "HINT:  Perhaps you meant to reference the column "main_app_photo.dog_id"." so somewhere it is trying to get a dog_id but i have nothing in my code the references dog_id. Before, when writing the code we started with dog to make things easier, then we switched over to pet. 

**What is the problem you are trying to solve?**
the dtails page wont show a picture.

**Expected behavior**
_A clear and concise description of what you expected to happen._
when the page renders it is suppose to show no photo has been added, but instead it throws that error

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```
{% for photo in pet.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" alt="Cat Photo">
{% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}

```
```
def add_photo(request, pet_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, pet_id=pet_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', pet_id=pet_id)
```
```
class Pet(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    # size = models.CharField(max_length=100)
    age = models.IntegerField()
    # gender = models.CharField(max_length=100)
    shots_received = models.TextField(max_length=500)
    description = models.TextField(max_length=500)
    fixed = models.BooleanField(default=False)

    # Add the foreign key linking to a user
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pet_id': self.id})
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for pet_id: {self.pet_id} @{self.url}"
```

**What is your best guess as to the source of the problem?**
im thinking maybe in the migrations somewhere it still has a dog_id and have no way of deleting that id

**What things have you already tried to solve the problem?**
ive tried deleting all my migrations and migrating again and still throws up the same errors

**Additional context**

**Paste a link to your repository here**
the error is on my branch so inst on the repo
https://github.com/RyanCLuis/Fur-Ever-Friends

**Comment by nayaba** [comment]
Can you look at your actual database in neon and see what the columns are named - is there a dog column?

**Comment by RyanCLuis** [comment]
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/fa63f425-b8fc-479a-9d2f-a16ba0e4cefb)
but in the models i have 
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/4015df9f-17a3-412d-8ca4-b4e90ba6f590)

**Comment by nayaba** [comment]
Try to make migrations and then run them

**Comment by RyanCLuis** [comment]
would that have something to do with i created dog_id first and in my migrations i save it. so i would have to delete the database and set it up over again?

![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/fe5d3362-75d8-4c54-976f-6cc339f6dd8d)
still the same error
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/53d87801-efd4-4d6f-854e-e3d1d26cc39b)

**Comment by nayaba** [comment]
You could try dropping the database and migrating again

**Comment by RyanCLuis** [comment]
do i need to delete all my migrations before?
ie 0001_init___
0002 xxxxx
0003xxxxx?

**Comment by RyanCLuis** [comment]
i delete the database and re migrate 
i had to recreate the superuser, but i can still add a pet.
when i click on detail i get the same error, just a little different
![image](https://github.com/sei-ec-remote/team-project-issues/assets/150068816/cdceaf61-a2e6-416c-ae8e-44011f49bc22)

**Comment by nayaba** [comment]
This error is saying that your photo table does not exist.  When you ran makemigrations, did it make any migration files or did it tell you there were no changes to be made?

**Comment by RyanCLuis** [comment]
it said no changed made
