### ISSUE TITLE
Help with CSS for django

### ISSUE THREAD

**Issue by da1dude** [sei-ec-remote/team-project-issues#180]
**Describe the bug**
_A clear and concise description of what the bug is._

none

**What is the problem you are trying to solve?**

Spending time doing CSS and we have a few questions about how django and css work while attempting to change colors and steles. Just could use some help. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/da1dude/petdesk

**Comment by timmshinbone** [comment]
If you're not seeing changes to your CSS display after making those changes, you may have to stop and start the server again, and clear your cache in your browser history. 

Did you have a specific issue or question you wanted to ask here? I can pop into your breakout room in a few minutes

**Comment by da1dude** [comment]
Closed
