### ISSUE TITLE
One more piece of advice needed for Boolean functionality

### ISSUE THREAD

**Issue by JohnArochaDev** [sei-ec-remote/team-project-issues#181]
**Describe the bug**
_A clear and concise description of what the bug is._

We have almost full CRUD functionality, we are missing the Update, and we were hoping to get some advice on how to structure the database to work with Boolean's for our update functionality. No coding issues or problems or bugs, we just need a little advice again.  :]
( I understand how to add a Boolean field, my concern is if we need to make another database, or how we can refer specific data in the chart to have a Boolean for multiple inputs)
**Paste a link to your repository here**
https://github.com/F2easy/Drinks-app

**Comment by nayaba** [comment]
Could you provide some more details?  What field will be a boolean, and on what model?  Can you also expand on why you feel you'd need a separate database?

**Comment by JohnArochaDev** [comment]
We need each ingredient to have a boolean value assigned to it so the user can check off the list which items they have. We only have one model and its the ShoppingGuide model

**Comment by nayaba** [comment]
I believe you'll want to introduce a separate ingredients table/model and remove ingredients from your current model.

You can fashion it after the Toy model in catcollector, wherein you have an Ingredient model that records the ingredient name, as well as a field for on_hand (or owned, has, available, etc. - whatever you want to name it).  Each ShoppingGuide will have the ingredients added on an individual basis.

@timmshinbone what do you think?  Is there another option I'm not seeing?

**Comment by JohnArochaDev** [comment]
We are going to create a new functionality where we update the drink in the database so that we can customize it. Thanks for the help!
