### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/team-project-issues#183]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**

so the problem is that when i make the page smaller i wanted all the nav bar url's to go into the menu which they do but the issue is the old ones still stay there like they go page below  for some unknown reason

**Expected behavior**
_A clear and concise description of what you expected to happen._
when i minimize the screen i want everything to go into the menu the dropdown

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

i tried switching the whole thing into something different but more problems started acquiring so i decided to stay where i was before with the code 

**Additional context**

![Screenshot 2024-01-24 140147](https://github.com/sei-ec-remote/team-project-issues/assets/145096395/2175a497-1134-40e9-9927-37183a320317)

**Paste a link to your repository here**
https://github.com/da1dude/petdesk/blob/main/main_app/templates/base.html

**Comment by nayaba** [comment]
Try adding this class to your ul tag `hide-on-med-and-down`

**Comment by ItsAlbi007** [comment]
> Try adding this class to your ul tag `hide-on-med-and-down`

it worked can you tell me where you found that information
i have been looking for an hour

**Comment by nayaba** [comment]
[Materialize docs](https://materializecss.com/navbar.html), Mobile Collapse Button section
