### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CameronASC20** [sei-ec-remote/team-project-issues#19]
**Describe the bug**
_A clear and concise description of what the bug is._
TypeError: Cannot read properties of null (reading '_id')

**What is the problem you are trying to solve?**
Getting my show page to display

**Expected behavior**
_A clear and concise description of what you expected to happen._
My show page should pop up

**What is the actual behavior?**
_A clear and concise description of what actually happened._
I keep getting errors

**Post any code you think might be relevant (one fenced block per file)**
```js
import React, {useState, useEffect} from 'react'
import { getOneFav, removeFav } from '../../api/favorite'
import { useParams } from 'react-router-dom'
import { Button } from 'react-bootstrap'


const ShowFaves = (props) => {

    const {user, msgAlert, triggerRefresh} = props
    const [favorites, setFaves] = useState(null)
    console.log('props in showFaves', props)
    const { id } = useParams()
    console.log('id in showFaves', id)
    // empty dependency array in useEffect to act like component did mount
    useEffect(() => {
        getOneFav(id)
            .then(res => setFaves(res.data.favorites))
            .catch(console.error)
    }, [id])

    const destroyFav = () => {
        removeFav(user, favorites._id)
            .then(() =>
                msgAlert({
                    heading: 'Fav updated!',
                    message: 'great! the pet loves it!',
                    variant: 'success',
                }))
            .then(() => triggerRefresh())
            // if there is an error, we'll send an error message
            .catch(() =>
                msgAlert({
                    heading: 'Oh No!',
                    message: 'that aint it',
                    variant: 'danger',
            }))
    }

    return (
        <>
            <h5> Show Favorites</h5>
            <p>{favorites._id}</p>
            <p>{favorites.haveSeen}</p>
            <p>{favorites.bird}</p>
            <Button onClick={() => destroyFav()}variant="danger">
                Delete
            </Button>
        </>
    )
}

export default ShowFaves
```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by CameronASC20** [comment]
![Screenshot from 2022-04-06 09-50-56](https://user-images.githubusercontent.com/68292255/161990412-ed37cdb9-ece8-4316-9e04-ddc7e3e08128.png)

**Comment by tkolsrud** [comment]
So that error is telling you that `favorites` is reading as null, try console logging `favorites` and see if you get data back

**Comment by CameronASC20** [comment]
It says null

**Comment by CameronASC20** [comment]
How do I get the data to show?

**Comment by tkolsrud** [comment]
So if favorites is console logging as null, that means that currently there isn't any data. Can you show exactly what's coming up when you console log `favorites`?

**Comment by CameronASC20** [comment]
![Screenshot from 2022-04-06 10-32-23](https://user-images.githubusercontent.com/68292255/161999186-0f62f028-4fb6-4927-96f8-db76efafaf36.png)

**Comment by tkolsrud** [comment]
the `getFaves` api url needed to be adjusted*
