### ISSUE TITLE
adding function to our checkbox

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/team-project-issues#2]
**Describe the bug**
_A clear and concise description of what the bug is._

n/a

**What is the problem you are trying to solve?**

we don't know where to start because the way we want to implement the checkbox is different from how went over checkboxes in class.

**Expected behavior**
_A clear and concise description of what you expected to happen._

We are currently trying to implement that when we click the checkbox, it will save the destination to a db as a Visited destination object . 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

There is no behavior because we haven't written the function for it yet.

**Post any code you think might be relevant (one fenced block per file)**
```js



```

**What is your best guess as to the source of the problem?**

We just have written a function yet for it yet,

**What things have you already tried to solve the problem?**

We don't know where to start, and need some guidance.

**Additional context**

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-api
https://github.com/ivycle94/GhostBustr-client

**Comment by timmshinbone** [comment]
We need more from this issue, you haven't shared any code or anything that will help us help you out. Are y'all even in a place where you should be working on the front end yet? Is your API done yet?

**Comment by ivycle94** [comment]
Gotcha! We'll try to do more research and get some code going to try to make the process easier for both parties. We thought we were done, but we just realized some kinks inside one of our routes atm. so we'll work on that getting sorted out. Sorry about that!

**Comment by timmshinbone** [comment]
No apologies needed! Just wanna get as much info as we can before we debug! :)
