### ISSUE TITLE
Issue with our signin

### ISSUE THREAD

**Issue by oliviawilcox1** [sei-ec-remote/team-project-issues#20]
**Describe the bug**
_A clear and concise description of what the bug is._

It doesn't automatically redirect to the sign in page if we aren't logged in.

**What is the problem you are trying to solve?**

Fix it to redirect to the sign-in.

**Expected behavior**
_A clear and concise description of what you expected to happen._

We expect to not render products without being logged in

**What is the actual behavior?**
_A clear and concise description of what actually happened._

You can see products without being logged in

**Post any code you think might be relevant (one fenced block per file)**
```js
import { Navigate } from 'react-router-dom'

export default function RequireAuth({ user, children }) {

	return user !== null ? children : <Navigate to='/sign-in' replace />
}
```

**What is your best guess as to the source of the problem?**

the navigate page

**What things have you already tried to solve the problem?**

changing the code ins require auth

**Additional context**

**Paste a link to your repository here**
https://github.com/oliviawilcox1/333-client

**Comment by cory-yonomi** [comment]
Can you share your `Routes` codeblock?
