### ISSUE TITLE
git pull not working

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/team-project-issues#21]
**Describe the bug**
_A clear and concise description of what the bug is._
git pull is not working on my api 

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._
i keep getting an error that says      fatal: Not possible to fast-forward, aborting.

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by tkolsrud** [comment]
Are you pulling down into a specific branch, the main branch, etc?

**Comment by Nash4star** [comment]
im pulling into the main branch

**Comment by cory-yonomi** [comment]
Try `git pull --rebase`

For some reading: https://stackoverflow.com/questions/13106179/fatal-not-possible-to-fast-forward-aborting

**Comment by Nash4star** [comment]
that worked haha thank you
