### ISSUE TITLE
issue with PATCH Route - Update cart items

### ISSUE THREAD

**Issue by daenamcclintock** [sei-ec-remote/team-project-issues#22]
**Describe the bug**
_A clear and concise description of what the bug is._
Error Message

```
TypeError: Cannot convert undefined or null to object
    at /Users/daenamcclintock/sei/projects/Project-3/Gytshop-API/app/routes/product_routes.js:128:18
    at Layer.handle [as handle_request] (/Users/daenamcclintock/sei/projects/Project-3/Gytshop-API/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/daenamcclintock/sei/projects/Project-3/Gytshop-API/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/Users/daenamcclintock/sei/projects/Project-3/Gytshop-API/lib/remove_blank_fields.js:17:2)
```

**What is the problem you are trying to solve?**
I am trying to create a backend route to update the order and then a post route to send the data to a checkout page.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expect the route to be able to update the shipping address in the order and then send the data to the checkout page.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
I am receiving a 500 Internal Server error in Postman and the error message above in the terminal

**Post any code you think might be relevant (one fenced block per file)**
```product_Routes.js

// UPDATE - PATCH /products/checkout
// this will push the products in the cart to the checkout page
router.patch('/products/:orderId}', requireToken, removeBlanks, (req, res, next) => {
	const ownerid = req.body.owner
	console.log('owner id: ', ownerid)

	req.body.owner = req.user.id

    const order = req.body.order
	console.log('this is the order', order)

	// Find the order that belongs to the currently logged in user
    Order.find({owner: ownerid})
        .then(handle404)
        .then( order => {
            const productsInCart = order.productsOrdered
			console.log('products array:', productsInCart)
			requireOwnership(req, order)

			// pass the result of Mongoose's `.update` to the next `.then`
			return order.updateMany(req.body.order)
        })
        // Send 201
		.then(() => res.sendStatus(204))
        // Catch errors and send to the handler
        .catch(next)
})

```

**What is your best guess as to the source of the problem?**
I think it is an issue with the backend route.

**What things have you already tried to solve the problem?**
I've used console logs to look at the structure of the data being returned and tried to query the order based on the ownerId and orderId, but I keep getting the same error message.

**Additional context**

**Paste a link to your repository here**
https://github.com/daenamcclintock/Gytshop-API
https://github.com/daenamcclintock/GytShop-Client

**Comment by DoireannJane** [comment]
I might pop in in a second.
