### ISSUE TITLE
Need to reconcile divergent branches

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/team-project-issues#23]
**Describe the bug**
_A clear and concise description of what the bug is._

I don't know how to fix my merge conflict, The terminal says I have divergent branches and need to specify how to reconcile them.

**What is the problem you are trying to solve?**

my merge conflict, and that my branch is out of sync of the main.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Just to merge and get my branch up to date

**What is the actual behavior?**
_A clear and concise description of what actually happened._

The only thing I know is that i currently have a merge conflict and that my branch is not in sync with main.

**Post any code you think might be relevant (one fenced block per file)**
not really a code block, but this is the error and hints I get in my terminal
```js
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

**What is your best guess as to the source of the problem?**

I did something to mess up the workflow of merging

**What things have you already tried to solve the problem?**

Nothing yet because I don't feel confident in resolving the issue with the commands in my terminal without having someone to consult with.

**Additional context**

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-client

**Comment by tkolsrud** [comment]
do you want to pull updated code into your fork/repo? Basically rebase false means that the upstream branch you're pulling from will override your local one, rebase.true means that you're keeping your current code and overriding the pull

**Comment by ivycle94** [comment]
I just fixed the issue, but thank you Tom! that cleared up a lot of confusion that I have about those commands!
