### ISSUE TITLE
Trouble with editing info

### ISSUE THREAD

**Issue by NikPurvis** [sei-ec-remote/team-project-issues#27]
**Describe the bug**
_A clear and concise description of what the bug is._
When I try to make an edit to a document in the database, I'm receiving an error message and the update doesn't take.

**What is the problem you are trying to solve?**
I'm unable to update or make changes to an existing document.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected the information changed in the edit form to be pushed to the database.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
When I make a change to the document and hit submit, I get the failure message in my browser and long string of errors in the terminal for my API. Looking through those errors, the jist of the problem seems to be to do with an ID either not being sent or received correctly. I'm not sure if this is the target document ID, or the user ID.

**Post any code you think might be relevant (one fenced block per file)**
EditSightingModal
```js
const handleSubmit = (e) => {
        // e === event
        e.preventDefault()

        console.log('the sighting to submit', sighting)
        updateSight(user, sighting)
```

api/sightings.js
```js
// PATCH
// API call to update an existing sighting
export const updateSight = (user, updatedSighting) => {
    console.log("user in updatedSighting:", user)
    console.log("Updated sighting:", updatedSighting)
    return axios({
        url: `${apiUrl}/sightings/${updatedSighting.id}`,
        method: "PATCH",
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { sighting: updatedSighting }
    })
}
```
App.js
```js
	{/* Sightings: CREATE route */}
	<Route
		path="/sightings/new"
		element={
			<RequireAuth user={user}>
				<CreateSighting msgAlert={msgAlert} user={user} />
			</RequireAuth>}
	/>
	{/* Sightings: INDEX route */}
	<Route
		path="/sightings"
		element={<IndexSightings msgAlert={msgAlert} user={user} />}
	/>
	{/* Sightings: SHOW route */}
	<Route
		path="/sightings/:id"
		element={<ShowSighting msgAlert={msgAlert} user={user} />}
	/>
```

**What is your best guess as to the source of the problem?**
It's an ID, I'm near 100% sure, with terminal errors like

```
messageFormat: undefined,
  stringValue: '"undefined"',
  kind: 'ObjectId',
  value: 'undefined',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
```
It's throwing errors everywhere, but I think maybe it's an authorization problem, given that I'm getting the most detailed errors from middleware\authenticate, and that whenever I hit this error, I'm also logged out.

**What things have you already tried to solve the problem?**
I've reexamined all the variables and put console logs every which way to try and isolate the problem. I've verified the routes passing user info. I went from writing this edit component myself to straight copying and modifying the template to try and get it to go, and no luck.

**Additional context**

**Paste a link to your repository here**
https://github.com/NikPurvis/Bird-client/tree/nikki

**Comment by cory-yonomi** [comment]
Do you have it working through Postman? I'm wondering if the authorization string shouldn't start with "Bearer Token" vs. just token. That last error makes me wonder if passing the user into the function isn't working as intended, I'd recommend console.logging the token right before it's supposed to go into the axios call

**Comment by NikPurvis** [comment]
I did have updates working through postman, but for this specific one, it's sure not.

Okay, so I just made a new entry through Postman, and confirmed it's showing up client-side. Then I was able to use Postman to edit that entry, confirmed that edit was showing up client-side. Tried then, client-side, to edit the same entry, signed in as the same user, and no love.

I also just noticed that the patch request, in terminal, is logging PATCH /sightings/undefined.

I wanted to toss all that out to get brains turning. I'm going to try and console log info before the fetch, I'll update with what I get from that.

**Comment by NikPurvis** [comment]
I've got the info it's passing to the API call (I THINK -- I'm pretty sure, but I'm confusing myself a little bit at this point, I admit), and it looks like I'd expect:

![image](https://user-images.githubusercontent.com/98634026/162038564-26728884-3490-4a75-bf08-e871e3ea3042.png)

![image](https://user-images.githubusercontent.com/98634026/162038856-c0001aaa-8b62-44ed-b557-c7aefc111254.png)

But yeah, still throwing the error in middleware\authenticate, but also we're routing to PATCH/sightings/undefined.

**Comment by tkolsrud** [comment]
exporting the method required changing parameter to `._id`

**Comment by NikPurvis** [comment]
Got everything going now, thank you, guys!
