### ISSUE TITLE
Issue with calling api for a search index route

### ISSUE THREAD

**Issue by clds84** [sei-ec-remote/team-project-issues#28]
**Describe the bug**
_A clear and concise description of what the bug is._

It's not a bug but rather logic/syntax issues in understanding how to create a search index route in react

**What is the problem you are trying to solve?**
We want to call the api and display an index of results based on values from two form.control "items" in react

**Expected behavior**
_A clear and concise description of what you expected to happen._

We expect to create a value for each form.control by typing a value, and after we hit search we expect the api to be called and for an index of results to show based on what was typed. 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

We're not there yet because we're not sure what type of logic/syntax to use. Is it similar to a create route, to a show route, etc? Is it a mix? 

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/katherine-kania/team-mack-client

**Comment by DoireannJane** [comment]
Hey Cristian! Was this resolved?
