### ISSUE TITLE
Getting page to show personal items

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/team-project-issues#3]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
trying to get a page to show the items of only the user, can't figure out how to get in id for the items to do this

**Expected behavior**
_A clear and concise description of what you expected to happen._
page to show the items of only the user

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
not having an id to make it only show the wanted items

**What things have you already tried to solve the problem?**
tried using a this.props values kept getting errors

**Additional context**

**Paste a link to your repository here**
https://github.com/Nash4star/GytShop-Client/tree/main

**Comment by tkolsrud** [comment]
If i understand correctly, the id you're talking about is the user id? If that's the case it i will be stored in the session cookie. So you once someone's signed in you're going to use that destructuring code to isolate the `currentUser.id` (or something along those lines) and then fine any items whose "owner" match that

**Comment by tkolsrud** [comment]
Does the schema for the items have some kind of owner key?

**Comment by Nash4star** [comment]
the schema doesnt have an owner key per say but it does have a owner listed on it

**Comment by Nash4star** [comment]
we are using tokens for our users

**Comment by Nash4star** [comment]
wait i think i figured it out haha

**Comment by tkolsrud** [comment]
nice! if you did, post the solution here and then close the issue*
