### ISSUE TITLE
Git  discrepancies issues

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/team-project-issues#32]
**Describe the bug**
_A clear and concise description of what the bug is._
having issues with git which is saying i have discrepancies that make it so i cant push or pull the code

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by tkolsrud** [comment]
drop a screenshot of the error in here

**Comment by Nash4star** [comment]
![Screen Shot 2022-04-06 at 4 03 38 PM](https://user-images.githubusercontent.com/99209265/162061365-2670aaae-c035-4c12-8ebd-2982b04bf33d.png)

**Comment by Nash4star** [comment]
![Screen Shot 2022-04-06 at 4 04 27 PM](https://user-images.githubusercontent.com/99209265/162061461-84bc0190-59df-45a6-90db-a31f4e76d37e.png)
