### ISSUE TITLE
Cannot hide button based on a conditional

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/team-project-issues#33]
**Describe the bug**
_A clear and concise description of what the bug is._

We cannot hide the button 'add to favorites' when the product is already a favorite (to avoid it becoming added twice)

**What is the problem you are trying to solve?**

We are trying to have a promise chain set the value of a hook 'hidden' but it is not setting it..

**Expected behavior**
_A clear and concise description of what you expected to happen._

'add to favorites' button to be hidden

**What is the actual behavior?**
_A clear and concise description of what actually happened._

set state not changing after comparing the showproduct to all the products in the favorites array to see if any are matching and if so hide the 'add to favorites' button

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

set state is not working.. and maybe something with the promise chain?

**What things have you already tried to solve the problem?**

Narrowed the problem down to know it is not JSX. Tried not using a react hook and just a global variable

**Additional context**

It would be nice if Liam and I could get help before end of day :)

We have been working on this bug for too long..

**Paste a link to your repository here**

**Comment by tkolsrud** [comment]
Is this issue still unresolved?
