### ISSUE TITLE
Delete item from cart does not update React but removes from db

### ISSUE THREAD

**Issue by jfw2855** [sei-ec-remote/team-project-issues#34]
**Describe the bug**
_A clear and concise description of what the bug is._

Once I click on the delete button to remove an item from the cart, it will still have the item display on the page. Once I leave the Cart Showpage and return back, it will then not show the item.

**What is the problem you are trying to solve?**

Trying to have the item remove while still on the cart show page

**Expected behavior**
_A clear and concise description of what you expected to happen._

To display the remaining items in the cart

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Displays all items in cart (even removed)

**Post any code you think might be relevant (one fenced block per file)**
```js
export default function Cart(props) {

    const styleObj = {
        fontSize: 20,
        color: "#4a54f1",
        textAlign: "center",
        paddingTop: "100px",
    }
    const navigate = useNavigate()
    const [cart,setCart] = useState(null)
    const [itemsArr,setItemsArr] = useState([])
    const { user,msgAlert} = props
    console.log('this is user',user._id)
    useEffect(() => {
        viewCart(user)
            .then(res => {
                setCart(res.data.cart.items)
                
            })
            .then(()=> {
                console.log('this is cart',cart)
            })
            .then(() =>
                msgAlert({
                    heading: 'Success!',
                    message: `recipe show page`,
                    variant: 'success',
                }))
            .catch(()=> {
                msgAlert({
                    heading: 'Oh No!',
                    message: 'Issue with showing recipe',
                    variant: 'danger',
                })})
    }, [])

    if (!cart) {
        return <p>loading...</p>
    } 




    const handleDelete = (e,itemId) => {
        //e === event
        e.preventDefault()

        removeItem(user,itemId)
            .then(() => {navigate('/cart/view')})
            .then(() =>
            msgAlert({
                heading: 'Success!',
                message: 'item removed',
                variant: 'success',
            }))
            // if there is an error, we'll send an error message
            .catch(() =>
                msgAlert({
                    heading: 'Oh No!',
                    message: 'issue with removing item',
                    variant: 'danger',
                }))
    }

```

**What is your best guess as to the source of the problem?**

Not too sure. Maybe the depnd arr?

**What things have you already tried to solve the problem?**

I tried adding the navigate section in the promise chain to redirect back to the show cart page, but still the same issue

**Additional context**

**Paste a link to your repository here**
https://github.com/jfw2855/Grocery-Client

**Comment by cory-yonomi** [comment]
You'll want to add whichever data you're changing to the dependency array so that the useEffect is triggered again on that data  changing.

**Comment by jfw2855** [comment]
```js
    useEffect(() => {
        viewCart(user)
            .then(res => {
                setCart(res.data.cart.items)
                
            })
            .then(()=> {
                console.log('this is cart',cart)
            })
            .then(() =>
                msgAlert({
                    heading: 'Success!',
                    message: `recipe show page`,
                    variant: 'success',
                }))
            .catch(()=> {
                msgAlert({
                    heading: 'Oh No!',
                    message: 'Issue with showing recipe',
                    variant: 'danger',
                })})
    }, [cart])
```



Adding cart to the DA does remove the item from the cart show page, but it's now spamming the console.

**Comment by timmshinbone** [comment]
You absolutely DO NOT want to put the `cart` in the useEffect dependency array that updates the `cart`, this triggers the useEffect endlessly.

**Comment by timmshinbone** [comment]
Remember how we pseudo refreshed the page when we did the pets client app. You can use multiple useEffects that do different things, and have different dependency arrays, both useEffects will cause the component to re-render. So, one useEffect does cart actions and does NOT have `cart` in its dependency array(DA), a second useEffect that is just for refreshes can be used for that, and CAN have the `cart` in that DA, as long as it never affects the cart

**Comment by timmshinbone** [comment]
Sorry, my last comment could have been better written(forgive my antibiotics brain), but look at the Pet Show component [HERE](https://git.generalassemb.ly/sei-ec-remote/pets-client/blob/main/src/components/pets/ShowPet.js), see the state hook `updated` was set up as a trigger, and placed in the initial useEffect DA, so that whenever the `updated` piece of state is changed the useEffect is called. Find a way to implement something similar, all it takes is changing a value from `true` to `false` whenever something happens, so you can trigger another API call

**Comment by jfw2855** [comment]
Solution to issue

useEffect code block
```js
    const [updated, setUpdated] = useState(false)
    useEffect(() => {
        viewCart(user)
            .then(res => {
                setCart(res.data.cart.items)
                
            })
            .then(()=> {
                setUpdated(false)
                console.log('this is cart',cart)
            })
            .then(() =>
                msgAlert({
                    heading: 'Success!',
                    message: `recipe show page`,
                    variant: 'success',
                }))
            .catch(()=> {
                msgAlert({
                    heading: 'Oh No!',
                    message: 'Issue with showing recipe',
                    variant: 'danger',
                })})
    }, [updated])
```


handleDelete code block
```js
    const handleDelete = (e,itemId) => {
        //e === event
        e.preventDefault()

        removeItem(user,itemId)
            .then(() => setUpdated(true))
            .then(() =>
            msgAlert({
                heading: 'Success!',
                message: 'item removed',
                variant: 'success',
            }))
            // if there is an error, we'll send an error message
            .catch(() =>
                msgAlert({
                    heading: 'Oh No!',
                    message: 'issue with removing item',
                    variant: 'danger',
                }))
    }
```

As Timm & Corey suggested (Thanks for the help!), we needed to put a variable in the da that would not continually fire the useEffect. I added the updated state variable which is set to false upon loading the page (in useEffect). When a user triggers the delete button, the setUpdated will set to true which will fire the useEffect to reload the updated cart info from the db then will reset to false to prevent the useEffect to get retriggered.
