### ISSUE TITLE
having several problems with my edit and create

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/team-project-issues#35]
**Describe the bug**
_A clear and concise description of what the bug is._
my edit modal is popping up unexpectedly and my edit form is holding the changes to my values but show page is not

**What is the problem you are trying to solve?**
trying to get my edit modal to display when needed and to get my show page to hold updated changes

**Expected behavior**
_A clear and concise description of what you expected to happen._
open the create and make an object, then be able to edit the object and see those changes reflected in my show page

**What is the actual behavior?**
_A clear and concise description of what actually happened._
on submitting my form for create, I get the post request in terminal so it is creating, but it opens my edit modal which I then have to exit out of and don't really know what I'm doing to set the modal to open to get it to open in the first place. also when trying to edit a created object, it shows my updates only in the modal and doesn't reflect the changes in show page

**Post any code you think might be relevant (one fenced block per file)**
```js
return (
        <>
            <h5> Show Favorites</h5>
            <div style={cardContainerLayout}>
                {favorite.Jsx}
                <Button onClick={() => destroyFav()}variant="danger">
                    Delete
                </Button>
                <Button onClick={() => setModalOpen(true)} className="m-2" variant="warning">
                    Edit
                </Button>
                <EditFave 
                favorite={favorite}
                show={modalOpen}
                user={user}
                msgAlert={msgAlert}
                triggerRefresh={() => setUpdated(prev => !prev)}
                updateFave={updateFave}
                handleClose={() => setModalOpen(false)}
            />
            </div>
            
        </>
    )

```

```js
return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton></Modal.Header>
            <Modal.Body>
                <FavoriteForm 
                    favorite={favorite}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Edit favorite!"
                />
            </Modal.Body>
        </Modal>
    )
```

**What is your best guess as to the source of the problem?**
I believe the problem lies in how I'm calling my edit modal in the show page. I think that I'm having a problem with the updated value in show that is preventing me from seeing my changes

**What things have you already tried to solve the problem?**
talking to my team members and fiddling around with the placement of my modal component and trying to mess with the updated value in my edit component 

**Additional context**

**Paste a link to your repository here**
https://github.com/jscodeguy/Bird-client

**Comment by cory-yonomi** [comment]
Can you show the whole component for the show/edit?

**Comment by timmshinbone** [comment]
Is this resolved?

**Comment by cory-yonomi** [comment]
It is not. Trying to figure out why an axios call isn't hitting the backend at all for the Patch route.

**Comment by cory-yonomi** [comment]
Closing this! Found that JSX was being sent instead of JSON, implemented quick solution of manipulating data being sent.
