### ISSUE TITLE
having a bug with our favorites and reviews

### ISSUE THREAD

**Issue by oliviawilcox1** [sei-ec-remote/team-project-issues#36]
**Describe the bug**
_A clear and concise description of what the bug is._

We are getting an id is null message

**What is the problem you are trying to solve?**
To get the favorites to display

**Expected behavior**
_A clear and concise description of what you expected to happen._

The favorites should load on their own page
The reviews should show up on all pages

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Neither of those things are happening! We keep getting an error message about the id

**Post any code you think might be relevant (one fenced block per file)**
```js

const IndexFavorites = (props) => {
        const [favorites, setfavorites] = useState(null)
        const { user, msgAlert } = props
        useEffect(()=> {
            getAllFavorites()
                .then(res => {
                    console.log('this is the res', res)
                    setfavorites(res.data.favorites)
                })
                .then(()=> {
                    msgAlert({
                        heading:"Found Favorites",
                        variant: 'success'
                    })
                })
                .catch(() => 
                    msgAlert({
                        heading:"Uh Oh, something went wrong finding your favorites..",
                        variant: 'danger'
                    }))
            },[])
        if (!favorites) {
            return <p>loading...</p>
        } else if (favorites.length === 0) {
            return <p>no favorites yet, go add some</p>
        }

        let favoriteCards

        if (favorites.length > 0) {
            favoriteCards = favorites.map(favorite => (
                <div key={favorite._id} style={{ width:'300px'}}>
                    <Link to={`/products/${favorite.product._id}`} style={{overflowWrap: 'break-word'}} >{favorite.product.name}</Link>
                    <img src={`${favorite.product.image}`} style={{ height: '200px'}} class='img-thumbnail' />
                    <p>$ {favorite.product.price}</p>
                </div>
            ))
        }
```

**What is your best guess as to the source of the problem?**

Something in our index favorites page
**What things have you already tried to solve the problem?**

Ton of console logs, throughout the promos chain

**Additional context**

**Paste a link to your repository here**
https://github.com/oliviawilcox1/333-client

**Comment by tkolsrud** [comment]
can you show a console log for `favorites`?

**Comment by oliviawilcox1** [comment]
I responded via slack with an attached image!

**Comment by tkolsrud** [comment]
Alright so it looks it's logging as an array of objects, each with a parameter of `product` that's returning null for most of them -- so it could be that it's passing through correctly but there's nothing to display once it's in the client

**Comment by tkolsrud** [comment]
conditional needed a `return` statement and change `CSS` property
