### ISSUE TITLE
Having Trouble Accessing Object for Show Route

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/team-project-issues#37]
**Describe the bug**
_A clear and concise description of what the bug is._
Attempting to render the route from the api but it seems as though the path is out of order. Our routes in the front end is correct but the console is showing the complete reverse of our path

**What is the problem you are trying to solve?**
Having the path correctly hit and render the id of the search result
We have the route showing what it should, but we're still receiving a 500 internal server error, but it might still have something to do with the Axios call. 

**Expected behavior**
_A clear and concise description of what you expected to happen._
Show page for search result would render the card for the search results

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js
 useEffect(() => {
        getOneSearch(id)
        .then(res => {
        setShowResult(res.data.performers)
        console.log('this is the data', res.data.performers)
        })
```

**What is your best guess as to the source of the problem?**
Not sure whether its an error in the API for the route and maybe it would have something to do with that
If commented out, the useEffect function, there is no error message of localHost:8000/search/:id/undefined/undefined

**What things have you already tried to solve the problem?**
Progress have been made, please still check in

**Additional context**

**Paste a link to your repository here**
https://github.com/katherine-kania/team-mack-client
https://github.com/katherine-kania/team-mack-api
<img width="2240" alt="Screen Shot 2022-04-07 at 11 10 17 AM" src="https://user-images.githubusercontent.com/98559337/162232059-4f0fb162-c2ea-4632-b8b5-acfa2c14b434.png">

**Comment by timmshinbone** [comment]
Share the api function `getOneSearch` here, and in a separate code block, show me in react where you're getting the `id` that you passed to `getOneSearch` in your useEffect

**Comment by thefrostyausty** [comment]
**api function**
`export const getOneSearch = (type, name, id) => {
    return axios (`${apiUrl}/search/${type}/${name}/${id}`)
}`
_**We were originally looking at show pets which just passed the id in the getOnePet, and then realized that our 500 error in the console had a path that was messed up because of only passing the id, when for our case, we have three params. So we changed it to have three arguments in getOneSearch, to be type, name, and ID, and we we're successfully able to have a show route with an object specific to a particular ID. This is a new problem now: we tried digging into this object and using {showResult[0].name} in the card.text tag, and it actually worked a few times, but now all of a sudden we're getting an error that says cannot read properterties of null (reading '0'). All we literally did that ended up giving us an error was move {showResult[0].name}  from card.text to card.header. It was working without having any erorrs until then, and now we can't escape this error. Not sure if the logic is off, but it seems it wouldn't be if it did in fact work at one point. We tried resetting client and api and running npm start again to no avail.**_
**id code block**
`const SearchShow = (props) => {
    const { type, name, id } = useParams()
    const {user, msgAlert, searchResults } = props
    const [showResult, setShowResult] = useState(null)
    
    useEffect(() => {
        getOneSearch(type, name, id)
        .then(res => {
        console.log(res.data.performers)
        setShowResult(res.data.performers)
        

        }
        )
        // .catch(() => {
        //     msgAlert({
        //         heading: 'Oops!',
        //         message: searchShowFailure,
        //         variant: 'danger',
        //     })
        // })
    }, [])
    return (
        <>
        <Card style={{ width: '30%' }} className="m-2">
            
            <Card.Header>
            
            </Card.Header>
            <Card.Body>
                <Card.Text>
                    {showResult[0].name}
                    {/* <Card.Img variant="bottom" src={searchItem.image} /> */}
                </Card.Text>
            </Card.Body>
        </Card>
        <Link style={{ textDecoration: "none" }}
                to={`/search`}>
            <Button>
                Back to search
            </Button>
        </Link>
        </>
    )
}`

**Comment by thefrostyausty** [comment]
Update: if we set our state specifically like this,
`setShowResult(res.data.performers[0].name)`
we can write {showResult} in the card and it works, but if we set our state as
`setShowResult(res.data.performers)`
it doesn't work if we type {showResult[0].name} in the card

What's going on here?

**Comment by tkolsrud** [comment]
That's interesting, does logging `setShowResult` from the second scenario shed light on anything?

**Comment by thefrostyausty** [comment]
Do you mean console.logging (res.data.performers)?

**Comment by tkolsrud** [comment]
yeah the output of that function*

**Comment by thefrostyausty** [comment]
```js
console.log('this is the res.data.performers[0].name', showResult)
console.log('this` is the res.data.performers[0].name', res.data.performers[0].name)
```

first answer returns null
the second returns object
