### ISSUE TITLE
Implementing star rating

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/team-project-issues#38]
**Describe the bug**
_A clear and concise description of what the bug is._

I am trying to set up one ternary as a test to see if I can grab the value of the rating , but it doesn't seem to be recognizing the rating with my strict equality operator.

**What is the problem you are trying to solve?**

Trying to get my test ternary to return the correct value for now.

**Expected behavior**
_A clear and concise description of what you expected to happen._

I wanted the ternary to recognize the rating number and return the correct string. (ie. if rating number is 1, then the return should be `"rating is 1"`)

**What is the actual behavior?**
_A clear and concise description of what actually happened._

It is not meeting my condition at all.

**Post any code you think might be relevant (one fenced block per file)**
```js
 return (
        <>
            <Container className="fluid">
                <Card>
                    <Card.Header>
                        Visit to {visited.destination.name}
                    </Card.Header>
                    <Card.Body>
                        <Card.Text>
                            <small>Description: {visited.description}</small><br />
                            <small>rating: {visited.visitRating}</small><br />
                            {/* TESTING GHOST ICON RATING : ivy */}
                            {/* {visited.rating === 1 ? ghost : null }<br/> */}
                            {(visited.rating === 1) ? "rating is one" : "rating is not 1"  }<br/>
                            <small>Date from: <Moment format="MMMM do, YYYY">{visited.visitFromDate}</Moment></small><br/>
                            <small>Date to: <Moment format="MMMM do, YYYY">{visited.visitToDate}</Moment></small><br/>
                        </Card.Text>
                    </Card.Body>
                    <Card.Footer>
                        <Button onClick={() => setModalOpen(true)} className="m-2" variant="warning">
                            Edit Visited
                        </Button>
                        <Button onClick={() => removeTheVisited()} className="m-2" variant="danger">
                            Delete Visited
                        </Button>
                    </Card.Footer>
                </Card>
            </Container>

```

**What is your best guess as to the source of the problem?**

maybe the syntax, or it is not actually recognizing the rating number

**What things have you already tried to solve the problem?**

- rearranging and messing with my ternary 
- accept both string number and also a number
- console logging (but I couldn't figure out where I could even console log because I just get errors)
- google
- youtube

**Additional context**

So i found resources that didn't really relate so how I was currently trying to implement my rating system. The reason why I am trying to implement it this way with a set of chain ternary conditions is to keep is simple because the other route was to have a set up "stars" for the user to click on, but I had confusion of how I would connect the schema  and db to the "star" if I were to implement it by adding a whole new component and mapping through an array of the "stars", which also adds a lot more complexity that would cause a domino effect. I'm not sure if that makes sense, but any guidance as to wether I should keep going this route or swap to the other one would be appreciated !

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-client

**Comment by timmshinbone** [comment]
Is it called `visited.rating` or is it called `visited.visitRating`??
![image](https://user-images.githubusercontent.com/55121526/162238069-da552e83-c544-4f04-8b92-00feaaa14947.png)

**Comment by ivycle94** [comment]
Oh wow....how on earth did i totally miss that?! Thank you Timm!
