### ISSUE TITLE
Getting multiple promises in chain setup

### ISSUE THREAD

**Issue by kaiguy920** [sei-ec-remote/team-project-issues#4]
**Describe the bug**
_A clear and concise description of what the bug is._
We are trying to #1- create a visit & #2 - update the places object to take in the id of the visit. We are able to create the visit, but unable to reach the second part of the promise chain to access the place object.

**What is the problem you are trying to solve?**
proper promise chain syntax

**Expected behavior**
_A clear and concise description of what you expected to happen._
After creating the visit details, expecting to see the id of the visit to render into the array of the places model

**What is the actual behavior?**
_A clear and concise description of what actually happened._
The promise chain isn't accessing the second part of the chain at all, so no errors - just not seeing any data. No logs on places are rendering, so we aren't hitting it at all

**Post any code you think might be relevant (one fenced block per file)**
```js

router.post('/visit/:placeId', requireToken, removeBlanks, async (req, res, next) => {
    const visit = req.body.visit
    const visitId = req.params.id

    visit.destination = req.params.placeId
    req.body.visit.owner = req.user.id
    console.log('req.params.placeId', req.params.placeId);


    await Visit.create(visit)
        .then((visit) => {
            console.log('this was returned from create', visit)
            res.status(201).json({ visit: visit.toObject() })
        })
        .catch(next)

    Place.findById(req.params.placeId)
        .then(handle404)
        .then(place => {
            place.visitors.push(visitId)
            // return place.save()
        })

        .then(place => res.status(201).json({ place: place }))
        // catch errors and send to the handler
        .catch(next)


})

```

**What is your best guess as to the source of the problem?**

setup of the route

**What things have you already tried to solve the problem?**
We have all been researching/working through lunch to try different syntax

**Additional context**

**Paste a link to your repository here**
https://github.com/ivycle94/GhostBustr-api

**Comment by tkolsrud** [comment]
Currently it looks like `visitId` is set to `req.params.id` -- where is `req.params.id` coming from/does anything come up when you console log either that or the `visitId`?

**Comment by cory-yonomi** [comment]
The problem here is that the route moves on after it hits the first res.send(). If the second promise needs data from the first, you'll need to chain the two promises, so that one `.then()`s into the next. If they aren't dependent on each other, I'd recommend looking into `Promise.all()`. It's a built in method that takes an array of promises and gives you a single response with an array of all those reponses.

**Comment by kaiguy920** [comment]
When logging id:
![image](https://user-images.githubusercontent.com/98335552/161598747-683829c5-dde7-4606-949b-47871d1e3ec8.png)
it is properly filling in all other fields to the visit (userid, place id)

**Comment by kaiguy920** [comment]
The chain of events is dependent on each other. We need first for the visit to get created, and from that visit, it's id to be pushed into an array on the place.

**Comment by kaiguy920** [comment]
This is our place schema:
![image](https://user-images.githubusercontent.com/98335552/161599077-d5d4348f-b992-404d-901d-be1a0dd9322f.png)

**Comment by kaiguy920** [comment]
Visitors is set up as an array within the place

**Comment by tkolsrud** [comment]
Cory's right, you've got to put that `Place.findById` into the same promise chain bc it's probably exiting the function on `res.status`

**Comment by ivycle94** [comment]
This is our current code with our promises nest now:

```
router.post('/visit/:placeId', requireToken, removeBlanks, (req, res, next) => {

    const visit = req.body.visit
    const visitId = req.params.id

    visit.destination = req.params.placeId
    req.body.visit.owner = req.user.id
    console.log('req.params.placeId', req.params.placeId);

    Place.findById(req.params.placeId)
        .then(handle404)
        .then(place => {
            Visit.create(visit)
                .then((visit) => {
                    console.log('this was returned from create', visit)
                    res.status(201).json({ visit: visit.toObject() })
                    place.visitors.push(visit._id)

                })
            return place.save()

        })
})
```

**Comment by ivycle94** [comment]
So now we see the visit being created on postman, but when we check the show route for that visit it is empty. We can see the visit being updated but we don't actually know if it's being stored correctly because our array of visits is empty.
