### ISSUE TITLE
Using Local Font .woff file and setup

### ISSUE THREAD

**Issue by ladomino** [sei-ec-remote/team-project-issues#41]
**Describe the bug**
Unable to get a Local Font file to be used as a font family.

**What is the problem you are trying to solve?**
To see whether it is possible.  It was setup by a team member and the rest of the team is pulling it down and not seeing it working on our local machines.   It isn't clear to me that this is even possible.

**Expected behavior**
_A clear and concise description of what you expected to happen._
For a new font to be used and shown.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
No changes.  However I think a group member downloaded the file onto their machine which is why it
works there.

**Post any code you think might be relevant (one fenced block per file)**
```js
@font-face {
  font-family: "Cantique";
  src: url(./fonts/Cantique-Normal.woff) format("woff"),
      url(./fonts/Cantique-Normal.woff2) format("woff2"),
}
```

**What is your best guess as to the source of the problem?**
I'm not sure you can do this without having a dedicated server.  Using chrome I can see that the link is not meaningful.

**What things have you already tried to solve the problem?**
Pretty much everything but it's a local file.   I just want to know if it can be done.

**Additional context**

**Paste a link to your [repository]
https://github.com/ladomino/GhostBustr-client

**Comment by timmshinbone** [comment]
When you pull this onto your machine, is the file `./fonts/Cantique-Normal.woff` showing up in the fonts folder?

**Comment by ladomino** [comment]
Yes that directory structure and that file exists.   All the files and directory structure are the same.   The only difference between the machine that is working (Stevie's) is she downloaded the actual Font to her machine and we pulled from github.

**Comment by DoireannJane** [comment]
Awesome! So you can all install the font locally and just make sure to include that in your readMe. Let us know how it goes!
