### ISSUE TITLE
Styling of a card to get it so the image is on the left side and the text is on the right

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/team-project-issues#44]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
trying to get it so that i have the cards set up so that the image is on the left side of the card and the text is on the right side and also have the images not be squished 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by DoireannJane** [comment]
What have you tried so far?
