### ISSUE TITLE
Getting Error on Profile_Routes

### ISSUE THREAD

**Issue by bostonbachexchange** [sei-ec-remote/team-project-issues#46]
**Describe the bug**
_A clear and concise description of what the bug is._
Cannot delete individual profile pages.

**What is the problem you are trying to solve?**
When hitting the delete route on postman, 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._
     Terminal is showing:

 15:32:46 GMT-0400 (Eastern Daylight Time):
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/app/routes/profile_routes.js:80:46

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
Create route is similar to Delete route. Should be nearly the same.

**What things have you already tried to solve the problem?**
Refered to toys from pets api as subdoc route example for profiles. Checked to see if there are differences from create route.

**Additional context**

```
router.delete('/profiles/:userId/:profileId', requireToken, (req, res, next) => {
    // get the toy and the pet ids saved to variables
    const userId = req.params.userId
    const profileId = req.params.profileId
    // then we find the pet
    User.findById(userId)
        // handle a 404
        .then(handle404)
        // do stuff with the toy(in this case, delete it)
        .then(user => {
            // we can get the subdoc the same way as update
            const theProfile = user.profile._id(profileId)
            // require that the user deleting this toy is the user's owner
            requireOwnership(req, user)
            // call remove on the subdoc
            theProfile.remove()

            // return the saved user
            return user.save()
        })
        // send 204 no content status
        .then(() => res.sendStatus(204))
        // handle errors
        .catch(next)
`})`
```

**Paste a link to your repository here**
https://github.com/alysvolatile/Scrumptious-Bunch-API

**Comment by mattkeane-ga** [comment]
Are you seeing any errors in your back end terminal? What happens when you try logging `theProfile`?

**Comment by mattkeane-ga** [comment]
I'm a little bit puzzled by the `TypeError: Cannot read properties of undefined (reading 'id')` error. I don't see you trying to read an `id` property on anything. Is it coming from one of the middleware functions? Maybe it's coming from `requireOwnership`.

**Comment by timmshinbone** [comment]
This line is giving you the issue: `const theProfile = user.profile._id(profileId)`

Share your schema here for the user and the profile.

**Comment by bostonbachexchange** [comment]
We got around the profile id is not a function, but now we are getting stuck on require ownership, when we comment out that function, everything else is working fine
https://github.com/alysvolatile/Scrumptious-Bunch-API/blob/main/project_3_api/app/routes/profile_routes.js

**Comment by bostonbachexchange** [comment]
Thank you!!! Here is the working code

router.delete('/profile', requireToken, (req, res, next) => {
    // we are getting the profile of associated user and removing it, a user can only ever access their profile with this pattern (require ownership is redundant)
    // get the user and the profile ids saved to variables
    const userId = req.user.id
    User.findById(userId)
        // returns user object of user that made the request
        .then(handle404)
        // do stuff with the toy(in this case, delete it)
        .then(user => {
            // we know that this is the user object from find by id
            console.log('here is the user: \n', user)
            console.log('here is the profile: \n', user.profile)

            // we can get the subdoc the same way as update
             const theProfile = user.profile
            // call remove on the subdoc
            theProfile.remove()
            console.log('user without profile?', user)
            // return the saved user
            return user.save()
        })
        // send 204 no content status
        .then(() => res.sendStatus(204))
        // handle errors
        .catch(next)
})
