### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by jadenRuplal** [sei-ec-remote/team-project-issues#47]
**Describe the bug**
_A clear and concise description of what the bug is._
We are trying to test user signup in postman but we end up with a 500 internal server error.

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._
A new user is created

**What is the actual behavior?**
_A clear and concise description of what actually happened._
500 internal server error

**Post any code you think might be relevant (one fenced block per file)**
```js
{
    "credentials": {
      "email": "an@example.email",
      "password": "1",
      "password_confirmation": "1"
    }
  }
```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/christian-the-brewer/poke_store_api

**Comment by kestler01** [comment]
what is the error you get in your api terminal window ?

**Comment by jadenRuplal** [comment]
It was a duplicate email, we fixed it
