### ISSUE TITLE
Hooking up API

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/team-project-issues#48]
**Describe the bug**
_A clear and concise description of what the bug is._
I am trying to get my lastFM API to link up on the backend side.

**What is the problem you are trying to solve?**
Hooking up API on the backend side.

**Expected behavior**
_A clear and concise description of what you expected to happen._
The API should be hooking up. I am returning some data in the terminal, but not sure what that data is.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Returning some data I don't understand.

**Post any code you think might be relevant (one fenced block per file)**
```js
const getLastFmSong = async () => {
	data = await axios.get("https://ws.audioscrobbler.com/2.0/?method=track.search&track=anthem&api_key=d8e8bce9ba4ee2c4e9813f3ccb16ed83&format=json&limit=30")
	console.log(data.data)


    // return axios({
    //     method: "GET",
    //     url: "https://ws.audioscrobbler.com/2.0/?method=track.search&track=anthem&api_key=d8e8bce9ba4ee2c4e9813f3ccb16ed83&format=json&limit=30"
    // })
}
getLastFmSong()



// SINGLE SONG SEARCH
router.get("/songs", (req, res, next) => {
	// getLastFmSong()
	// 	.then((res) => console.log(res))
		getLastFmSong()
})

```

**What is your best guess as to the source of the problem?**
I am hooking up the API wrong.

**What things have you already tried to solve the problem?**
Working with classmates and looking up solutions online.

**Additional context**

**Paste a link to your repository here**
https://github.com/mayday91/P3Mongo-Express

**Comment by timmshinbone** [comment]
Share a screenshot of your console.log that runs when you call the API.

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-04 at 9 44 42 AM](https://user-images.githubusercontent.com/103372967/182862417-80605051-4d11-49d6-951f-cdcc45b5976f.png)

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-04 at 9 45 12 AM](https://user-images.githubusercontent.com/103372967/182862545-972488e2-a8bf-4adb-a2cf-6dd43d89dfcd.png)

**Comment by timmshinbone** [comment]
Have you tried drilling down into the data? Looks like you got 620,000+ results, and there's an array in there called `track` inside the `trackmatches` object, what happens when you run this: `console.log(data.data.trackmatches.track)`

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-04 at 9 54 08 AM](https://user-images.githubusercontent.com/103372967/182864532-071cbace-36e8-4faa-b00a-449feffed99b.png)

**Comment by timmshinbone** [comment]
ok get rid of track and run it again

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-04 at 9 55 28 AM](https://user-images.githubusercontent.com/103372967/182864838-556e6ea0-c782-4bf9-a8ff-b6c7fd854d96.png)

**Comment by kestler01** [comment]
resolved
