### ISSUE TITLE
API crashing on my device but not others

### ISSUE THREAD

**Issue by dangdo85** [sei-ec-remote/team-project-issues#51]
**Describe the bug**
_A clear and concise description of what the bug is._
App was working before, but is crashing after lunch without any changes (on Dang's comp)
App works on other members' comp after pulling the repo.

**What is the problem you are trying to solve?**
back-end crashing on start

**Expected behavior**
_A clear and concise description of what you expected to happen._
back-end not crashing

**What is the actual behavior?**
_A clear and concise description of what actually happened._
back-end crashing

**Post any code you think might be relevant (one fenced block per file)**
```js
/Users/dangdo/sei/projects/Project-3/project-3-mongoose-express/node_modules/mongoose/lib/connection.js:797
  const serverSelectionError = new ServerSelectionError();
                               ^
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at Connection.openUri (/Users/dangdo/sei/projects/Project-3/project-3-mongoose-express/node_modules/mongoose/lib/connection.js:797:32)

```

**What is your best guess as to the source of the problem?**
no idea

**What things have you already tried to solve the problem?**
restarting terminal

**Additional context**

**Paste a link to your repository here**
https://github.com/dangdo85/project-3-react
https://github.com/dangdo85/project-3-mongoose-express

**Comment by aishcann** [comment]
do you have the same code base as the rest of your group mates?

**Comment by dangdo85** [comment]
yes

**Comment by kestler01** [comment]
resolved with replacing localHost reference with 127.0.0.1
