### ISSUE TITLE
Cannot pull backend props

### ISSUE THREAD

**Issue by Lyndonna18** [sei-ec-remote/team-project-issues#52]
**Describe the bug**
_A clear and concise description of what the bug is._

The client is connected to the backend but the props are not showing 

**What is the problem you are trying to solve?**

Cannot map through the seeded data

**Expected behavior**
_A clear and concise description of what you expected to happen._

 I console.logged the props and I should be seeing the res.data but it shows an empty prototype array

**What is the actual behavior?**
_A clear and concise description of what actually happened._
 In the console, I just see the prototype object and no data

**Post any code you think might be relevant (one fenced block per file)**
```js
const BlogIndex = (props) => {
    console.log("watermelon sugar", props)
    const [blogs, setBlogs] = useState(null)
    const [error, setError] = useState(false)
    const { msgAlert } = props
    useEffect(() => {
        getAllBlogs()
            .then(res => setBlogs(res.data.blogs))
            .catch(err => {
                msgAlert({
                    heading: 'Error Getting Pets',
                    message: messages.getBlogsFailure,
                    variant: 'danger',
                })
                setError(true)
        })
    }, [])
```

**What is your best guess as to the source of the problem?**
 I don't know exactly how the backend is connected to the client except through the api Config which looks like its connected correctly 

**What things have you already tried to solve the problem?**
tried console logging the props and looking at the apiConfig file.

**Additional context**

**Paste a link to your repository here**

**Comment by aishcann** [comment]
resolved
