### ISSUE TITLE
404 in postman 

### ISSUE THREAD

**Issue by LarryMays92** [sei-ec-remote/team-project-issues#53]
**Describe the bug**
_A clear and concise description of what the bug is._

404 error in postman 

**What is the problem you are trying to solve?**
fet rid of error messge 

**Expected behavior**
_A clear and concise description of what you expected to happen._

route to work 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

route not successful in postman

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

idk

**What things have you already tried to solve the problem?**

checking routes 

**Additional context**

**Paste a link to your repository here**
https://github.com/nickesparza/ga-project-3-api

**Comment by aishcann** [comment]
will message you on slack

**Comment by aishcann** [comment]
type error. resolved.
