### ISSUE TITLE
cant resolve an error message 

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/team-project-issues#54]
**Describe the bug**
we need help routing for our book index 

**What is the problem you are trying to solve?**
were trying to get our api to show up for out index

 

**Expected behavior**
_A clear and concise description of what you expected to happen._

click on home button and have the index show up

**What is the actual behavior?**
_A clear and concise description of what actually happened._

put localhost3000/books in terminal and we get an error message 

**Post any code you think might be relevant (one fenced block per file)**
```js

 const bookCards = books.map(book => (
        <Card style={{ width: '30%', margin: 5}} key={ book.id }>
            <Card.Header>{ book.fullTitle }</Card.Header>
            <Card.Body>
                <Card.Text>
                    <Link to={`/books/${book.id}`}>View { book.name }</Link>
                </Card.Text>
            </Card.Body>
        </Card>
    ))
    // const googleBookCards = books.map(book => (
    //     <Card style={{ width: '30%', margin: 5}} key={ book.id }>
    //         <Card.Header>{ book.fullTitle }</Card.Header>
    //         <Card.Body>
    //             <Card.Text>
    //                 <Link to={`/books/${book.id}`}>View { book.name }</Link>
    //             </Card.Text>
    //         </Card.Body>
    //     </Card>
    // ))
```

**What is your best guess as to the source of the problem?**

not grabbing the api correctly 

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by kestler01** [comment]
missing .env file
