### ISSUE TITLE
Submit func for my create button doesn't work

### ISSUE THREAD

**Issue by Lyndonna18** [sei-ec-remote/team-project-issues#55]
**Describe the bug**
_A clear and concise description of what the bug is._
The boilerplate for the post method for the onclick is compiling an error

**What is the problem you are trying to solve?**
I am trying to submit new data with a create js route

**Expected behavior**
_A clear and concise description of what you expected to happen._
 I expected the code to allow me to click submit on a new blog post and create a new post.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
 I'm getting a TypeError instead

**Post any code you think might be relevant (one fenced block per file)**
```js
// CREATE/POST
// need an api call that accepts a token
export const createBlog = (user, newBlog) => {
    // console.log('createBlog in api was hit')
    // console.log('this is user', user)
    // console.log('this is the blog', newBlog)
    return axios({
        url: apiUrl + '/blogs',
        method: 'POST',
        headers: {
            Authorization: `Token token=${user.token}`,
        },
        data: { blog: newBlog },
    })
```

**What is your best guess as to the source of the problem?**

NO Idea lol

**What things have you already tried to solve the problem?**
 This was copy and pasted from the pets react app

**Additional context**

**Paste a link to your repository here**

**Comment by Lyndonna18** [comment]
![Screen Shot 2022-08-04 at 3 58 37 PM](https://user-images.githubusercontent.com/86806118/182941514-c88697de-331f-4659-9a84-7e4f8823331b.jpg)

**Comment by aishcann** [comment]
when you ran `console.log(user)` what did you see?

**Comment by aishcann** [comment]
resolved - need to pass user props to right component
