### ISSUE TITLE
still having index issues 

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/team-project-issues#58]
**Describe the bug**
_A clear and concise description of what the bug is._

when we try to grab our index we get errors 
ERROR in ./src/components/books/ShowBook.js 15:0-58
Module not found: Error: Can't resolve '../comments/NewCommentModal' in '/Users/erisha/sei_icepops/projects/project3/project-3-client/src/components/books'
ERROR in ./src/components/books/ShowBook.js 16:0-50
Module not found: Error: Can't resolve '../Comments/ShowComment' in '/Users/erisha/sei_icepops/projects/project3/project-3-client/src/components/books'
ERROR
[eslint]
src/components/books/ShowBook.js
  Line 151:18:  'commentCards' is not defined  no-undef
Search for the keywords to learn more about each error.

**What is the problem you are trying to solve?**
get our index to show up

**Expected behavior**
_A clear and concise description of what you expected to happen._

have the index show up when we type localhost3000/books

**What is the actual behavior?**
_A clear and concise description of what actually happened._

the error message 

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

not grabbing api correctly 

**What things have you already tried to solve the problem?**

all the things i know 

**Additional context**

**Paste a link to your repository here**

**Comment by kestler01** [comment]
Good morning ! wanted to check in about the status of this issue, still active ?

**Comment by nrissman** [comment]
no it was a super bizarre bug, maybe just on erishas computer, we copied all my code over to hers and it still was acting funky so we switched up the plan and went bck to old code and edited from there.
