### ISSUE TITLE
Fixing the delete route

### ISSUE THREAD

**Issue by Nash4star** [sei-ec-remote/team-project-issues#6]
**Describe the bug**
_A clear and concise description of what the bug is._
the delete route thats been created deletes the cart(an array) but also sets it to null and causes the cart to become non functional 

**What is the problem you are trying to solve?**
We are trying to have a delete function that will clear our car but also not delete the cart all together and causing the whole thing to stop working

**Expected behavior**
_A clear and concise description of what you expected to happen._
to clear all the items from the cart and have the array t go back to being an empty array again

**What is the actual behavior?**
_A clear and concise description of what actually happened._
it deletes the array making the cart unable to be used again

**Post any code you think might be relevant (one fenced block per file)**
```js
router.delete('/orders/:ownerId', requireToken, (req, res, next) => {
    const ownerid = req.params.ownerId

	Order.findOne({owner: ownerid})
		.then(handle404)
        
		.then((order) => {
			// Error if current user does not own the order
			let productsInCart = order.productsOrdered
            console.log('array', productsInCart)
			// Delete the order ONLY IF the above didn't error
            // productsInCart.splice(0, productsInCart.length)
            order.deleteMany(productsInCart)
            console.log('array', productsInCart)
		})
        
		// send back 204 and no content if the deletion succeeded
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})

```

**What is your best guess as to the source of the problem?**
i think it has to do with whats being deleted causing it to bug

**What things have you already tried to solve the problem?**
tryied using different ways of removing it and the ones ive tried either dont work or have the same issue

**Additional context**

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Look up the mongoose method `deleteMany` in the mongoose documentation, come back here and let me know what it says deleteMany does. 

Is it a subdocument method? Or is it a model method? 

Remember, you can also use array methods to carry out what you want to do since the productsInCart is an array.

**Comment by Nash4star** [comment]
So I tried using array methods and i cant seem to get it to work either, I had put deleteMany on just to test a new thing out its a model method from my understanding.

**Comment by timmshinbone** [comment]
Note that deleteMany removes ALL documents that match the first argument passed to it. So, what you were trying to delete was _not_ cartItems, but the orders that have those cart items.

![image](https://user-images.githubusercontent.com/55121526/161775282-a7f0e30e-c95b-402a-a122-6c05c691050e.png)
