### ISSUE TITLE
Lost on how to get favorites to work in backend

### ISSUE THREAD

**Issue by jlx012** [sei-ec-remote/team-project-issues#60]
**Describe the bug**
_A clear and concise description of what the bug is._
Confused

**What is the problem you are trying to solve?**
I am trying to create a router.post that creates a new Favorite schema with the books contents and user id

**Expected behavior**
_A clear and concise description of what you expected to happen._
creates a new Favorite schema with the books contents and user id

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Not exactly sure, It looks like it made something the first time but with only the book_id? now its the only thing that shows up everything I create a favorite regardless of req.body content

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by kestler01** [comment]
Good morning James, is this still an active issue ?

**Comment by jlx012** [comment]
Yes!

**Comment by nrissman** [comment]
Hey we are all working together today, and this is still an active issue, can you jump into rm.4
please?
