### ISSUE TITLE
Images not displaying on BookIndex card

### ISSUE THREAD

**Issue by erisha** [sei-ec-remote/team-project-issues#61]
**Describe the bug**
_A clear and concise description of what the bug is._

Images are showing up as broken thumbnails

**What is the problem you are trying to solve?**
To get images to be displayed on cards in book index instead of broken thumbnail

**Expected behavior**
_A clear and concise description of what you expected to happen._

image of book to show on book index card

**What is the actual behavior?**
_A clear and concise description of what actually happened._

broken thumbnail shows up

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

code may not be in the right place

**What things have you already tried to solve the problem?**

moved code around and tried it in different versions

**Additional context**

**Paste a link to your repository here**
https://github.com/eshalali/project-3-client.git

**Comment by kestler01** [comment]
how are we trying to display the images ? ex, are you using a a reference string ?

**Comment by erisha** [comment]
<Link to={`/books/`}>View { book.volumeInfo.smallThumbnail }</Link>

**Comment by kestler01** [comment]
and what is the value of smallThumbnail look like ?

**Comment by erisha** [comment]
James got it to work. Thank you
