### ISSUE TITLE
Question about ecommerce routing for past orders

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/team-project-issues#62]
**Describe the bug**
_A clear and concise description of what the bug is._
We are wondering how to do the routing for past and current orders. We are not sure if we should just have one set of cart routes, that are /carts/, where we can find all carts, and then filter out if the cart is active or not, or if we should have another set of routes at /orders/ where we just get the past unactive carts. If someone could jump into breakout room 6 with us we would appreciate it. 

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
API: https://github.com/christian-the-brewer/poke_store_api
CLIENT: https://github.com/christian-the-brewer/poke_store_client/tree/main

**Comment by kestler01** [comment]
ah, the architecture of you api is totally up to you. To bounce off your idea here with the 1 route only getting the active cart, I would add another route to only get inactive / past carts

**Comment by christian-the-brewer** [comment]
thank you for the advice, we will use separate routes for the past orders
