### ISSUE TITLE
Handling a push of data to frontend from backend

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/team-project-issues#64]
**Describe the bug**
_A clear and concise description of what the bug is._

Not a bug, just trying to wrap my head around the issue. So when the user does a song search: the frontend sends the search term to the back and the backend hits the API and then returns an object with a bunch of song back to the frontend. This works, however, it looks like in Pets, when a pet is requested, the frontend does a pull of the data. In my case the backend is pushing the data, so I trying to determine where and how to handle the information. Specifically, where/how to handle data to front, since it is not directly a pull ...

**What is the problem you are trying to solve?**
See above :)

**Expected behavior**
_A clear and concise description of what you expected to happen._

When a song is searched the term goes to the backend, API happens, then a object of all the songs goes to the front end for a display of all the song for adding to a cart or not.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
The search term goes to the back and an JSON is returned with a bunch of songs. There is no handling of the returned data yet.

**Post any code you think might be relevant (one fenced block per file)**
```
import React, { useState, Fragment } from 'react'
import { Link } from 'react-router-dom'
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import Form from 'react-bootstrap/Form';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import Offcanvas from 'react-bootstrap/Offcanvas';
import { songSearch } from '../../api/song.js'
import { useNavigate } from 'react-router-dom'



const SongSearch = (props) => {


    const [searchTerm,setSearchTerm] = useState('')

// searchTerm is the thing we pass in



        // handle changing state
    const handleInput = (e) => {
        e.preventDefault()
        setSearchTerm(e.target.value)

    }

    const doSongSearch = (e) => {
        e.preventDefault()

        console.log('searTerm:',searchTerm);

        songSearch(searchTerm).then().catch((error) => {
            // msgAlert({
            //     heading: 'Sign Up Failed with error: ' + error.message,
            //     message: messages.signUpFailure,
            //     variant: 'danger',
            })  
    }



    return (
        <Fragment>             
                <Form onSubmit={(e) => {doSongSearch(e)}} className="d-flex">

                        <Form.Label>Song Search</Form.Label>                
                        <Form.Control
                            onChange = {(e) => {handleInput(e)}}
                            type="search"
                            placeholder="Search"
                            className="me-2"
                            aria-label="Search"
                            value = {searchTerm}
                        />
                  <Button variant="outline-success" type="submit" >Search</Button>
                </Form>
        </Fragment>

    )
}



export default SongSearch

```

```

import { useState, useEffect, Fragment } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Container, Card, Button } from 'react-bootstrap'
// import LoadingScreen from '../shared/LoadingScreen'
// import { getOnePet, updatePet, removePet } from '../../api/pets'
// import messages from '../shared/AutoDismissAlert/messages'

const ShowSong = (props) => {
    const [song, setSong] = usestate('')

    // const { id } = useParams()
    const navigate = useNavigate()

    // prob need msgAlert here in future
    const { user } = props


return (

    <>
    <Container className="fluid">
        <Card>
            <Card.Header>{ song.name }</Card.Header>
            <Card.Body>
                <Card.Text>
                    <div><small>Song: {song.name}</small></div>
                    <div><small>Artist: { song.artist}</small></div>
                   <div><small> { song.imageUrl}</small></div>

                </Card.Text>
            </Card.Body>
            
        </Card>
    </Container>
    

    {/* ?????????
    <Container>
        {toyCards}  
    </Container> */}

</>


)


}
```

**What is your best guess as to the source of the problem?**
A conceptual understanding

**What things have you already tried to solve the problem?**
Can't handle the data 

**Additional context**

**Paste a link to your repository here**
https://github.com/mayday91/P3Mongo-Express/tree/routes   (the frontend)

**Comment by kestler01** [comment]
to start working with the data you're getting, you want to save it in the state, typically at a level above the search component - do this by passing the state' setter function down as props. 
From there you can have the component loop through the data and make an individual song component like the one you have written for each song in the state data

**Comment by Rando-cal** [comment]
I think I got it.

The function doing the passing the data can accept the data back... like so

 songSearch(searchTerm).then((res) => console.log('RES:!!!',res.data)).catch((error) => {
           

            })  

Yay!! Thank you
