### ISSUE TITLE
Route not working

### ISSUE THREAD

**Issue by danstacy1** [sei-ec-remote/team-project-issues#65]
**Describe the bug**
_A clear and concise description of what the bug is._
We cannot get one of our show routes to work. 

**What is the problem you are trying to solve?**

We believe we have the route set up correctly, but our console says the route does not exist. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

The route to work.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

It doesn't work.

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

Probably something in the code.

**What things have you already tried to solve the problem?**

We have checked our routes on both the front end and backend, as well as post man and they are all the same, but the route doesn't work. All other routes are working.

**Additional context**

**Paste a link to your repository here**
Backend:
https://github.com/tylly/project-3-mongoose-express.git

frontend:
https://github.com/tylly/project-3-react.git

**Comment by timmshinbone** [comment]
We need to see some code here to discern what's going on, please share the code blocks you think are causing the problems.

**Comment by danstacy1** [comment]
```js
// READ => SHOW Activity.js
export const getOneActivity = (user, id, activityId) => {
	console.log('the user in showActivity', user)
	console.log('the activity in showActivity', activityId)
    return axios(`${apiUrl}/activities/${id}/${activityId}`)
}
```

APP.js
```js
<Route
	path="/activities/:id/activityId"
	element={ <ShowActivity user={ user } msgAlert={ msgAlert } />}
/>
```

ActivityShow Route on backend
```js
// SHOW
// GET /examples/5a7db6c74d55bc51bdf39793
router.get('/activites/:id/:activityId', requireToken, (req, res, next) => {
	// req.params.id will be set based on the `:id` in the route
	Activity.findById(req.params.activityId)
		.then(handle404)
		// if `findById` is succesful, respond with 200 and "example" JSON
		.then((activity) => res.status(200).json({ activity: activity.toObject() }))
		// if an error occurs, pass it to the handler
		.catch(next)
})
```

**Comment by timmshinbone** [comment]
Show me the code in the show component where you're calling the `getOneActivity` function

**Comment by danstacy1** [comment]
```js
const ShowActivity = (props) => {
    const [activity, setActivity] = useState(null)
    const [editModalShow, setEditModalShow] = useState(false)
    const [updated, setUpdated] = useState(false)
const { id } = useParams()
    const navigate = useNavigate()
    // useNavigate returns a function
    // we can call that function to redirect the user wherever we want to

    const { user, msgAlert } = props
    console.log('user in props', user)
    // console.log('the activity in showActivity', activity)
    
    // destructuring to get the id value from our route parameters

    useEffect(() => {
        getOneActivity(id)
            .then(res => setActivity(res.data.activity))
            .catch(err => {                   
                msgAlert({
                    heading: 'Error getting activity',
                    message: messages.getActivityFailure,
                    variant: 'danger'
                })
                navigate('/destinations/:_id')
                //navigate back to the destinations page if there's an error fetching
            })
    }, [updated])
```

**Comment by timmshinbone** [comment]
Ok, that's the problem. How many parameters does your `getOneActivity` function expect? How many _arguments_ are you passing to it when you call it?

**Comment by danstacy1** [comment]
Ahhhhh, it should have a user and an activity id. Is that right?

**Comment by danstacy1** [comment]
Is that why it does not recognize the route?

**Comment by timmshinbone** [comment]
exactly, I'm going to jump into your breakout room and explain!

**Comment by timmshinbone** [comment]
Is this still an issue? If it is please update with a reply, if it isn't please add a brief note about what solved the problem and close it.

**Comment by danstacy1** [comment]
We realized that we had first to search the destination ID and then the activity ID to make the data display. Everything is resolved.
