### ISSUE TITLE
How to style modals

### ISSUE THREAD

**Issue by DRG104** [sei-ec-remote/team-project-issues#66]
**Describe the bug**
_A clear and concise description of what the bug is._
Having an issue trying to style modal. Tried to find associated CSS file, but couldn't so I'm using `style={{ }}` instead.

**What is the problem you are trying to solve?**
Trying to resize/style specific modals.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Styling a specific modal.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Can't seem to style or edit modals.

**Post any code you think might be relevant (one fenced block per file)**
```js
<EditBlogModal 
                user={user}
                blog={blog} 
                show={editModalShow} 
                updateBlog={updateBlog}
                msgAlert={msgAlert}
                triggerRefresh={() => setUpdated(prev => !prev)}
                handleClose={() => setEditModalShow(false)}
                style={{
                    overlay: {
                        width: '100%',
                        height: '100%',
                    }
                }}
            />
```
and

```
    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton />
            <Modal.Body style={{
                width: '100%',
            }}>
                <BlogForm 
                    blog={blog}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Update this Post"
                />
            </Modal.Body>
        </Modal>
    )
}
```

**What is your best guess as to the source of the problem?**
I'm not interacting with bootstrap properly, since modals are imported from `bootstrap-react`

**What things have you already tried to solve the problem?**
Tried applying `style= {{ }}` to both the `modal.js` and our `showDocument.js` where the modal is returned and called respectively, style has no affect.

**Additional context**
Modals are imported from `react-bootstrap`

**Paste a link to your repository here**
https://github.com/Zene09/project-3-team-8-client

**Comment by ejparnell** [comment]
@DRG104 With React boostrap you have to interact with it in a bit of a different way. Basically you will have to pass some props to the `Modal` component and then it will resize. [Here](https://react-bootstrap.github.io/components/modal/#optional-sizes) is the React Boostrap docs for modals and the optional sizing.

**Comment by DRG104** [comment]
Thanks Beth! Sorry I forgot to close this issue, I basically mimicked the React Bootstrap to fix all my styling by interacting and accessing `<FormControl>` and setting my desired size/style/anything with their predefined parameters.

Just as an example for anyone that might need it, I did it like this so that our form input for `body` would be larger...
```
<Form.Label htmlFor="body">Blog</Form.Label>
                    <Form.Control
                        as="textarea"
                        rows={8}
                        style={{overflow: "auto"}}
                        // placeholder="Blog Body"
                        name="body"
                        id="body"
                        value={blog.body}
                        onChange={handleChange}
                    />
```
