### ISSUE TITLE
Creating a Cart

### ISSUE THREAD

**Issue by lancenguyen100** [sei-ec-remote/team-project-issues#67]
**Describe the bug**
_A clear and concise description of what the bug is._
I am getting the error of reading properties of undefined (reading id)

**What is the problem you are trying to solve?**
I am trying to get the id to be defined, so the cart can be created when the route is hit.

**Expected behavior**
_A clear and concise description of what you expected to happen._
The cart should be created when the cart route is hit.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Throwing an error of undefined id

**Post any code you think might be relevant (one fenced block per file)**
```js
outer.post("/cart", (req, res, next) => {
    req.body.owner = req.user.id

    Cart.create(req.body)
        .then(cart => {
            console.log(cart)
			res.status(201).json({toObject})
            // res.json(fruit)
        })
        .catch(err => {
            res.json(err)
        })
})```



**What is your best guess as to the source of the problem?**
Maybe the id is not define?


**What things have you already tried to solve the problem?**
look backing at fruits and pets activities.


**Additional context**
Add any other context about the problem here.



**Paste a link to your repository here**[
](https://github.com/mayday91/P3Mongo-Express)

**Comment by timmshinbone** [comment]
You need the requireToken middleware, that's what sets `req.user` in your routes. Try adding that in and let me know what behaviors change.

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-05 at 1 42 10 PM](https://user-images.githubusercontent.com/103372967/183131830-2dfcae0b-bd74-45b4-a967-e7eef663d82e.png)
Does that mean the object has been created? In this case the CART?

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-05 at 1 43 01 PM](https://user-images.githubusercontent.com/103372967/183131937-0fa9cc7a-7093-4d96-9794-04d8417a386d.png)


Postman screenshot

**Comment by timmshinbone** [comment]
looks like you got a 201 created! Make your route match the process laid out in the examples in the boilerplate, and you'll then be able to send the newly created cart back as a response.

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-05 at 1 58 32 PM](https://user-images.githubusercontent.com/103372967/183134110-2f80770a-5c69-4628-b17f-e24cafdddbb3.png)

**Comment by lancenguyen100** [comment]
Does that mean my cart object has been successfully created in MongoDB??

**Comment by lancenguyen100** [comment]
![Screen Shot 2022-08-05 at 2 11 42 PM](https://user-images.githubusercontent.com/103372967/183136515-1441423c-4ff3-4b1b-b60c-f89063577f73.png)

Also, here is the change in my code.

**Comment by timmshinbone** [comment]
Looks good!
