### ISSUE TITLE
cannot display my data in my indexphotos.js file from api 

### ISSUE THREAD

**Issue by stephanieonyekaba** [sei-ec-remote/team-project-issues#7]
**Describe the bug**
_A clear and concise description of what the bug is._

**What is the problem you are trying to solve?**
I do not know how to display the data from my api in my client 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```
import React, { useState, useEffect } from 'react'
import { getAllPhotos } from '../../api/photos.js'
import { Link } from 'react-router-dom'

const IndexPhotos = (props) => {
    const [photos, setPhotos] = useState(null)
    useEffect(() => {
        getAllPhotos()
            .then(res => {
                console.log(res.data.photos)
                setPhotos(res.data.photos)
            })
            .catch(console.error)
    }, [])

    

    return ( 
        <>
            <h5> index photos</h5>
            <small>Type: {this.props.photos.bird}</small><br/>

        </>
    )

 

}

export default IndexPhotos

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by tkolsrud** [comment]
Is the data being returned an array? Bc in that case you'll need to map through in order to access individual objects.
