### ISSUE TITLE
cannot get show route to work

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/team-project-issues#70]
**Describe the bug**
_A clear and concise description of what the bug is._

were are attempting to move from the index page to the show page with a click, we are getting to out loading screen and thats it.

**What is the problem you are trying to solve?**

getting the use effect to work

**Expected behavior**
_A clear and concise description of what you expected to happen._

have a book and its information show up 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

loading screen

**Post any code you think might be relevant (one fenced block per file)**
```js
 useEffect(() => {
        getOneBook(id)

            // .then(res => setBook(res.data.data))
            .then(res => console.log(res.data.data))
            .catch(err => {                   
                msgAlert({
                    heading: 'Error getting book',
                    message: messages.getBooksFailure,
                    variant: 'danger'
                })
                navigate('/')
                //navigate back to the home page if there's an error fetching
            })
    }, [updated])
```

**What is your best guess as to the source of the problem?**

not calling our route the right way

**What things have you already tried to solve the problem?**

adjusting the route 

**Additional context**

**Paste a link to your repository here**

**Comment by aishcann** [comment]
resolved - error dotting into data properly
