### ISSUE TITLE
.map FUN!! aka not working

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/team-project-issues#71]
**Describe the bug**
_A clear and concise description of what the bug is._
I'm not able to run a .map on an object.

**What is the problem you are trying to solve?**
I'm trying to render cards of the information from the API call. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

I expect that once the returned data is stored in the components state, I could run a .map on it to generate a bootstrap card for each element, then render that below

**What is the actual behavior?**
_A clear and concise description of what actually happened._

.map is not working on my data

**Post any code you think might be relevant (one fenced block per file)**
```js

// state var
    const [searchTerm,setSearchTerm] = useState('')
    const [returnedSongList, setReturnedSongList] = ([])



// hit API for songs
const doSongSearch = (e) => {
        e.preventDefault()

        console.log('searTerm:',searchTerm);
        songSearch(searchTerm).then((res) => {setReturnedSongList = res.data}).catch((error) => {
        })  

        // songSearch(searchTerm).then((res) => console.log('RES.data%$%$%$:',res)).catch((error) => {
        // })  
    }

```

```js
// make a new list of elements each with songname, track... inside a JSX / Bootstrap card
   const songsToDisplay = returnedSongList.map(aSong => (
        <Card style={{ width: '30%', margin: 5}} key={aSong.track.name }>
            <Card.Header>{ aSong.track.name }</Card.Header>
                <Card.Body>
                    <Card.Text>
                        <h3>{ aSong.track.artist }</h3>
                        <h3>{ aSong.track.image }</h3>
                        <h3>{ aSong.track.mbid }</h3>
                    </Card.Text>
                </Card.Body>
        </Card>
    ))


```

```
BROWSER RETURNED ERROR:

TypeError: setReturnedSongsNotState.map is not a function
SongSearch
src/components/shared/SongSearch.js:48
  45 | 
  46 | console.log('setReturnedSongsNotState******',setReturnedSongsNotState);
  47 | 
> 48 | const songsToDisplay = setReturnedSongsNotState.map(aSong => (
     | ^  49 | 
  50 | <Card style={{ width: '30%', margin: 5}} key={ aSong.track.name }>
  51 |     <Card.Header>{ aSong.track.name }</Card.Header>
View compiled


```

**What is your best guess as to the source of the problem?**

I don't think that its the .map, but that the state variable is not updating beforehand to run the map...

A console log shows information from the Backend is correct. A console does NOT show that the state variable actually updated. So I believe that before it even hits the .map, there is no information.

**What things have you already tried to solve the problem?**
I'm trying to force a statechange in react to make sure the API songlist data saves to the state variable, BEFORE it hits the mapping function...

**Additional context**

**Paste a link to your repository here**

https://github.com/mayday91/P3Mongo-Express/tree/routes

**Comment by aishcann** [comment]
Your guess about the source of the problem sounds about right! We'll take a look more in depth after the deployment party.

**Comment by aishcann** [comment]
There was an error dotting into the data - issue is mostly resolved! Will circle back when there is more information gathered about the `#text` key in the object and how to work with that.

**Comment by Rando-cal** [comment]
The .map was not happy with the array I passed it. I had to dig down and get the right "json" path for it to accept it....

songSearch(searchTerm).then((res) => {setReturnedSongList = res.data}).catch((error) => {
        })  

TO

songSearch(searchTerm).then((res) => {setReturnedSongList(res.data.fmData.results.trackmatches.track)}).catch((error) => {
        })
