### ISSUE TITLE
Getting back some results from api with div and h tags 

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/team-project-issues#73]
**Describe the bug**
_A clear and concise description of what the bug is._

when we get our info back from the api some of it comes with header and paragraph tags and others come back fine.

**What is the problem you are trying to solve?**

to get the text to come back without the tags 

**Expected behavior**
_A clear and concise description of what you expected to happen._

to get the message to display without tags 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

text is showing up with p tags

**Post any code you think might be relevant (one fenced block per file)**
```js
 return (
        <>
            <Container className="fluid">
                <Card>
                    <Card.Header>{ book.title }</Card.Header>
                    <Card.Body>
                        <Card.Text>
                            <img src={`http://books.google.com/books/content?id=${book.id}&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api`}></img>
                            <small>Author: { book.authors }</small>
                            <h6>description: { book.description } </h6>

                        </Card.Text>
                    </Card.Body>
```

**What is your best guess as to the source of the problem?**
funny api issue

**What things have you already tried to solve the problem?**

changing the tags that we bring in the info with 

**Additional context**

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Is this still an issue? If it is please update with a reply, if it isn't please add a brief note about what solved the problem and close it.

**Comment by nrissman** [comment]
yes this is still an issue, but it seems to be a problem with the api... were calling it correctly but it gives back some if the info in odd ways

**Comment by timmshinbone** [comment]
Is this related to the other issue at all? Can you share what 'odd ways' you're describing?

**Comment by nrissman** [comment]
the returns include text tags, and they dont come back the same as the api json that we see in the browser
