### ISSUE TITLE
Updated information not showing on the page after Submitting Form, Edit, or Delete

### ISSUE THREAD

**Issue by bostonbachexchange** [sei-ec-remote/team-project-issues#75]
**Describe the bug**
_A clear and concise description of what the bug is._
Unable to update User information without Signing Out and Signing In. Information is cleared in the back end, and updates in the console.log, but not on the page. 

**What is the problem you are trying to solve?**
useEffect setProfile sets the profile information once, but use effect only runs once and not again on submit? 

**Expected behavior**
_A clear and concise description of what you expected to happen._
*A user should be able to click add a profile and is taken to the add a profile form. Then on Submit, the user is taken to the show page and show the updated information.
* A user should be able to click Edit Profile on the Show page, and open a Modal, after clicking submit on the Model, the update information that is set should appear on the page.
* *A user should be able to click delete on the Show Page, and be able to remove the User's Profile. Then the Show Page will update and tell the User that there is no profile information.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

The User's profile information updates, but does not show on the page without signing out and back in.

**Post any code you think might be relevant (one fenced block per file)**

```js
import React, { useState } from 'react';
import { Modal } from 'react-bootstrap'
import ProfileForm from '../shared/ProfileForm';
import messages from '../shared/AutoDismissAlert/messages'
// import { updateProfile } from '../../api/profiles';

const EditProfileModal = (props) => {
    // console.log('here are the props in the EditServiceModal', props)
    // these props come from the parent component
    const { 
        user, 
        show, 
        handleClose, 
        updateProfile, 
        msgAlert, 
        triggerRefresh, 
        setUser
    } = props
    const [profile, setProfile] = useState(props.profile)
    console.log('profile in edit modal', profile)
    const handleChange = (e) => {
        // we got this same function from create!
        setProfile(prevProfile => {
            let updatedValue = e.target.value;
            const updatedName = e.target.name;
            if (e.target.type === 'number') {
                updatedValue = parseInt(e.target.value)
            }
            const updatedProfile = {
                [updatedName]: updatedValue
            }
            return {
                ...prevProfile, 
                ...updatedProfile
            }
        })
    }
    const handleSubmit = (e) => {
        // this is where we put updatePet! We need (user, updateService)
        // once again, we get a similar function from createService component
        e.preventDefault();
        // we want it to hit the updateService function
        updateProfile(user, profile)
        // if we're successful in the modal, we want the modal to close
            // console.log('userSet is going to set', profile)
            .then(() => setProfile(setUser)) 
            .then(() => handleClose())
                msgAlert({
                    heading: 'Update Service Success',
                    message: messages.updateServiceSuccess,
                    variant: 'success',
                })
            )
            // if successful, we need to trigger a refresh for the show page so we see the new information immediately
            // this refreshes the state of the service component to the updated information!
            .then(()=> triggerRefresh())
            // this tells the user about an error
            .catch(msgAlert({
                heading: 'Update Service Error',
                message: messages.updateServiceFailure,
                variant: 'danger',
            }))
    }

    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton />
            <Modal.Body>
                <ProfileForm 
                    profile={profile}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Update Profile"
                />
            </Modal.Body>
        </Modal>
    );
}

export default EditProfileModal;

```

**What is your best guess as to the source of the problem?**
setUser is not passing through and updating on the front end (credit to Andrew)

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/alysvolatile/Scumptious_Bunch_Client/tree/ProfileEditModule

**Comment by timmshinbone** [comment]
Is this still an issue? If it is, please show me the parent component for this modal's code. If it's been resolved add a brief note of how you resolved it and close the issue.

**Comment by bostonbachexchange** [comment]
Got it resolved. API function wasn't being hit. After getting it to return data, I put the function inside useEffect and added [updated]. Thanks, Tim!
