### ISSUE TITLE
trying to get two apis to display 

### ISSUE THREAD

**Issue by nrissman** [sei-ec-remote/team-project-issues#76]
**Describe the bug**
_A clear and concise description of what the bug is._

we have a local and a web api, we would like both of them to show up in the same index

**What is the problem you are trying to solve?**

how to get the local api to show up 

**Expected behavior**
_A clear and concise description of what you expected to happen._

two apis showing in one index 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

only the web api shows up 

**Post any code you think might be relevant (one fenced block per file)**
```js

attempt #1
//attempting to get local api to show with google api
                // useEffect(function() { 
                //     let localBooks = null 
                //     let apiBooks = null
                //     async function getDb() {
                //         let books = {}
                //         localBooks = await getLocalBooks()
                //         apiBooks = await getAllBooks()
                //         console.log(localBooks.data.books)
                //         console.log(apiBooks.data.data)
                //         if (apiBooks.length) {
                //             apiBooks.map((book) =>{
                //             books.title = book.data.volumeInfo.title
                //             books.authour = book.data.volumeInfo.authour
                //             books.description = book.data.volumeInfo.description
                //         })   
                //         }
                //         console.log('here are the books', books)
                //     }
                //     getDb()
                
                // }, [])

attempt#2

                // useEffect(() => {
                //     console.log(props)
                //     getLocalBooks()
                        
                //     .then(res => setBooks(res.data.book))
                //     .catch(err => {
                //         msgAlert({
                //             heading: 'Error Getting Books',
                //             message: messages.getBooksFailure,
                //             variant: 'danger',
                //         })
                //         setError(true)
                //     })

                // }, [])


                  // const localBookCards = books.map(book => (
    //     <Card style={{ width: '30%', margin: 5}} key={ book.id }>
    //         <Card.Header>{ book.title }</Card.Header>
    //         <Card.Body>
    //         <img></img>
    //             <Card.Text>
    //                 <Link to={`/books/local/${book.id}`}>View: { book.title }</Link>
    //             </Card.Text>
    //         </Card.Body>
    //     </Card>
    // ))



```

**What is your best guess as to the source of the problem?**
program diesnt know we want to display both and only displays one 

**What things have you already tried to solve the problem?**

pasted in the code portion

**Additional context**
we made a route in books.js for this 

**Paste a link to your repository here**

**Comment by timmshinbone** [comment]
Share the code for any of the functions called in these two attempts, like `getLocalBooks()`

**Comment by nrissman** [comment]
`  //attempting to get local api to show 
export const getLocalBooks = () => {
    return axios(`${apiUrl}/books`)
}`

**Comment by timmshinbone** [comment]
Share the other functions too, like `getDb()`

**Comment by nrissman** [comment]
getDb is self contained to that pice of code,

**Comment by nrissman** [comment]
theres no other code anywhere else

**Comment by timmshinbone** [comment]
lol you're right, lemme read it again real quick now that I've had a little coffee😂

**Comment by nrissman** [comment]
hahaah all good

**Comment by timmshinbone** [comment]
I would recommend trying to declare that function outside of the useEffect and calling it inside the useEffect instead of doing both. Try that and let me know how the behavior changes.

**Comment by nrissman** [comment]
the getLocalBooks?

**Comment by nrissman** [comment]
hmm so like make a const getLocalBooks = localBooks outside of the books index function then call localBooks inside?

**Comment by timmshinbone** [comment]
In this snippet of code you're declaring the function `getDb` and calling it right after that, I'm talking about moving that function declaration out of useEffect and then calling it in useEffect to see if that changes behavior. This is the code I'm talking about:
![image](https://user-images.githubusercontent.com/55121526/183440932-167be459-800b-49c2-8612-dee581ab7f85.png)

**Comment by nrissman** [comment]
ok we tried that and im still not getting them to show, i can confirm the creation in the inspector but not view in the website

**Comment by timmshinbone** [comment]
ok, has the behavior changed at all? Any new console logs you can add/share with me here that might shed a little more light on this?

**Comment by nrissman** [comment]
we think its kinda working now, trying to iron out some oddities, and need to make a new show route for books in our local db

**Comment by timmshinbone** [comment]
ok we can look at it again sometime after lunch
