### ISSUE TITLE
Problem calling API says unauthorized even with correct API key being used

### ISSUE THREAD

**Issue by Amandacorral07** [sei-ec-remote/team-project-issues#77]
**Describe the bug**
_A clear and concise description of what the bug is._

When calling the API url it returns cannot get 401 unathorized. I have input the correct API url. I have the correct information being passed in. 

**What is the problem you are trying to solve?**

Calling the API and returning and image jpg

**Expected behavior**
_A clear and concise description of what you expected to happen._

The API returns and image.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Returned 401 unauthorized error in console.

**Post any code you think might be relevant (one fenced block per file)**
```js
let radiusTester = await axios.get(`https://api.opentripmap.com/0.1/en/places/radius?radius=32186.9&lon=${destination.lon}&lat=${destination.lat}&apikey=5ae2e3f221c38a28845f05b6ee69c6dabf1a1c065bbb25f00387dbd9`)

        destination.xid = radiusTester.data.features[0].properties.xid
        console.log('this is the xid', destination.xid)
        console.log('radiusTester', radiusTester)
        let imageTester = await axios.get(`https://api.opentripmap.com/0.1/en/places/xid/${destination.xid}&apikey=5ae2e3f221c38a28845f05b6ee69c6dabf1a1c065bbb25f00387dbd9`)
         console.log('this is the image', imageTester)
```

**What is your best guess as to the source of the problem?**

No idea

**What things have you already tried to solve the problem?**

Changing API URL doesn't work

**Additional context**

**Paste a link to your repository here**

https://github.com/tylly/project-3-react

**Comment by timmshinbone** [comment]
Are you console logging the response? Please share a screenshot of the entire 401 response here.

**Comment by Amandacorral07** [comment]
<img width="699" alt="Screen Shot 2022-08-08 at 7 02 06 AM" src="https://user-images.githubusercontent.com/99426594/183436306-0c145161-c24a-470e-a643-7c34c72227ca.png">

**Comment by timmshinbone** [comment]
Are you sure the apiKey is meant to be separated by an ampersand instead of a question mark in the url? Looks like(from my _brief_ glancing at the docs) you can use a question mark instead in some circumstances, see here:
![image](https://user-images.githubusercontent.com/55121526/183437231-c11bad68-0540-435e-a397-788c2b5b68f3.png)

**Comment by Amandacorral07** [comment]
Sweet! That worked! Only now the calls we are making don't seem to have images. We'll have to look for another API. Thank you!

**Comment by timmshinbone** [comment]
Wait why do you need another API? does this one not return any images? do you just need to make a different call to another endpoint?

**Comment by Amandacorral07** [comment]
It's supposed to return an image in the response but in each call I have done there hasn't been an image response.
<img width="747" alt="Screen Shot 2022-08-08 at 7 26 16 AM" src="https://user-images.githubusercontent.com/99426594/183441346-89f76b3d-68ff-4e39-ae52-c80aefd25be1.png">

Comparing it to the opentrip docs I should get this image response....
<img width="600" alt="Screen Shot 2022-08-08 at 7 28 13 AM" src="https://user-images.githubusercontent.com/99426594/183441813-71413ecb-66e8-46d4-a35d-ef03cfc388d6.png">

**Comment by timmshinbone** [comment]
What is the `otm` and what is in the `sources -> attributes` array?

**Comment by Amandacorral07** [comment]
<img width="607" alt="Screen Shot 2022-08-08 at 7 35 00 AM" src="https://user-images.githubusercontent.com/99426594/183443280-dbfef568-2c4e-40a6-af0c-a2fbd352ec7c.png">


The otm url brings me to a map page of some sorts. 
<img width="385" alt="Screen Shot 2022-08-08 at 7 34 01 AM" src="https://user-images.githubusercontent.com/99426594/183443099-832edd53-b08b-406a-a6aa-595edfdafe56.png">

**Comment by timmshinbone** [comment]
ok, let's meet after Andrew covers double palindrome
