### ISSUE TITLE
.map not happy

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/team-project-issues#78]
**Describe the bug**
_A clear and concise description of what the bug is._

Trying to do a .map on an object. I'm tying to get a document from mongo(backend) then convert it to array so we can do a .map on it to display cards with the information.

First I'm trying to make a copy in a state variable to get it out of useEffect(). Then I want to convert it before putting it in .map

Browser is erroring out.

**What is the problem you are trying to solve?**

(see above)

**Expected behavior**
_A clear and concise description of what you expected to happen._

I want the res with the mongo list to converted to array, then save to state. I can then use the state var to .map over.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

Not sure, if its hitting the .then in useEffect() at this point even before the state var save.

**Post any code you think might be relevant (one fenced block per file)**
```js
    const [songListFromMongo, setSongListFromMongo]= useState({})


    useEffect(() => { 
        getMyCart(user)
        .then((res) => {
            // cartItemsToDisplay = res.data.cart[0].songs
            // let oneThing = res.data.cart[0].songs[9].songName // working+
            console.log('^^^^^^^^^^^^IN .THEN RES^^^^^^^^^^^^^');
            setSongListFromMongo(res.data.cart[0])
      
            
            
            // console.log('RES++++++++++++++',res.data.cart[0].songs);})
        // .catch((error) => {console.log(error) })
    }, [])
})



```

```js

const conversion = () => {
    // let converted = JSON.parse(oneThing)

    console.log('songListFromMongo ::***********',songListFromMongo);
          
    return 

}

conversion()

           const finalCartItems = songListFromMongo.map(cartElement => (
                <Card style={{ width: '30%', margin: 5}} key={cartElement}>
                    <Card.Header><strong>{ cartElement }</strong></Card.Header>
                        <Card.Body>
                            ...

```

ERROR
```js

TypeError: songListFromMongo.map is not a function
MyCart
src/components/carts/MyCart.js:56
  53 | 
  54 | conversion()
  55 | 
> 56 |            const finalCartItems = songListFromMongo.map(cartElement => (
  57 |                 <Card style={{ width: '30%', margin: 5}} key={cartElement}>
  58 |                     <Card.Header><strong>{ cartElement }</strong></Card.Header>
  59 |                         <Card.Body>
``



**What is your best guess as to the source of the problem?**

I thought the mongo object was throwing the .map into a fit, but I can't see the console output  .then in the useEffect now...
Its probably not saving to state vars, then its not converting the object to an array which the .map needs.



**What things have you already tried to solve the problem?**

Many things.



**Additional context**
Add any other context about the problem here.



**Paste a link to your repository here**
https://github.com/Rando-cal/P3React/tree/showCart

**Comment by timmshinbone** [comment]
Please share the data(the response) you're trying to do this to so I can see how it's laid out and get a clearer picture of the problem.

**Comment by Rando-cal** [comment]
Haha. My useEffect is not getting hit now so I can't pull the res ( mongoDb songlist) at the moment...

**Comment by Rando-cal** [comment]
i  pulled my getMyCart() out of useEffect and got this.
![res](https://user-images.githubusercontent.com/106480852/183440647-ba79d81b-c851-400a-8046-9f3da31c0437.PNG)

**Comment by timmshinbone** [comment]
Looks like, instead of this `setSongListFromMongo(res.data.cart[0])` you want to use this `setSongListFromMongo(res.data.cart[0].songs)` as `songs` is the actual array you're trying to use.

**Comment by Rando-cal** [comment]
Okay. So with getMyCart() outside of useEffect with

```js
getMyCart(user)

.then((res) => {
    
    // console.log('res',res.data.cart[0].songs)}
    setSongListFromMongo(res.data.cart[0].songs)

}).catch((error)=> {console.log(error);})
```
I get this in browser:


![res2](https://user-images.githubusercontent.com/106480852/183445611-c5262b59-6004-411e-8928-ab3d494f2da1.PNG)

**Comment by timmshinbone** [comment]
ok, what's does `console.log(songListFromMongo)` show? Is it possible you're not handling what happens when the songList is `null`?

**Comment by Rando-cal** [comment]
the state var has this in it:

!!!!songListFromMongo {}[[Prototype]]: 

![res3](https://user-images.githubusercontent.com/106480852/183455921-56a728fd-aab5-43ec-8a9f-8ca10d34b976.PNG)

However, i'm not finding the values in it. Perhaps I'm not finding them , or they are not being added the state var with 
setSongListFromMongo(res.data.cart[0].songs) ... My guess is there are not adding to the state var but I'm not sure why...

**Comment by Rando-cal** [comment]
If i change state var type to [] instead of {} it looks like its taking.

Now i'm getting:

Error: Objects are not valid as a React child (found: object with keys {songName, songArtist, songImages}). If you meant to render a collection of children, use an array instead.   

/

```
react-dom.development.js:13231 Uncaught Error: Objects are not valid as a React child (found: object with keys {songName, songArtist, songImages}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13231:1) 

```

with this at the very bottom

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

**Comment by timmshinbone** [comment]
Ok, let's take a look together in a breakout room after lunch

**Comment by Rando-cal** [comment]
Solution: 
- some syntax errors.  
- I set the state variable to null.  
- i pulled the array.map out of a variable (outside the comp. render() ) and put it directly in component render()
- used useEffect AND added a dependency array   },[])
- added a conditional to component return if data was empty
- made sure that the .map saw the first ARRAY in a complex object with multiple arrays {1 {2 [3 {4 [5 {6} ...  Showed it 3 not 5 
- used UUIDV4 npm package for .map key ={uuidv4()}
