### ISSUE TITLE
Adding ._id to seeded documents

### ISSUE THREAD

**Issue by DRG104** [sei-ec-remote/team-project-issues#79]
**Describe the bug**
_A clear and concise description of what the bug is._
Would like to add ._id to seeded documents, an issue occurs when viewing seeded documents and the page errors out with reading `unidentified _id`

**What is the problem you are trying to solve?**
Errors associated with seeded documents not having an owner ID

**Expected behavior**
_A clear and concise description of what you expected to happen._
When viewing seeded documents signed in/out as an authenticated user, page will *sometimes* error out because it cannot read a user id?

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Clicking through seeded documents to display their show page, sometimes an error will occur "cannot read undefined user ID"
I'm unsure why it happens after a random amount of show pages have been shown.

**Post any code you think might be relevant (one fenced block per file)**
Unsure of what code is the issue, error presents:
TypeError: Cannot read properties of undefined (reading '_id')
src/components/comments/ShowComment.js:32
```js
const ShowComment = (props) => {
    const { comment, blog, user, msgAlert, triggerRefresh } = props
    const [editModalShow, setEditModalShow] = useState(false)

    const destroyComment = () => {
        deleteComment(user, blog._id, comment._id)
            .then(() =>
                msgAlert({
                    heading: 'Comment Deleted',
                    message: 'Bye bye comment!',
                    variant: 'success'
                }))
            .then(() => triggerRefresh())
            .catch(() =>
                msgAlert({
                    heading: 'Oh no!',
                    message: 'Something went wrong!',
                    variant: 'danger'
                }))
    }
    return (
        <>
            <Card className="m-2">
                <Card.Body>
                    <small>{comment.text}</small><br />
                </Card.Body>
                <Card.Footer>
                    {
                        user && user._id === blog.owner._id
                            ?
                            <>
                                <Button
                                    variant="warning"
                                    onClick={() => setEditModalShow(true)}
                                >
                                    Edit Comment
                                </Button>
                                <Button
                                    onClick={() => destroyComment()}
                                    variant="danger"
                                >
                                    Delete Comment
                                </Button>
                            </>
                            :
                            null
                    }
                </Card.Footer>
            </Card>
            <EditCommentModal
                user={user}
                blog={blog}
                comment={comment}
                show={editModalShow}
                handleClose={() => setEditModalShow(false)}
                msgAlert={msgAlert}
                triggerRefresh={triggerRefresh}
            />
        </>
    )
}
```

**What is your best guess as to the source of the problem?**
I'm not really sure, my understanding is throw TypeErrors are associated with authentication issues

**What things have you already tried to solve the problem?**
Unsure, the bug happens inconsistently, obviously the best way to avoid it is to not click on too many show pages for a documents?

**Additional context**

**Paste a link to your repository here**
https://github.com/Zene09/project-3-team-8-client

**Comment by timmshinbone** [comment]
Try adding a conditional rendering statement that checks if the blog has an owner at all. That's a quick workaround, for a more in depth solution to your seeded data not having owners, I can join your breakout room later. For now, try this and update me here with how/if the behavior changes.

**Comment by DRG104** [comment]
I'm sorry, I went through a few console logs and noticed there ARE owners (IDs) associated with the seeded data. I guess now I'm just unsure of why its suddenly having issues reading owner IDs at all? Viewing a SHOW page for any document does not require a user, so am I misunderstanding that the error is saying the `document` or the `subdocument` requires an owner?

**Comment by timmshinbone** [comment]
Can you share the entire error? Maybe a screenshot of it?

**Comment by DRG104** [comment]
![image](https://user-images.githubusercontent.com/106381005/183453097-ce2efd65-1a88-45a9-bb4f-c07395ae0eb7.png)

**Comment by timmshinbone** [comment]
console log all of the blogs and send what that looks like

**Comment by DRG104** [comment]
Blogs in Index
![image](https://user-images.githubusercontent.com/106381005/183459982-a5b7f265-3cfe-4b7f-aa18-84bcf090ede9.png)

One blog in index
![image](https://user-images.githubusercontent.com/106381005/183460079-9501bd04-8b48-405c-bb8b-c815002ced99.png)
