### ISSUE TITLE
Is it possible to refresh multiple components with one handleSubmit?

### ISSUE THREAD

**Issue by danstacy1** [sei-ec-remote/team-project-issues#81]
**Describe the bug**
_A clear and concise description of what the bug is._

We have two separate cards, Destination and Activities. When we update our destination, we still see the suggested activities for the old destination. Is it possible to update both the destination and activities with one triggerRefresh or handleSubmit?

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js
const handleSubmit = async (e) => {
        e.preventDefault();
        let testing = await axios.get(`https://api.opentripmap.com/0.1/en/places/geoname?name=${destination.name}&apikey=5ae2e3f221c38a28845f05b6ee69c6dabf1a1c065bbb25f00387dbd9`)
        console.log('testing', testing)
        destination.lat = testing.data.lat
        destination.lon = testing.data.lon
        destination.population = testing.data.population
        console.log(destination)

        updateDestination(user, destination)
          .then(() => handleClose())
          // .then(res => { navigate(`/destinations/${res.data.destination._id}`)})
          .then(() =>
            msgAlert({
              heading: "oh yea!",
              message: "success",
              variant: "success",
            })
          )
          .then(() => triggerRefresh())
          .catch(() =>
            msgAlert({
              heading: "oh no!",
              message: "failure",
              variant: "danger",
            })
          );
      };
```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/tylly/project-3-react.git

**Comment by aishcann** [comment]
Are activities linked to your destinations? As in a part of your destination schema? If so, is there a way you can update your activities state after you update the destinations?

**Comment by kestler01** [comment]
" We have two separate cards, Destination and Activities. When we update our destination, we still see the suggested activities for the old destination. Is it possible to update both the destination and activities with one triggerRefresh or handleSubmit? "

Yes - ideally we want to use state lifecycle methods to handle these refreshes / changing state triggers a new render ( remember how we have handle change with forms ? ) 
To get both of the components to 'update' we should trigger our 're render' in the parent component or a new one if you don't have a shared parent that works well in context

**Comment by danstacy1** [comment]
Nice. We got it fixed.
