### ISSUE TITLE
axios calls

### ISSUE THREAD

**Issue by jadenRuplal** [sei-ec-remote/team-project-issues#82]
**Describe the bug**
_A clear and concise description of what the bug is._
function isn't making a call to the API

**What is the problem you are trying to solve?**
I'm trying to update stock in the item DB of one item that has been purchased.

**Expected behavior**
_A clear and concise description of what you expected to happen._
i expect the number to update by 1

**What is the actual behavior?**
_A clear and concise description of what actually happened._
nothing is really happening just a .catch

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
i think my function to call to the API is erroring out before it does anything

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/jadenRuplal/poke_store_client

**Comment by kestler01** [comment]
sounds like fun, lets take a peek at that apicall function and where you're evoking it in separate code blocks

**Comment by jadenRuplal** [comment]
Client side
`const changeQuantity = (item) => {
        // e.preventDefault()
        const updatedStock = item.stock - 1
         updateStockItem(item, updatedStock)
            .then(() => triggerRefresh())
            .catch(() =>
                msgAlert({
                    heading: 'Oh No!',
                    message: messages.updateItemFailure,
                    variant: 'danger'
                })
            )
}`


`export const updateStockItem = (item, updatedStock) => {

    console.log('this is updatedStock', updatedStock)

    return axios({
        url: `${apiUrl}/items/${item._id}`,
        method: 'PATCH',
        data: { item: updatedStock }
    })
}`


API
`// UPDATE
// PATCH /items/:id/stock
router.patch('/items/:id/stock', removeBlanks, (req, res, next) => {
	console.log("this is req.body", req.body)
	console.log("this is req.params.id", req.params.id)

	Item.findById(req.params.id)
		.then(handle404)
		.then((item) => {
			return item.updateOne(req.body.item.stock)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})`

**Comment by jadenRuplal** [comment]
update i got it to make a call but its not really working

**Comment by kestler01** [comment]
in your changeQuantity function, lets add a console log and print out what the item and updatedStock re when you try to make the call 
past in a code block below

**Comment by jadenRuplal** [comment]
cost: 500
createdAt: "2022-08-07T00:35:52.333Z"
description: "Bulbasaur is a Grass/Poison type Pokémon introduced in Generation 1. It is known as the Seed Pokémon."
image: "https://img.pokemondb.net/artwork/avif/bulbasaur.avif"
name: "Bulbasaur"
pokemonType: "Grass"
stock: 10
updatedAt: "2022-08-08T18:00:59.608Z"
__v: 0
_id: "62ef08e8b60a094b44fac757"



and i get 9




this is item and updatedStock

**Comment by kestler01** [comment]
well that looks all good, do we get an api error now ?

we may want to start looking at the api side now since we know we're passing the correct values

**Comment by jadenRuplal** [comment]
No, I just get an incoming request and that's it I could possibly get one it may be there for a second till the page changes then it might go away

**Comment by jadenRuplal** [comment]
performing an update on the path _id would modify the immutable field _id

this is the error i found

**Comment by jadenRuplal** [comment]
i can send an image on slack i cant copy the code in time

**Comment by jadenRuplal** [comment]
fixed problem on the api side
