### ISSUE TITLE
Need help deploying

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/team-project-issues#83]
**Describe the bug**
_A clear and concise description of what the bug is._
Deployment is done without errors
the client app isn't getting data from beck end
We believe they are cross set up properly

**What is the problem you are trying to solve?**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by aishcann** [comment]
When you deploy your backend it essentially starts a new database and you have to put in new data. Have you done this already?

**Comment by shaialoni** [comment]
Yes. We also tested the backend routes with postman, so they work there.
but when we load the client app on deployed it isnt talking to the backend

**Comment by aishcann** [comment]
resolved - CORS error
