### ISSUE TITLE
CSS not displaying after refresh

### ISSUE THREAD

**Issue by mayday91** [sei-ec-remote/team-project-issues#84]
**Describe the bug**
_A clear and concise description of what the bug is._
CSS is working and then once app is refreshed the css styling goes away. However, bootstrap css styling is working. Went over it with Andrew already and made sure everything is in the proper place as far as importing.

**What is the problem you are trying to solve?**
Want CSS to display all the time

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**
I HAVE NO IDEA *sad/angry face*

**What things have you already tried to solve the problem?**
changing how the css file is imported, where it is imported and what style elements its using

**Additional context**

**Paste a link to your repository here**
https://github.com/mayday91/P3React

**Comment by ejparnell** [comment]
@mayday91 When importing styles you have to import them to the file you want to use them in. I would suggest moving your import statement to the file you are using your styles in

**Comment by mayday91** [comment]
I figured it out. Had to remove bootstrap import and change css to scss file
