### ISSUE TITLE
boot strap issues 

### ISSUE THREAD

**Issue by maiky5198** [sei-ec-remote/team-project-issues#9]
**Describe the bug**
_A clear and concise description of what the bug is._
bootstrap fonts suck

**What is the problem you are trying to solve?**
changing fonts

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js

```

**What is your best guess as to the source of the problem?**

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**

**Comment by maiky5198** [comment]
also need help with flex box and comments

**Comment by DoireannJane** [comment]
snippets pls

**Comment by maiky5198** [comment]
@import url('https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap');

body {
  /* font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif; */
    font-family: 'Fjalla One', sans-serif;
}

code {
  /* font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
    monospace; */
    font-family: 'Fjalla One', sans-serif;
} 

.bg-myOrange {
  background-color: orange;
}



we've tried everything on many files doing many things. this is the index.css file

**Comment by maiky5198** [comment]
need help overriding bootstrap on many files

**Comment by DoireannJane** [comment]
Is your googlefonts being linked in the metadata of your html?

**Comment by maiky5198** [comment]
yes

**Comment by DoireannJane** [comment]
So you want to change the font for every element?

**Comment by maiky5198** [comment]
yea it works when I refresh the page a million times. Concluded that bootstrap is overriding it

**Comment by DoireannJane** [comment]
probably has to do with your specificity. I've always used !important (directly after the css value) for details that won't ever change but it's not always the best practice. ---> https://stackoverflow.com/questions/19768794/custom-css-being-overridden-by-bootstrap-css

**Comment by DoireannJane** [comment]
If you don't have luck in 10 minutes, I'll pop in.

**Comment by maiky5198** [comment]
it worked! thanks !
