### ISSUE TITLE
Troubles using postman

### ISSUE THREAD

**Issue by nabbott98** [sei-ec-remote/team-project-issues#90]
**Describe the bug**
_A clear and concise description of what the bug is._
I am having trouble using postman with the auth, login is not working.

**What is the problem you are trying to solve?**
How to use postman with the auth tokens

**Expected behavior**
_A clear and concise description of what you expected to happen._

Return user info and token

**What is the actual behavior?**
_A clear and concise description of what actually happened._
{
    "name": "BadParamsError",
    "message": "A required parameter was omitted or invalid",
    "status": 422
}

**Post any code you think might be relevant (one fenced block per file)**
```JSON
{
    "email": "nick@nick.nick",
    "hashedPassword": "nick"
}

const mongoose = require('mongoose')

const userSchema = new mongoose.Schema(
	{
		email: {
			type: String,
			required: true,
			unique: true,
		},
		hashedPassword: {
			type: String,
			required: true,
		},
		token: String,
	},
	{
		timestamps: true,
		toObject: {
			// remove `hashedPassword` field when we call `.toObject`
			transform: (_doc, user) => {
				delete user.hashedPassword
				return user
			},
		},
	}
)

module.exports = mongoose.model('User', userSchema)
```

**What is your best guess as to the source of the problem?**
I have the wrong body, or I am misunderstanding the model

**What things have you already tried to solve the problem?**
Tried different fields in the body that I was sending

**Additional context**

**Paste a link to your repository here**
https://github.com/nabbott98/global-back/

**Comment by scarletpuma** [comment]
You need to wrap the email and password in an object called credentials. So, it'd look something like

```{
"credentials": {
{
    "email": "nick@nick.nick",
    "hashedPassword": "nick"
}
}
```

**Comment by scarletpuma** [comment]
Also, you should change "hashedPassword" to just "password".

**Comment by nabbott98** [comment]
I just tried that and got this back

```JSON
{
    "expose": true,
    "statusCode": 400,
    "status": 400,
    "body": "\"credentials\": {\n    {\n        \"email\": \"nick@nick.nick\",\n        \"hashedPassword\": \"nick\"\n    }\n}",
    "type": "entity.parse.failed"
}
```

**Comment by timmshinbone** [comment]
hashedPassword should be changed to just `password`
![image](https://user-images.githubusercontent.com/55121526/199022932-9b6cdf0a-945d-41a1-8e22-4308f20c27d5.png)

**Comment by nabbott98** [comment]
![Screen Shot 2022-10-31 at 10 13 44 AM](https://user-images.githubusercontent.com/105761906/199028759-83326949-421f-4f72-b8e8-7e7d76a49ae3.png)

**Comment by nabbott98** [comment]
I am now getting a badparamserror
```JSON
{
    "name": "BadParamsError",
    "message": "A required parameter was omitted or invalid",
    "status": 422
}
```

**Comment by nabbott98** [comment]
Needed password_confirmation as a line
