### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by ange1026** [sei-ec-remote/team-project-issues#91]
**Describe the bug**
_A clear and concise description of what the bug is._

I'm trying to link a css file with a component file it looks like it worked, but when the page is refreshed the css doesn’t work

**What is the problem you are trying to solve?**
css style gone after page refresh

**Expected behavior**
_A clear and concise description of what you expected to happen._
 that the style doesn’t disappear when the page is refreshed

**What is the actual behavior?**
_A clear and concise description of what actually happened._

I imported the css file to my component, is seems that the connection work because the css style from the file shows but only for a while then if i refresh the page is gone

**Post any code you think might be relevant (one fenced block per file)**
```js
import '../home.css'
```

**What is your best guess as to the source of the problem?**

maybe is something with the import link

**What things have you already tried to solve the problem?**

different routes

**Additional context**

no more context

**Paste a link to your repository here**
https://github.com/ange1026/Trivia-Client/tree/main

**Comment by scarletpuma** [comment]
Could you push up your code so I can get a better idea of what's going on?

**Comment by ange1026** [comment]
I'm trying it out on a boilerplate first before adding it to the project, do you mind meeting in a zoom room?

**Comment by scarletpuma** [comment]
I would try it out on the project repo. You can always make a separate branch if you're worried about messing something up/breaking something. You want to make sure what you're doing is going to work on your project. No two apps are going to be exactly the same.

**Comment by ange1026** [comment]
Okay! I pushed it out on the project is on the branch named 'angelica'

**Comment by scarletpuma** [comment]
Have you tried it with just '.home.css'?

**Comment by ange1026** [comment]
yes, it gives me an error
./src/components/Home.js
Module not found: Can't resolve '.home.css' in '/Users/angelicadelacruz/Sei/projects/Trivia-Client/src/components'

**Comment by scarletpuma** [comment]
Sorry! I meant './home.css'

**Comment by ange1026** [comment]
I tried that, it still the same error

**Comment by ange1026** [comment]
```
index.js:1 Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.
    at body
    at Home
    at Routes (http://localhost:3000/static/js/vendors~main.chunk.js:52084:5)
    at App (http://localhost:3000/static/js/main.chunk.js:117:81)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:52017:15)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:51532:5)
```
it gives me this in the console

**Comment by scarletpuma** [comment]
What that error means is that somewhere in your code you have a <body> tag inside of a <div>. So, I would find out where that's happening and fix it.

**Comment by ange1026** [comment]
Solved in TA hours!  I  just put a 'div' tag instead of a body tag and change the height so the background color covers everything.
