### ISSUE TITLE
More of a best-practice/security issue

### ISSUE THREAD

**Issue by infinitelyann** [sei-ec-remote/team-project-issues#92]
**Describe the bug**
_A clear and concise description of what the bug is._

The only way I was able to get  public API data to display without Unicode was with  < dangerouslySetInnerHTML >

**What is the problem you are trying to solve?**

Special characters, such as an apostrophe, would display strangely

**Expected behavior**
_A clear and concise description of what you expected to happen._

<img width="709" alt="Screen Shot 2022-10-31 at 9 42 48 AM" src="https://user-images.githubusercontent.com/68655342/199021955-b6c46940-4e69-43bd-869a-c5027380f800.png">
 

**What is the actual behavior?**
_A clear and concise description of what actually happened._

<img width="659" alt="Screen Shot 2022-10-31 at 9 46 00 AM" src="https://user-images.githubusercontent.com/68655342/199022693-0584efb2-c54d-4d92-a380-8fa56d9a3d59.png">

**Post any code you think might be relevant (one fenced block per file)**

<img width="916" alt="Screen Shot 2022-10-31 at 9 47 03 AM" src="https://user-images.githubusercontent.com/68655342/199022865-97616f12-b67b-452d-84fb-925eb71f06b6.png">

this was the only way I was able to get the text to display as intended- but I read online that this poses security issues and wanted to check with you guys if this was okay for this project

**What is your best guess as to the source of the problem?**

I'm sure that there is an encoding process that the text goes through before being displayed

**What things have you already tried to solve the problem?**

I have tried adjusting the 'header' in my API call- but that didn't work

<img width="752" alt="Screen Shot 2022-10-31 at 9 50 44 AM" src="https://user-images.githubusercontent.com/68655342/199023657-fb6253a4-7271-4f0f-aed0-5d2c3621f0ce.png">

**Additional context**

**Paste a link to your repository here**
https://github.com/infinitelyann/Trivia-Client 

--not updated bc I want to make sure I'm okay to continue with this method

**Comment by ejparnell** [comment]
@infinitelyann I suggest using [`.replace` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) and using regex to match the special characters you want to replace. [This](https://regex101.com/) is the site I use to test my regex to ensure I'm crafting the correct expression.
