### ISSUE TITLE
Issueinvolving package.json and multi platform usability

### ISSUE THREAD

**Issue by jlm8965** [sei-ec-remote/team-project-issues#93]
**Describe the bug**
_A clear and concise description of what the bug is._
Julie changed a line in package.json for her windows machine and broke the app for the rest of the team.

**What is the problem you are trying to solve?**

Julie changed a line in package.json for her windows machine and broke the app for the rest of the team.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Julie changed a line in package.json for her windows machine and broke the app for the rest of the team.

**What is the actual behavior?**
_A clear and concise description of what actually happened._

broken app. 

**Post any code you think might be relevant (one fenced block per file)**
```js

```
added - "start": "react-scripts --openssl-legacy-provider start" to package.json

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**What is your best guess as to the source of the problem?**

windows updates

**What things have you already tried to solve the problem?**

**Additional context**

**Paste a link to your repository here**
https://github.com/skbarbee/petMatch.git

**Comment by ejparnell** [comment]
Working with different systems can do this. What we will need to do is to add the `package.json` to your `.gitignore` and remove your `package.json` from being tracked by git. 

First, remove your `package.json` from being tracked by git `git rm --cached package.json`. Then modify your `package.json` to be correct for your environment. Run `rm -rf package-lock.json node_modules` to remove old environment and `npm install` to install the new environment. 

This will make sure you have a working environment that works for your OS
