### ISSUE TITLE
RequireOwnership throwing error 'cannot read properties of undefined (reading: '_id')

### ISSUE THREAD

**Issue by harrisimon** [sei-ec-remote/team-project-issues#94]
**Describe the bug**
_A clear and concise description of what the bug is._
When trying to update/patch a subdoc and reading for requireOwnership it isn't finding _id

**What is the problem you are trying to solve?**

Trying to figure out where requireOwnership is reading the req for _id

**Expected behavior**
_A clear and concise description of what you expected to happen._
Should be checking for ownership and then patching

**What is the actual behavior?**
_A clear and concise description of what actually happened._
Throwing an error

**Post any code you think might be relevant (one fenced block per file)**
```js
router.patch('/questions/:gameId/:questionId', requireToken, (req, res, next) => {
    const { gameId, questionId } = req.params
 
    Game.findById(gameId)
        .then((game) => {
            console.log(game.questions)
            const theQuestion = game.questions.id(questionId)
            console.log("the game",game)
            console.log("the req", req)
            requireOwnership(req, game)
            theQuestion.set(req.body.question)
            return game.save()
        })
        .then(game => res.sendStatus(204))
        .catch(next)
})
```

**What is your best guess as to the source of the problem?**
Something in the req? I've been console logging and can't find it

**What things have you already tried to solve the problem?**
Lots of console logging and googling

**Additional context**

**Paste a link to your repository here**
[https://github.com/harrisimon/Trivia-API/tree/harrison](https://github.com/harrisimon/Trivia-API/tree/harrison)

**Comment by scarletpuma** [comment]
Your requireOwnership is only accessing 'game' right now. If you want it to access 'theQuestion', you'll have to either edit requireOwnership to be able to access subdocs, or create a new middleware that does that.

**Comment by harrisimon** [comment]
Hmm ok! I was following a very similar structure to Timm's pets app where toys are a subdoc of Pet--eg question is a subdoc of game. In the example for patching in Timm's code it's very similar:
```js
router.patch('/toys/:petId/:toyId', requireToken, removeBlanks, (req, res, next) => {
    const { petId, toyId } = req.params

    // find the pet
    Pet.findById(petId)
        .then(handle404)
        .then(pet => {
            // get the specific toy
            const theToy = pet.toys.id(toyId)

            // make sure the user owns the pet
            requireOwnership(req, pet)

            // update that toy with the req body
            theToy.set(req.body.toy)

            return pet.save()
        })
        .then(pet => res.sendStatus(204))
        .catch(next)
})

```
Any reason that's different? Maybe I'm misunderstanding

I'm checking if the user owns the game they are accessing to be able to update a question if that makes sense.

**Comment by ejparnell** [comment]
@harrisimon Where in the `requireOwnership` function is the cannot read property of `_id` failing on. If it's on the line `const owner = resource.owner._id ? resource.owner._id : resource.owner` then the doc you are getting back might not have an owner field. If its `!requestObject.user._id.equals(owner)` are you sending back the user in the request? console.log(req.user._id) to see if it's there

**Comment by harrisimon** [comment]
Yup! The user is there
This is the response body
```
the game {
  _id: new ObjectId("635fcd6336d406911f5e7675"),
  name: 'Futurama Quiz',
  questions: [
    {
      question: 'What is the best gator?',
      correctAnswer: 'Frosted',
      incorrectAnswers: [Array],
      category: 'Art',
      type: 'True / False',
      difficulty: 'Hard',
      _id: new ObjectId("635fce0636d406911f5e767f")
    },
    {
      question: 'What is the best donut?',
      correctAnswer: 'All donuts',
      incorrectAnswers: [Array],
      category: 'Art',
      type: 'True / False',
      difficulty: 'Hard',
      _id: new ObjectId("635fce3c36d406911f5e7687")
    },
    {
      question: 'What is the best gum?',
      correctAnswer: 'All donuts',
      incorrectAnswers: [Array],
      category: 'Art',
      type: 'True / False',
      difficulty: 'Hard',
      _id: new ObjectId("635fd6136503e19a1124182c")
    }
  ],
  createdAt: 2022-10-31T13:28:03.254Z,
  updatedAt: 2022-10-31T14:07:02.201Z,
  __v: 3,
  id: '635fcd6336d406911f5e7675'
}
the user new ObjectId("635edf7a8715223e3b621e3e")
```
and for the game model owner is there
```js
const mongoose = require('mongoose')
const questionSchema = require('./question')

const gameSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            required: true
        },
        questions: [questionSchema],
        owner: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        }
    },
    {
        timestamps: true,
        toObject: { virtuals: true },
        toJSON: { virtuals: true }
    }
)

module.exports = mongoose.model('Game', gameSchema)




```

**Comment by harrisimon** [comment]
Think I figured it out! Still have to test but I wasn't setting owner in creating--oof

**Comment by harrisimon** [comment]
Yup! That'll do it 🙃
