### ISSUE TITLE
Trying to get my routes to work #solved

### ISSUE THREAD

**Issue by smoothbrady** [sei-ec-remote/team-project-issues#97]
**Describe the bug**
_A clear and concise description of what the bug is._

getting a 422 error.

**What is the problem you are trying to solve?**

getting my information to pull from the postman.

**Expected behavior**
_A clear and concise description of what you expected to happen._

so I put the scheme objects into my postman but it's not returning and processing my information.

**What is the actual behavior?**
_A clear and concise description of what actually happened._
It would return my objects but follow with error codes.

**Post any code you think might be relevant (one fenced block per file)**
```const mongoose = require('mongoose')

const paymentInfoSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            required: true
        },
        // bcrypt
        card_number: {
            type: String,
            required: true
        },
        expiration: {
            type: String,
            required: true
        },
        // bcrypt
        sec_code: {
            type: Number,
            required: true
        },
    // Add billing adddress in later
    }, {
        timestamps: true
    })

module.exports = mongoose.model('PaymentInfo', paymentInfoSchema)


```router.post('/paymentInfo', (req, res, next) => {
	// req.body.paymentInfo.owner = req.user.id
	PaymentInfo.create(req.body.paymentInfo)
		.then((payment) => {
            console.log(payment)
			res.status(201).json({payments: payment.toObject() })
		})
		.catch(next)
})



**What is your best guess as to the source of the problem?**

I looked up what 422 and rewrite some of my code and still couldn't find the solution.

**What things have you already tried to solve the problem?**

![Screenshot 2022-10-31 191929](https://user-images.githubusercontent.com/112364309/199132791-723d730c-8077-4e88-93d1-b55212abfe32.png)
![Screenshot 2022-10-31 191943](https://user-images.githubusercontent.com/112364309/199132803-b9062cfa-d29e-4dec-8b78-6dc878e05929.png)
![Screenshot 2022-10-31 192010](https://user-images.githubusercontent.com/112364309/199132807-3a13ec19-5086-4f7b-9941-0b82120317cd.png)
![Screenshot 2022-10-31 192024](https://user-images.githubusercontent.com/112364309/199132810-cd4ec580-f1ef-4313-a9ed-7bccc8e427e6.png)


**Additional context**
Add any other context about the problem here.



**Paste a link to your repository here**
https://github.com/smoothbrady/global-back

**Comment by timmshinbone** [comment]
422 unprocessable entity means that something about your request is not in the right format. Share the request you're sending to this route so we can check that out.

**Comment by smoothbrady** [comment]
![Screenshot 2022-11-01 084018](https://user-images.githubusercontent.com/112364309/199246976-9506f79b-c5f0-483b-b9b2-382430a707aa.png)

**Comment by smoothbrady** [comment]
i believe this is what i needed to send if i understood you correctly

**Comment by timmshinbone** [comment]
That's perfect, so, looking at your routes, you're trying to send your database a query with `PaymentInfo.create(req.body.paymentInfo)`, which means your request body needs an item called `paymentInfo`, but currently your req.body doesn't have that. Your data needs to be shaped like this:
```json
{
     "paymentInfo" : 
           {
                <the request body from the screenshot goes here>
           }
}
```

**Comment by smoothbrady** [comment]
awesome, it worked! I thought i had done everything correctly just still learning postman lol
