### ISSUE TITLE
git merge

### ISSUE THREAD

**Issue by sam-phillips21** [sei-ec-remote/team-project-issues#98]
\
git issue... I knew there was going to be a merge conflict. I resolved it locally and tried to merge. It was rejected. Git checked me out to a new branch> I think it should be easy to fix but i do not want to move forward without some input... 
<img width="1728" alt="Screen Shot 2022-10-31 at 7 27 09 PM" src="https://user-images.githubusercontent.com/112962554/199146283-a1d73d74-4dac-413d-9413-783a47c2710b.png">

**Comment by sam-phillips21** [comment]
help... i aborted the rebase and tried to pull back down and it wont let me. Ive merged the conflicts again... and now it wants me to rebase again...

**Comment by ejparnell** [comment]
@sam-phillips21 Please use the issue queue questions and fill them out to the best of your abilities and reopen your issue when this is complete. Please do not remove the questions all together they are there to help us help you 😄
