### ISSUE TITLE
Trying to  use socket io to create chat with users.

### ISSUE THREAD

**Issue by nguyenpham207** [sei-ec-remote/team-project-issues#99]
**Describe the bug**
_A clear and concise description of what the bug is._

Having a problem setting up socket io for live chat.

**What is the problem you are trying to solve?**

I don't know if I installed the right version of the socket io.

**Expected behavior**
_A clear and concise description of what you expected to happen._

could be a syntax error importing socket io

**What is the actual behavior?**
_A clear and concise description of what actually happened._

we are trying to build a dating app with live chat so users could chat with each other. And I'm trying to install and set up socket io but could not get it to work.

**Post any code you think might be relevant (one fenced block per file)**
```js



```

**What is your best guess as to the source of the problem?**

Im struggling to figure it out.

**What things have you already tried to solve the problem?**

google and trying to find the right syntax for the up-to-date version.

**Additional context**
![Screen Shot 2022-11-01 at 12 28 02 AM](https://user-images.githubusercontent.com/110972681/199181498-be1b3f8c-115b-4ab6-91c3-1f5e4e582084.png)

**Paste a link to your repository here**
https://github.com/skbarbee/PetMatchBackEnd
https://github.com/skbarbee/petMatch

**Comment by kestler01** [comment]
try starting here and following the [ tutorial implementation ](https://socket.io/get-started/private-messaging-part-1/)
by implementing an initial bit in a separate repo to allow you to understand whats going on before breaking your app

**Comment by nguyenpham207** [comment]
this was an option in our project. Just want to know how it works.
